
var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.Oe||(h.Oe=0);h.Oe++;
(function(a){function b(n,r,p){var t=new XMLHttpRequest;t.open("GET",n,!0);t.responseType="arraybuffer";t.onprogress=function(u){var v=r;u.total&&(v=u.total);if(u.loaded){t.ge?h.we[n].loaded=u.loaded:(t.ge=!0,h.we||(h.we={}),h.we[n]={loaded:u.loaded,total:v});var z=v=u=0,C;for(C in h.we){var H=h.we[C];u+=H.total;v+=H.loaded;z++}u=Math.ceil(u*h.Oe/z);h.setStatus&&h.setStatus("Downloading data... ("+v+"/"+u+")")}else!h.we&&h.setStatus&&h.setStatus("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+
n);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)p(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function c(n){console.error("package error:",n)}function d(){function n(u,v,z){this.start=u;this.Be=v;this.audio=z}function r(u){if(!u)throw"Loading data file failed."+Error().stack;if(!(u instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);n.prototype.cf=u;u=a.files;for(var v=0;v<
u.length;++v)n.prototype.ge[u[v].filename].onload();h.removeRunDependency("datafile_basque.data")}h.FS_createPath("/","assets",!0,!0);h.FS_createPath("/assets","data",!0,!0);h.FS_createPath("/assets","audio",!0,!0);h.FS_createPath("/assets","icons",!0,!0);h.FS_createPath("/assets/icons","basque_logo.iconset",!0,!0);h.FS_createPath("/assets","fonts",!0,!0);h.FS_createPath("/assets","images",!0,!0);n.prototype={ge:{},open:function(u,v){this.name=v;this.ge[v]=this;h.addRunDependency("fp "+this.name)},
send:function(){},onload:function(){this.bf(this.cf.subarray(this.start,this.Be))},bf:function(u){h.FS_createDataFile(this.name,null,u,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.ge[this.name]=null}};for(var p=a.files,t=0;t<p.length;++t)(new n(p[t].start,p[t].end,p[t].audio)).open("GET",p[t].filename);h.addRunDependency("datafile_basque.data");h.sf||(h.sf={});h.sf["basque.data"]={$f:!1};m?(r(m),m=null):g=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=h.locateFile?h.locateFile("basque.data",""):"basque.data",f=a.remote_package_size,g=null,m=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;m||b(e,f,function(n){g?(g(n),g=null):m=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))})({files:[{filename:"/assets/data/map_layout_9.txt",start:0,end:2153,audio:0},{filename:"/assets/data/map_layout_2.txt",start:2153,end:28018,audio:0},{filename:"/assets/data/map_layout_8.txt",start:28018,end:30171,audio:0},{filename:"/assets/data/map_layout_5.txt",
start:30171,end:56036,audio:0},{filename:"/assets/data/map_layout_1.txt",start:56036,end:81901,audio:0},{filename:"/assets/data/map_layout_3.txt",start:81901,end:107766,audio:0},{filename:"/assets/data/map_layout.txt",start:107766,end:153120,audio:0},{filename:"/assets/data/map_attributes.txt",start:153120,end:155620,audio:0},{filename:"/assets/data/map_layout_4.txt",start:155620,end:181485,audio:0},{filename:"/assets/data/map_library.txt",start:181485,end:181778,audio:0},{filename:"/assets/data/map_layout_6.txt",
start:181778,end:183931,audio:0},{filename:"/assets/data/map_layout_7.txt",start:183931,end:186084,audio:0},{filename:"/assets/data/map_layout_0.txt",start:186084,end:231438,audio:0},{filename:"/assets/audio/Basque_sample_music.ogg",start:231438,end:4472344,audio:1},{filename:"/assets/icons/basque_logo.png",start:4472344,end:4482987,audio:0},{filename:"/assets/icons/basque_logo.icns",start:4482987,end:4740714,audio:0},{filename:"/assets/icons/basque_logo.ico",start:4740714,end:4843544,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_32x32.png",
start:4843544,end:4847746,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_8x8@2x.png",start:4847746,end:4850653,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_64x64@2x.png",start:4850653,end:4870623,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_32x32@2x.png",start:4870623,end:4878803,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_128x128@2x.png",start:4878803,end:4931191,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_512x512@2x.png",start:4931191,
end:5158980,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_16x16@2x.png",start:5158980,end:5163182,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_256x256.png",start:5163182,end:5215570,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_128x128.png",start:5215570,end:5235540,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_512x512.png",start:5235540,end:5355911,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_64x64.png",start:5355911,end:5364091,
audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_1024x1024.png",start:5364091,end:5591880,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_16x16.png",start:5591880,end:5594787,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_256x256@2x.png",start:5594787,end:5715158,audio:0},{filename:"/assets/fonts/backpacker_license.pdf",start:5715158,end:6021361,audio:0},{filename:"/assets/fonts/BPtypewrite.ttf",start:6021361,end:6100533,audio:0},{filename:"/assets/images/basque_logo_scaled_v3.png",
start:6100533,end:6124657,audio:0},{filename:"/assets/images/basque_logo.png",start:6124657,end:6126132,audio:0},{filename:"/assets/images/basque_logo_scaled.png",start:6126132,end:6149996,audio:0},{filename:"/assets/images/README.md",start:6149996,end:6150182,audio:0},{filename:"/assets/images/tiles_packed.png",start:6150182,end:6157212,audio:0},{filename:"/assets/images/character.png",start:6157212,end:6161192,audio:0},{filename:"/assets/images/basque_logo_scaled_v2.png",start:6161192,end:6184967,
audio:0}],remote_package_size:6184967,package_uuid:"a4f61b77-a1ba-4d67-a829-595114329faf"});var aa={},ba;for(ba in h)h.hasOwnProperty(ba)&&(aa[ba]=h[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var ka="",la,ma,na,oa,pa,ra;
if(ia)ka=ha?require("path").dirname(ka)+"/":__dirname+"/",la=function(a,b){pa||(pa=require("fs"));ra||(ra=require("path"));a=ra.normalize(a);return pa.readFileSync(a,b?null:"utf8")},na=function(a){a=la(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof sa))throw a;}),process.on("unhandledRejection",
l),ea=function(a){process.exit(a)},h.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(la=function(a){return read(a)}),na=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?ka=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ka=document.currentScript.src),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.lastIndexOf("/")+1):"",la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ma=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},oa=function(a){document.title=a};var ta=h.print||console.log.bind(console),k=h.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(h[ba]=aa[ba]);aa=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);
function ua(a){va||(va={});va[a]||(va[a]=1,k(a))}var va,wa=0,xa;h.wasmBinary&&(xa=h.wasmBinary);var noExitRuntime;h.noExitRuntime&&(noExitRuntime=h.noExitRuntime);"object"!==typeof WebAssembly&&l("no native wasm support detected");
function ya(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":q[a>>0]=b;break;case "i8":q[a>>0]=b;break;case "i16":Aa[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":x=[b>>>0,(y=b,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[a>>2]=x[0];w[a+4>>2]=x[1];break;case "float":A[a>>2]=b;break;case "double":B[a>>3]=b;break;default:l("invalid type for setValue: "+c)}}var Ba,Ca=!1;
function assert(a,b){a||l("Assertion failed: "+b)}var Da="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ea(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Da)return Da.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?Ea(E,a,b):""}
function Fa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function F(a,b,c){return Fa(a,E,b,c)}
function Ga(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ha(a){var b=Ga(a)+1,c=G(b);c&&Fa(a,q,c,b);return c}function Ia(a){var b=Ga(a)+1,c=Ja(b);Fa(a,q,c,b);return c}var Ka,q,E,Aa,La,w,Ma,A,B;
function Na(a){Ka=a;h.HEAP8=q=new Int8Array(a);h.HEAP16=Aa=new Int16Array(a);h.HEAP32=w=new Int32Array(a);h.HEAPU8=E=new Uint8Array(a);h.HEAPU16=La=new Uint16Array(a);h.HEAPU32=Ma=new Uint32Array(a);h.HEAPF32=A=new Float32Array(a);h.HEAPF64=B=new Float64Array(a)}var Oa=h.INITIAL_MEMORY||1610612736;h.wasmMemory?Ba=h.wasmMemory:Ba=new WebAssembly.Memory({initial:Oa/65536,maximum:32768});Ba&&(Ka=Ba.buffer);Oa=Ka.byteLength;Na(Ka);var I,Pa=[],Qa=[],Ra=[],Sa=[],Ta=[];
function Ua(){var a=h.preRun.shift();Pa.unshift(a)}var Va=0,Wa=null,Xa=null;function Ya(){Va++;h.monitorRunDependencies&&h.monitorRunDependencies(Va)}function Za(){Va--;h.monitorRunDependencies&&h.monitorRunDependencies(Va);if(0==Va&&(null!==Wa&&(clearInterval(Wa),Wa=null),Xa)){var a=Xa;Xa=null;a()}}h.preloadedImages={};h.preloadedAudios={};function l(a){if(h.onAbort)h.onAbort(a);k(a);Ca=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function $a(a){var b=ab;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function bb(){return $a("data:application/octet-stream;base64,")}var ab="basque.wasm";if(!bb()){var cb=ab;ab=h.locateFile?h.locateFile(cb,ka):ka+cb}function db(){try{if(xa)return new Uint8Array(xa);if(na)return na(ab);throw"both async and sync fetching of the wasm failed";}catch(a){l(a)}}
function eb(){return xa||!fa&&!ha||"function"!==typeof fetch||$a("file://")?Promise.resolve().then(db):fetch(ab,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+ab+"'";return a.arrayBuffer()}).catch(function(){return db()})}
var y,x,hb={63882:function(a){a=D(a)+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");a=fb(a);var b=G(a.length);a.subarray||a.slice?E.set(a,b):E.set(new Uint8Array(a),b);return b},101452:function(a,b,c){h.SDL2||(h.SDL2={});var d=h.SDL2;d.xf!==h.canvas&&(d.pe=h.createContext(h.canvas,!1,!0),d.xf=h.canvas);if(d.w!==a||d.Ef!==b||d.Gf!==d.pe)d.image=d.pe.createImageData(a,b),d.w=a,d.Ef=b,d.Gf=d.pe;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&
a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=w[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Yf!==a&&(d.yf=new Int32Array(a.buffer),d.zf=new Uint8Array(a.buffer)),a=d.yf,c=a.length,a.set(w.subarray(b,b+c)),a=d.zf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.pe.putImageData(d.image,0,0);return 0},102931:function(a,
b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=w[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>16&255;b[m+3]=r>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(w.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=G(c.length+
1);F(c,d,c.length+1);return d},103920:function(a){h.canvas&&(h.canvas.style.cursor=D(a));return 0},104013:function(){h.canvas&&(h.canvas.style.cursor="none")},105238:function(){return screen.width},105265:function(){return screen.height},105293:function(){return window.innerWidth},105325:function(){return window.innerHeight},105403:function(a){"undefined"!==typeof oa&&oa(D(a));return 0},105537:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},105703:function(){return"undefined"!==
typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},105929:function(a){"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.fe||("undefined"!==typeof AudioContext?b.fe=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.fe=new webkitAudioContext),b.fe&&gb(b.fe));return void 0===b.fe?-1:0},106482:function(){return h.SDL2.fe.sampleRate},106552:function(a,b,c,d){function e(){}
function f(m){void 0!==g.capture.Ee&&(clearTimeout(g.capture.Ee),g.capture.Ee=void 0);g.capture.Ie=g.fe.createMediaStreamSource(m);g.capture.ie=g.fe.createScriptProcessor(b,a,1);g.capture.ie.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Ne=n.inputBuffer,n=[d],I.get(c).apply(null,n))};g.capture.Ie.connect(g.capture.ie);g.capture.ie.connect(g.fe.destination);g.capture.stream=m}var g=h.SDL2;g.capture.Le=g.fe.createBuffer(a,b,g.fe.sampleRate);
g.capture.Le.getChannelData(0).fill(0);g.capture.Ee=setTimeout(function(){g.capture.Ne=g.capture.Le;var m=[d];I.get(c).apply(null,m)},b/g.fe.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},108204:function(a,b,c,d){var e=h.SDL2;e.audio.ie=e.fe.createScriptProcessor(b,0,a);e.audio.ie.onaudioprocess=
function(f){void 0!==e&&void 0!==e.audio&&(e.audio.af=f.outputBuffer,f=[d],I.get(c).apply(null,f))};e.audio.ie.connect(e.fe.destination)},108614:function(a,b){for(var c=h.SDL2,d=c.capture.Ne.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ne.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)ya(a+4*g,f[g]);else for(g=0;g<b;++g)ya(a+4*(g*d+e),f[g])}},109219:function(a,b){for(var c=
h.SDL2,d=c.audio.af.numberOfChannels,e=0;e<d;++e){var f=c.audio.af.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=A[a+(g*d+e<<2)>>2]}},109699:function(a){var b=h.SDL2;if(a){void 0!==b.capture.Ee&&clearTimeout(b.capture.Ee);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==
b.capture.ie&&(b.capture.ie.onaudioprocess=function(){},b.capture.ie.disconnect(),b.capture.ie=void 0);void 0!==b.capture.Ie&&(b.capture.Ie.disconnect(),b.capture.Ie=void 0);void 0!==b.capture.Le&&(b.capture.Le=void 0);b.capture=void 0}else void 0!=b.audio.ie&&(b.audio.ie.disconnect(),b.audio.ie=void 0),b.audio=void 0;void 0!==b.fe&&void 0===b.audio&&void 0===b.capture&&(b.fe.close(),b.fe=void 0)}};function ib(a,b,c){a.addEventListener(b,c,{once:!0})}
function gb(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&ib(d,c,function(){"suspended"===a.state&&a.resume()})})})}function jb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.ff;"number"===typeof c?void 0===b.Fe?I.get(c)():I.get(c)(b.Fe):c(void 0===b.Fe?null:b.Fe)}}}function kb(a){w[lb()>>2]=a}
function mb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function nb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=mb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ob(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function pb(a){if("/"===a)return"/";a=nb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function qb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){l("randomDevice")}}
function rb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=mb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var sb=[];function tb(a,b){sb[a]={input:[],output:[],ze:b};ub(a,vb)}
var vb={open:function(a){var b=sb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ze.flush(a.tty)},flush:function(a){a.tty.ze.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ze.gf)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.ze.gf(a.tty)}catch(m){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.ze.Se)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.ze.Se(a.tty,b[c+e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},wb={gf:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.ge?Buffer.ge(256):new Buffer(256),d=0;try{d=pa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=fb(b,!0)}return a.input.shift()},Se:function(a,b){null===b||10===b?(ta(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ta(Ea(a.output,0)),a.output=[])}},xb={Se:function(a,b){null===b||10===b?(k(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(Ea(a.output,0)),a.output=[])}},K={re:null,se:function(){return K.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.re||(K.re={dir:{node:{qe:K.ce.qe,je:K.ce.je,lookup:K.ce.lookup,Je:K.ce.Je,rename:K.ce.rename,unlink:K.ce.unlink,rmdir:K.ce.rmdir,readdir:K.ce.readdir,symlink:K.ce.symlink},stream:{ve:K.de.ve}},file:{node:{qe:K.ce.qe,je:K.ce.je},stream:{ve:K.de.ve,read:K.de.read,write:K.de.write,We:K.de.We,mf:K.de.mf,pf:K.de.pf}},link:{node:{qe:K.ce.qe,je:K.ce.je,readlink:K.ce.readlink},stream:{}},$e:{node:{qe:K.ce.qe,
je:K.ce.je},stream:yb}});c=zb(a,b,c,d);L(c.mode)?(c.ce=K.re.dir.node,c.de=K.re.dir.stream,c.be={}):32768===(c.mode&61440)?(c.ce=K.re.file.node,c.de=K.re.file.stream,c.ee=0,c.be=null):40960===(c.mode&61440)?(c.ce=K.re.link.node,c.de=K.re.link.stream):8192===(c.mode&61440)&&(c.ce=K.re.$e.node,c.de=K.re.$e.stream);c.timestamp=Date.now();a&&(a.be[b]=c);return c},ag:function(a){if(a.be&&a.be.subarray){for(var b=[],c=0;c<a.ee;++c)b.push(a.be[c]);return b}return a.be},bg:function(a){return a.be?a.be.subarray?
a.be.subarray(0,a.ee):new Uint8Array(a.be):new Uint8Array(0)},df:function(a,b){var c=a.be?a.be.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.be,a.be=new Uint8Array(b),0<a.ee&&a.be.set(c.subarray(0,a.ee),0))},Pf:function(a,b){if(a.ee!=b)if(0==b)a.be=null,a.ee=0;else{if(!a.be||a.be.subarray){var c=a.be;a.be=new Uint8Array(b);c&&a.be.set(c.subarray(0,Math.min(b,a.ee)))}else if(a.be||(a.be=[]),a.be.length>b)a.be.length=b;else for(;a.be.length<b;)a.be.push(0);a.ee=
b}},ce:{qe:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.ee:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.wf=4096;b.blocks=Math.ceil(b.size/b.wf);return b},je:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.Pf(a,
b.size)},lookup:function(){throw Ab[44];},Je:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(L(a.mode)){try{var d=Bb(b,c)}catch(f){}if(d)for(var e in d.be)throw new J(55);}delete a.parent.be[a.name];a.name=c;b.be[c]=a;a.parent=b},unlink:function(a,b){delete a.be[b]},rmdir:function(a,b){var c=Bb(a,b),d;for(d in c.be)throw new J(55);delete a.be[b]},readdir:function(a){var b=[".",".."],c;for(c in a.be)a.be.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,
b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},de:{read:function(a,b,c,d,e){var f=a.node.be;if(e>=a.node.ee)return 0;a=Math.min(a.node.ee-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===q.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.be||a.be.subarray)){if(f)return a.be=b.subarray(c,c+d),a.ee=d;if(0===a.ee&&0===e)return a.be=
b.slice(c,c+d),a.ee=d;if(e+d<=a.ee)return a.be.set(b.subarray(c,c+d),e),d}K.df(a,e+d);if(a.be.subarray&&b.subarray)a.be.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.be[e+f]=b[c+f];a.ee=Math.max(a.ee,e+d);return d},ve:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ee);if(0>b)throw new J(28);return b},We:function(a,b,c){K.df(a.node,b+c);a.node.ee=Math.max(a.node.ee,b+c)},mf:function(a,b,c,d,e,f){assert(0===b);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.be;
if(f&2||a.buffer!==Ka){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=G(f);c<f;)q[b+c++]=0;c=b;if(!c)throw new J(48);q.set(a,c)}else d=!1,c=a.byteOffset;return{ig:c,Vf:d}},pf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.de.write(a,b,0,d,c,!1);return 0}}},Cb=null,Db={},Eb=[],Fb=1,Gb=null,Hb=!0,M={},J=null,Ab={};
function Ib(a,b){a=rb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ef:!0,Te:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Te)throw new J(32);a=mb(a.split("/").filter(function(g){return!!g}),!1);var e=Cb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Bb(e,a[d]);c=nb(c+"/"+a[d]);e.xe&&(!f||f&&b.ef)&&(e=e.xe.root);if(!f||b.He)for(f=0;40960===(e.mode&61440);)if(e=Jb(c),c=rb(ob(c),e),e=Ib(c,{Te:b.Te}).node,40<f++)throw new J(32);}return{path:c,node:e}}
function Kb(a){for(var b;;){if(a===a.parent)return a=a.se.nf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Lb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Gb.length}function Mb(a){var b=Lb(a.parent.id,a.name);if(Gb[b]===a)Gb[b]=a.ye;else for(b=Gb[b];b;){if(b.ye===a){b.ye=a.ye;break}b=b.ye}}
function Bb(a,b){var c;if(c=(c=Nb(a,"x"))?c:a.ce.lookup?0:2)throw new J(c,a);for(c=Gb[Lb(a.id,b)];c;c=c.ye){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ce.lookup(a,b)}function zb(a,b,c,d){a=new Ob(a,b,c,d);b=Lb(a.parent.id,a.name);a.ye=Gb[b];return Gb[b]=a}function L(a){return 16384===(a&61440)}var Pb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};
function Qb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Nb(a,b){if(Hb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Rb(a,b){try{return Bb(a,b),20}catch(c){}return Nb(a,"wx")}function Sb(a,b,c){try{var d=Bb(a,b)}catch(e){return e.ne}if(a=Nb(a,"wx"))return a;if(c){if(!L(d.mode))return 54;if(d===d.parent||"/"===Kb(d))return 10}else if(L(d.mode))return 31;return 0}
function Tb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Eb[a])return a;throw new J(33);}function Ub(a,b){Vb||(Vb=function(){},Vb.prototype={});var c=new Vb,d;for(d in a)c[d]=a[d];a=c;b=Tb(b);a.fd=b;return Eb[b]=a}var yb={open:function(a){a.de=Db[a.node.rdev].de;a.de.open&&a.de.open(a)},ve:function(){throw new J(70);}};function ub(a,b){Db[a]={de:b}}
function Wb(a,b){var c="/"===b,d=!b;if(c&&Cb)throw new J(10);if(!c&&!d){var e=Ib(b,{ef:!1});b=e.path;e=e.node;if(e.xe)throw new J(10);if(!L(e.mode))throw new J(54);}b={type:a,hg:{},nf:b,Mf:[]};a=a.se(b);a.se=b;b.root=a;c?Cb=a:e&&(e.xe=b,e.se&&e.se.Mf.push(b))}function Xb(a,b,c){var d=Ib(a,{parent:!0}).node;a=pb(a);if(!a||"."===a||".."===a)throw new J(28);var e=Rb(d,a);if(e)throw new J(e);if(!d.ce.Je)throw new J(63);return d.ce.Je(d,a,b,c)}function Yb(a){Xb(a,16895,0)}
function Zb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Xb(a,b|8192,c)}function $b(a,b){if(!rb(a))throw new J(44);var c=Ib(b,{parent:!0}).node;if(!c)throw new J(44);b=pb(b);var d=Rb(c,b);if(d)throw new J(d);if(!c.ce.symlink)throw new J(63);c.ce.symlink(c,b,a)}
function ac(a){var b=Ib(a,{parent:!0}).node,c=pb(a),d=Bb(b,c),e=Sb(b,c,!1);if(e)throw new J(e);if(!b.ce.unlink)throw new J(63);if(d.xe)throw new J(10);try{M.willDeletePath&&M.willDeletePath(a)}catch(f){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.ce.unlink(b,c);Mb(d);try{if(M.onDeletePath)M.onDeletePath(a)}catch(f){k("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}}
function Jb(a){a=Ib(a).node;if(!a)throw new J(44);if(!a.ce.readlink)throw new J(28);return rb(Kb(a.parent),a.ce.readlink(a))}function bc(a,b){var c;"string"===typeof a?c=Ib(a,{He:!0}).node:c=a;if(!c.ce.je)throw new J(63);c.ce.je(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function cc(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=Pb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=nb(a);try{f=Ib(a,{He:!(b&131072)}).node}catch(m){}}e=!1;if(b&64)if(f){if(b&128)throw new J(20);}else f=Xb(a,c,0),e=!0;if(!f)throw new J(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!L(f.mode))throw new J(54);if(!e&&(c=f?40960===(f.mode&61440)?32:L(f.mode)&&
("r"!==Qb(b)||b&512)?31:Nb(f,Qb(b)):44))throw new J(c);if(b&512){c=f;var g;"string"===typeof c?g=Ib(c,{He:!0}).node:g=c;if(!g.ce.je)throw new J(63);if(L(g.mode))throw new J(31);if(32768!==(g.mode&61440))throw new J(28);if(c=Nb(g,"w"))throw new J(c);g.ce.je(g,{size:0,timestamp:Date.now()})}b&=-131713;d=Ub({node:f,path:Kb(f),flags:b,seekable:!0,position:0,de:f.de,Sf:[],error:!1},d);d.de.open&&d.de.open(d);!h.logReadFiles||b&1||(dc||(dc={}),a in dc||(dc[a]=1,k("FS.trackingDelegate error on read file: "+
a)));try{M.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),M.onOpenFile(a,f))}catch(m){k("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function ec(a){if(null===a.fd)throw new J(8);a.Pe&&(a.Pe=null);try{a.de.close&&a.de.close(a)}catch(b){throw b;}finally{Eb[a.fd]=null}a.fd=null}
function fc(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.de.ve)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.de.ve(a,b,c);a.Sf=[]}
function hc(a,b,c,d,e,f){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(L(a.node.mode))throw new J(31);if(!a.de.write)throw new J(28);a.seekable&&a.flags&1024&&fc(a,0,2);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new J(70);b=a.de.write(a,b,c,d,e,f);g||(a.position+=b);try{if(a.path&&M.onWriteToFile)M.onWriteToFile(a.path)}catch(m){k("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function ic(){J||(J=function(a,b){this.node=b;this.Qf=function(c){this.ne=c};this.Qf(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){Ab[a]=new J(a);Ab[a].stack="<generic error, no stack>"}))}var jc;function kc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function lc(a,b){a="string"===typeof a?a:Kb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=nb(a+"/"+c);try{Yb(d)}catch(e){}a=d}}return d}
function mc(a,b,c,d){a=nb(("string"===typeof a?a:Kb(a))+"/"+b);c=kc(c,d);return Xb(a,(void 0!==c?c:438)&4095|32768,0)}function nc(a,b,c,d,e,f){a=b?nb(("string"===typeof a?a:Kb(a))+"/"+b):a;d=kc(d,e);e=Xb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var g=c.length;b<g;++b)a[b]=c.charCodeAt(b);c=a}bc(e,d|146);a=cc(e,"w");hc(a,c,0,c.length,0,f);ec(a);bc(e,d)}return e}
function oc(a,b,c,d){a=nb(("string"===typeof a?a:Kb(a))+"/"+b);b=kc(!!c,!!d);oc.kf||(oc.kf=64);var e=oc.kf++<<8|0;ub(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,g,m,n){for(var r=0,p=0;p<n;p++){try{var t=c()}catch(u){throw new J(29);}if(void 0===t&&0===r)throw new J(6);if(null===t||void 0===t)break;r++;g[m+p]=t}r&&(f.node.timestamp=Date.now());return r},write:function(f,g,m,n){for(var r=0;r<n;r++)try{d(g[m+r])}catch(p){throw new J(29);}n&&
(f.node.timestamp=Date.now());return r}});return Zb(a,b,e)}
function pc(a){if(a.Kf||a.Lf||a.link||a.be)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(la)try{a.be=fb(la(a.url),!0),a.ee=a.be.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||kb(29);return b}
function rc(a,b,c,d,e){function f(){this.Qe=!1;this.ge=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var t=p%this.chunkSize;return this.hf(p/this.chunkSize|0)[t]}};f.prototype.Be=function(p){this.hf=p};f.prototype.Ye=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var t=Number(p.getResponseHeader("Content-length")),u,v=(u=p.getResponseHeader("Accept-Ranges"))&&
"bytes"===u;p=(u=p.getResponseHeader("Content-Encoding"))&&"gzip"===u;var z=1048576;v||(z=t);var C=this;C.Be(function(H){var za=H*z,qa=(H+1)*z-1;qa=Math.min(qa,t-1);if("undefined"===typeof C.ge[H]){var qc=C.ge;if(za>qa)throw Error("invalid range ("+za+", "+qa+") or no bytes requested!");if(qa>t-1)throw Error("only "+t+" bytes available! programmer error!");var N=new XMLHttpRequest;N.open("GET",c,!1);t!==z&&N.setRequestHeader("Range","bytes="+za+"-"+qa);"undefined"!=typeof Uint8Array&&(N.responseType=
"arraybuffer");N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);if(!(200<=N.status&&300>N.status||304===N.status))throw Error("Couldn't load "+c+". Status: "+N.status);za=void 0!==N.response?new Uint8Array(N.response||[]):fb(N.responseText||"",!0);qc[H]=za}if("undefined"===typeof C.ge[H])throw Error("doXHR failed!");return C.ge[H]});if(p||!t)z=t=1,z=t=this.hf(0).length,ta("LazyFiles on gzip forces download of the whole file when length is accessed");this.vf=
t;this.uf=z;this.Qe=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;Object.defineProperties(g,{length:{get:function(){this.Qe||this.Ye();return this.vf}},chunkSize:{get:function(){this.Qe||this.Ye();return this.uf}}});var m=void 0}else m=c,g=void 0;var n=mc(a,b,d,e);g?n.be=g:m&&(n.be=null,n.url=m);Object.defineProperties(n,{ee:{get:function(){return this.be.length}}});
var r={};Object.keys(n.de).forEach(function(p){var t=n.de[p];r[p]=function(){if(!pc(n))throw new J(29);return t.apply(null,arguments)}});r.read=function(p,t,u,v,z){if(!pc(n))throw new J(29);p=p.node.be;if(z>=p.length)return 0;v=Math.min(p.length-z,v);if(p.slice)for(var C=0;C<v;C++)t[u+C]=p[z+C];else for(C=0;C<v;C++)t[u+C]=p.get(z+C);return v};n.de=r;return n}
function sc(a,b,c,d,e,f,g,m,n,r){function p(v){function z(H){r&&r();m||nc(a,b,H,d,e,n);f&&f();Za(u)}var C=!1;h.preloadPlugins.forEach(function(H){!C&&H.canHandle(t)&&(H.handle(v,t,z,function(){g&&g();Za(u)}),C=!0)});C||z(v)}tc();var t=b?rb(nb(a+"/"+b)):a,u="cp "+t;Ya(u);"string"==typeof c?uc(c,function(v){p(v)},g):p(c)}var vc={},Vb,dc,wc=void 0;function xc(){wc+=4;return w[wc-4>>2]}function yc(a){a=Eb[a];if(!a)throw new J(8);return a}var zc;
ia?zc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?zc=dateNow:zc=function(){return performance.now()};
function Ac(a,b){Bc=a;Cc=b;if(Dc)if(0==a)Ec=function(){var d=Math.max(0,Fc+b-zc())|0;setTimeout(Gc,d)};else if(1==a)Ec=function(){Hc(Gc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Ec=function(){setImmediate(Gc)}}}
function Ic(a,b,c,d,e){noExitRuntime=!0;assert(!Dc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Dc=a;Jc=d;var f=Kc;Gc=function(){if(!Ca)if(0<Lc.length){var g=Date.now(),m=Lc.shift();m.ff(m.Fe);if(Mc){var n=Mc,r=0==n%1?n-1:Math.floor(n);Mc=m.Xf?r:(8*n+(r+.5))/9}console.log('main loop blocker "'+m.name+'" took '+(Date.now()-g)+" ms");h.setStatus&&(g=h.statusMessage||
"Please wait...",m=Mc,n=Nc.Zf,m?m<n?h.setStatus(g+" ("+(n-m)+"/"+n+")"):h.setStatus(g):h.setStatus(""));f<Kc||setTimeout(Gc,0)}else if(!(f<Kc))if(Oc=Oc+1|0,1==Bc&&1<Cc&&0!=Oc%Cc)Ec();else{0==Bc&&(Fc=zc());a:if(!(Ca||h.preMainLoop&&!1===h.preMainLoop())){try{a()}catch(p){if(p instanceof sa||"unwind"==p)break a;p&&"object"===typeof p&&p.stack&&k("exception thrown: "+[p,p.stack]);throw p;}h.postMainLoop&&h.postMainLoop()}f<Kc||("object"===typeof SDL&&SDL.audio&&SDL.audio.Of&&SDL.audio.Of(),Ec())}};e||
(b&&0<b?Ac(0,1E3/b):Ac(1,1),Ec());if(c)throw"unwind";}var Ec=null,Kc=0,Dc=null,Jc=0,Bc=0,Cc=0,Oc=0,Lc=[],Nc={},Fc,Gc,Mc,Pc=!1,Qc=!1,Rc=[];
function tc(){function a(){Qc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!Sc){Sc=!0;try{Tc=!0}catch(c){Tc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Uc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Tc?null:console.log("warning: no BlobBuilder");
Vc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.qf||"undefined"!==typeof Vc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.qf=!0);h.preloadPlugins.push({canHandle:function(c){return!h.qf&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(Tc)try{g=new Blob([c],{type:Wc(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Wc(d)}))}catch(r){ua("Blob constructor present but fails: "+
r+"; falling back to blob builder")}g||(g=new Uc,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var m=Vc.createObjectURL(g),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=n.width;r.height=n.height;r.getContext("2d").drawImage(n,0,0);h.preloadedImages[d]=r;Vc.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");f&&f()};n.src=m}});h.preloadPlugins.push({canHandle:function(c){return!h.gg&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function g(t){n||(n=!0,h.preloadedAudios[d]=t,e&&e(c))}function m(){n||(n=!0,h.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(Tc){try{var r=new Blob([c],{type:Wc(d)})}catch(t){return m()}r=Vc.createObjectURL(r);var p=new Audio;p.addEventListener("canplaythrough",function(){g(p)},!1);p.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var t="",u=0,v=0,
z=0;z<c.length;z++)for(u=u<<8|c[z],v+=8;6<=v;){var C=u>>v-6&63;v-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[C]}2==v?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],t+="=="):4==v&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],t+="=");p.src="data:audio/x-"+d.substr(-3)+";base64,"+t;g(p)}};p.src=r;Xc(function(){g(p)})}else return m()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&
b.addEventListener("click",function(c){!Qc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Yc(a,b,c,d){if(b&&h.pe&&a==h.canvas)return h.pe;var e;if(b){var f={antialias:!1,alpha:!1,lf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!==typeof Zc&&(e=$c(a,f)))var m=ad[e].te}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof O,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.pe=m,b&&bd(e),h.Tf=b,Rc.forEach(function(n){n()}),tc());return m}var cd=!1,dd=void 0,ed=void 0;
function fd(a,b){function c(){Pc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=gd,dd&&d.requestPointerLock(),Pc=!0,ed?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=Ma[SDL.screen>>2]|8388608),hd(h.canvas),id()):hd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),ed?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=Ma[SDL.screen>>2]&
-8388609),hd(h.canvas),id()):hd(d));if(h.onFullScreen)h.onFullScreen(Pc);if(h.onFullscreen)h.onFullscreen(Pc)}dd=a;ed=b;"undefined"===typeof dd&&(dd=!0);"undefined"===typeof ed&&(ed=!1);var d=h.canvas;cd||(cd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function gd(){if(!Pc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var jd=0;function Hc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===jd)jd=b+1E3/60;else for(;b+2>=jd;)jd+=1E3/60;setTimeout(a,Math.max(jd-b,0))}}function Xc(a){noExitRuntime=!0;setTimeout(function(){Ca||a()},1E4)}
function Wc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function uc(a,b,c){var d="al "+a;ma(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Za(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ya(d)}var kd=[];function id(){var a=h.canvas;kd.forEach(function(b){b(a.width,a.height)})}
function hd(a,b,c){b&&c?(a.Uf=b,a.Ff=c):(b=a.Uf,c=a.Ff);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}ed?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Sc,Tc,Uc,Vc,P=12288,ld=!1,md=0,nd=0,od=0,Q={alpha:!1,depth:!1,stencil:!1,antialias:!1},pd={},qd;function rd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function sd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function td(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var ud=1,vd=[],R=[],wd=[],xd=[],yd=[],S=[],T=[],zd=[],ad=[],Ad=[],Bd={},Cd={},Dd=4;function U(a){Ed||(Ed=a)}function Fd(a){for(var b=ud++,c=a.length;c<b;c++)a[c]=null;return b}function $c(a,b){if(a=a.getContext("webgl",b)){var c=Fd(ad),d={cg:c,attributes:b,version:b.lf,te:a};a.canvas&&(a.canvas.Ae=d);ad[c]=d;("undefined"===typeof b.Bf||b.Bf)&&Gd(d);b=c}else b=0;return b}function bd(a){Hd=ad[a];h.pe=O=Hd&&Hd.te}
function Gd(a){a||(a=Hd);if(!a.Hf){a.Hf=!0;var b=a.te;rd(b);sd(b);td(b);b.me=b.getExtension("EXT_disjoint_timer_query");b.fg=b.getExtension("WEBGL_multi_draw");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var Zc={},Ed,Hd,Id=0;function Jd(){for(var a=Kd.length-1;0<=a;--a)Ld(a);Kd=[];Md=[]}var Md=[];function Nd(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in Md){var f=Md[e];if(f.Ve==a&&d(f.Xe,c))return}Md.push({Ve:a,rf:b,Xe:c});Md.sort(function(g,m){return g.rf<m.rf})}
function Od(a){for(var b=0;b<Md.length;++b)Md[b].Ve==a&&(Md.splice(b,1),--b)}function Pd(){if(Id&&Qd.ue)for(var a=0;a<Md.length;++a){var b=Md[a];Md.splice(a,1);--a;b.Ve.apply(null,b.Xe)}}var Kd=[];function Ld(a){var b=Kd[a];b.target.removeEventListener(b.he,b.Cf,b.ke);Kd.splice(a,1)}
function Rd(a){function b(d){++Id;Qd=a;Pd();a.oe(d);Pd();--Id}if(a.le)a.Cf=b,a.target.addEventListener(a.he,b,a.ke),Kd.push(a),Sd||(Sa.push(Jd),Sd=!0);else for(var c=0;c<Kd.length;++c)Kd[c].target==a.target&&Kd[c].he==a.he&&Ld(c--)}function Td(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function Ud(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Vd={},Sd,Qd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he={},ie=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function V(a){a=2<a?D(a):a;return ie[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function je(a){var b=W(),c=Ja(8),d=c+4,e=Ja(a.id.length+1);F(a.id,e,a.id.length+1);if(a=V(e))w[c>>2]=a.width,w[d>>2]=a.height;c=[w[c>>2],w[d>>2]];X(b);return c}function ke(a,b,c){a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function le(a,b,c){if(a.Wf){var d=W(),e=Ja(a.id.length+1);F(a.id,e,a.id.length+1);ke(e,b,c);X(d)}else a.width=b,a.height=c}
function me(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),le(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=p,a.style.paddingTop=t,a.style.paddingBottom=u,a.style.marginLeft=v,a.style.marginRight=
z,a.style.marginTop=C,a.style.marginBottom=H,document.body.style.margin=za,document.documentElement.style.overflow=qa,document.body.scroll=qc,a.style.jf=N,a.Ae&&a.Ae.te.viewport(0,0,d,e),he.Ge&&I.get(he.Ge)(37,0,he.Ze))}var c=je(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,p=a.style.paddingRight,t=a.style.paddingTop,u=a.style.paddingBottom,v=a.style.marginLeft,z=a.style.marginRight,C=a.style.marginTop,H=a.style.marginBottom,
za=document.body.style.margin,qa=document.documentElement.style.overflow,qc=document.body.scroll,N=a.style.jf;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function ne(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function oe(a){return 0>ie.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function pe(a,b){if(0!=b.Ue||0!=b.Me){me(a);var c=b.Rf?innerWidth:screen.width,d=b.Rf?innerHeight:screen.height,e=oe(a),f=e.width;e=e.height;var g=je(a),m=g[0];g=g[1];3==b.Ue?(ne(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Ue&&(c*g<m*d?(f=g*c/m,ne(a,(d-f)/2,0),d=f):(f=m*d/g,ne(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Df&&(a.style.jf="pixelated");
f=2==b.Me?devicePixelRatio:1;0!=b.Me&&(c=c*f|0,d=d*f|0,le(a,c,d),a.Ae&&a.Ae.te.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Ud()?-3:-1;he=b;b.Ge&&I.get(b.Ge)(37,0,b.Ze);return 0}function qe(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.Ke)a.Ke();else return document.body.requestPointerLock||document.body.Ke?-3:-1;return 0}
function re(a,b){B[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)B[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)B[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)w[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];w[a+1296>>2]=b.connected;w[a+1300>>2]=b.index;w[a+8>>2]=b.axes.length;w[a+12>>2]=b.buttons.length;F(b.id,a+1304,64);F(b.mapping,a+1368,64)}
function se(a,b,c){(a|0)===a&&(a=D(a));a=rb(a);if(a=h.preloadedImages[a]){var d=a.getContext("2d").getImageData(0,0,a.width,a.height),e=G(a.width*a.height*4);E.set(d.data,e);w[b>>2]=a.width;w[c>>2]=a.height;return e}return 0}var te=[];function ue(a,b,c,d){for(var e=0;e<a;e++){var f=O[c](),g=f&&Fd(d);f?(f.name=g,d[g]=f):U(1282);w[b+4*e>>2]=g}}function ve(a,b,c,d,e,f,g,m){b=R[b];if(a=O[a](b,c))d=m&&F(a.name,m,d),e&&(w[e>>2]=d),f&&(w[f>>2]=a.size),g&&(w[g>>2]=a.type)}
function we(a,b){Ma[a>>2]=b;Ma[a+4>>2]=(b-Ma[a>>2])/4294967296}
function xe(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&U(1280);return;case 36345:d=0;break;case 34466:var e=O.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=O.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:U(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:q[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){U(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:U(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:we(b,
d);break;case 0:w[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:q[b>>0]=d?1:0}}else U(1281)}function ye(a){var b=Ga(a)+1,c=G(b);F(a,c,b);return c}function ze(a,b,c,d){if(c)if(a=O.getUniform(R[a],S[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:A[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b]}else U(1281)}
function Ae(a,b,c,d){if(c)if(a=O.getVertexAttrib(a,b),34975==b)w[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:w[c+4*b>>2]=Math.fround(a[b])}else U(1281)}
function Be(a,b,c,d,e){a-=5120;a=1==a?E:4==a?w:6==a?A:5==a||28922==a?Ma:La;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Dd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var Ce=[],De=[];function Ee(a,b){if(!Ud())return-1;a=V(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Id&&Qd.ue?pe(a,b):b.Af?(Nd(pe,1,[a,b]),1):-2:-3:-4}
function Fe(a,b){var c={target:V(2),he:"beforeunload",le:b,oe:function(d){d=d||event;var e=I.get(b)(28,0,a);e&&(e=D(e));if(e)return d.preventDefault(),d.returnValue=e},ke:!0};Rd(c)}function Ge(a,b,c,d,e,f){Xd||(Xd=G(256));a={target:V(a),he:f,le:d,oe:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Xd;F(Td(g.target),n+0,128);F(m,n+128,128);I.get(d)(e,n,b)&&g.preventDefault()},ke:c};Rd(a)}
function He(a,b,c,d,e){Zd||(Zd=G(280));Rd({target:a,he:e,le:d,oe:function(f){f=f||event;var g=Zd,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;w[g>>2]=n;w[g+4>>2]=Ud();var r=n?m:Yd,p=r&&r.id?r.id:"";F(Td(r),g+8,128);F(p,g+136,128);w[g+264>>2]=r?r.clientWidth:0;w[g+268>>2]=r?r.clientHeight:0;w[g+272>>2]=screen.width;w[g+276>>2]=screen.height;n&&(Yd=m);I.get(d)(19,g,b)&&f.preventDefault()},ke:c})}
function Ie(a,b,c,d,e){$d||($d=G(1432));b={target:V(2),ue:!0,he:e,le:c,oe:function(f){f=f||event;var g=$d;re(g,f.gamepad);I.get(c)(d,g,a)&&f.preventDefault()},ke:b};Rd(b)}
function Je(a,b,c,d,e,f){ae||(ae=G(164));a={target:V(a),ue:!0,he:f,le:d,oe:function(g){var m=ae,n=m>>2;w[n]=g.location;w[n+1]=g.ctrlKey;w[n+2]=g.shiftKey;w[n+3]=g.altKey;w[n+4]=g.metaKey;w[n+5]=g.repeat;w[n+6]=g.charCode;w[n+7]=g.keyCode;w[n+8]=g.which;F(g.key||"",m+36,32);F(g.code||"",m+68,32);F(g.char||"",m+100,32);F(g.locale||"",m+132,32);I.get(d)(e,m,b)&&g.preventDefault()},ke:c};Rd(a)}
function Ke(a,b,c){a>>=2;w[a]=b.screenX;w[a+1]=b.screenY;w[a+2]=b.clientX;w[a+3]=b.clientY;w[a+4]=b.ctrlKey;w[a+5]=b.shiftKey;w[a+6]=b.altKey;w[a+7]=b.metaKey;Aa[2*a+16]=b.button;Aa[2*a+17]=b.buttons;w[a+9]=b.movementX;w[a+10]=b.movementY;c=oe(c);w[a+11]=b.clientX-c.left;w[a+12]=b.clientY-c.top}function Le(a,b,c,d,e,f){be||(be=G(64));a=V(a);Rd({target:a,ue:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,he:f,le:d,oe:function(g){g=g||event;Ke(be,g,a);I.get(d)(e,be,b)&&g.preventDefault()},ke:c})}
function Me(a,b,c,d,e){ce||(ce=G(260));Rd({target:a,he:e,le:d,oe:function(f){f=f||event;var g=ce,m=document.pointerLockElement||document.Be||document.cf||document.bf;w[g>>2]=!!m;var n=m&&m.id?m.id:"";F(Td(m),g+4,128);F(n,g+132,128);I.get(d)(20,g,b)&&f.preventDefault()},ke:c})}
function Ne(a,b,c,d){de||(de=G(36));a=V(a);Rd({target:a,he:"resize",le:d,oe:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=de;w[g>>2]=e.detail;w[g+4>>2]=f.clientWidth;w[g+8>>2]=f.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset;w[g+32>>2]=pageYOffset;I.get(d)(10,g,b)&&e.preventDefault()}}},ke:c})}
function Oe(a,b,c,d,e,f){ee||(ee=G(1684));a=V(a);Rd({target:a,ue:"touchstart"==f||"touchend"==f,he:f,le:d,oe:function(g){for(var m={},n=g.touches,r=0;r<n.length;++r){var p=n[r];m[p.identifier]=p}n=g.changedTouches;for(r=0;r<n.length;++r)p=n[r],p.Jf=1,m[p.identifier]=p;n=g.targetTouches;for(r=0;r<n.length;++r)m[n[r].identifier].Nf=1;n=ee;p=n>>2;w[p+1]=g.ctrlKey;w[p+2]=g.shiftKey;w[p+3]=g.altKey;w[p+4]=g.metaKey;p+=5;var t=oe(a),u=0;for(r in m){var v=m[r];w[p]=v.identifier;w[p+1]=v.screenX;w[p+2]=v.screenY;
w[p+3]=v.clientX;w[p+4]=v.clientY;w[p+5]=v.pageX;w[p+6]=v.pageY;w[p+7]=v.Jf;w[p+8]=v.Nf;w[p+9]=v.clientX-t.left;w[p+10]=v.clientY-t.top;p+=13;if(31<++u)break}w[n>>2]=u;I.get(d)(e,n,b)&&g.preventDefault()},ke:c})}function Pe(a,b,c){var d=ie[1];fe||(fe=G(8));Rd({target:d,he:"visibilitychange",le:c,oe:function(e){e=e||event;var f=fe,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);w[f>>2]=document.hidden;w[f+4>>2]=g;I.get(c)(21,f,a)&&e.preventDefault()},ke:b})}
function Qe(a,b,c,d){ge||(ge=G(96));Rd({target:a,ue:!0,he:"wheel",le:d,oe:function(e){e=e||event;var f=ge;Ke(f,e,a);B[f+64>>3]=e.deltaX;B[f+72>>3]=e.deltaY;B[f+80>>3]=e.deltaZ;w[f+88>>2]=e.deltaMode;I.get(d)(9,f,b)&&e.preventDefault()},ke:c})}var Re={};
function Se(){if(!Te){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Re)a[b]=Re[b];var c=[];for(b in a)c.push(b+"="+a[b]);Te=c}return Te}var Te,Ue=[];function Ob(a,b,c,d){a||(a=this);this.parent=a;this.se=a.se;this.xe=null;this.id=Fb++;this.name=b;this.mode=c;this.ce={};this.de={};this.rdev=d}
Object.defineProperties(Ob.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Lf:{get:function(){return L(this.mode)}},Kf:{get:function(){return 8192===(this.mode&61440)}}});ic();Gb=Array(4096);Wb(K,"/");Yb("/tmp");Yb("/home");Yb("/home/web_user");
(function(){Yb("/dev");ub(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Zb("/dev/null",259);tb(1280,wb);tb(1536,xb);Zb("/dev/tty",1280);Zb("/dev/tty1",1536);var a=qb();oc("/dev","random",a);oc("/dev","urandom",a);Yb("/dev/shm");Yb("/dev/shm/tmp")})();Yb("/proc");Yb("/proc/self");Yb("/proc/self/fd");
Wb({se:function(){var a=zb("/proc/self","fd",16895,73);a.ce={lookup:function(b,c){var d=Eb[+c];if(!d)throw new J(8);b={parent:null,se:{nf:"fake"},ce:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");h.FS_createPath=lc;h.FS_createDataFile=nc;h.FS_createPreloadedFile=sc;h.FS_createLazyFile=rc;h.FS_createDevice=oc;h.FS_unlink=ac;h.requestFullscreen=function(a,b){fd(a,b)};h.requestAnimationFrame=function(a){Hc(a)};
h.setCanvasSize=function(a,b,c){hd(h.canvas,a,b);c||id()};h.pauseMainLoop=function(){Ec=null;Kc++};h.resumeMainLoop=function(){Kc++;var a=Bc,b=Cc,c=Dc;Dc=null;Ic(c,0,!1,Jc,!0);Ac(a,b);Ec()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return Yc(a,b,c,d)};for(var O,Y=0;32>Y;++Y)te.push(Array(Y));var Ve=new Float32Array(288);
for(Y=0;288>Y;++Y)Ce[Y]=Ve.subarray(0,Y+1);var We=new Int32Array(288);for(Y=0;288>Y;++Y)De[Y]=We.subarray(0,Y+1);function fb(a,b){var c=Array(Ga(a)+1);a=Fa(a,c,0,c.length);b&&(c.length=a);return c}Qa.push({ff:function(){Xe()}});
var mf={_:function(a,b,c,d){l("Assertion failed: "+D(a)+", at: "+[b?D(b):"unknown filename",c,d?D(d):"unknown function"])},x:function(a,b,c){wc=c;try{var d=yc(a);switch(b){case 0:var e=xc();return 0>e?-28:cc(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=xc(),d.flags|=e,0;case 12:return e=xc(),Aa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return kb(28),-1;default:return-28}}catch(f){return"undefined"!==typeof vc&&f instanceof J||l(f),
-f.ne}},ma:function(a,b,c){wc=c;try{var d=yc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=xc();return w[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=xc();if(!d.de.If)throw new J(59);return d.de.If(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:l("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof vc&&f instanceof J||l(f),
-f.ne}},na:function(a,b,c){wc=c;try{var d=D(a),e=xc();return cc(d,b,e).fd}catch(f){return"undefined"!==typeof vc&&f instanceof J||l(f),-f.ne}},oa:function(a){try{a=D(a);var b=Ib(a,{parent:!0}).node,c=pb(a),d=Bb(b,c),e=Sb(b,c,!0);if(e)throw new J(e);if(!b.ce.rmdir)throw new J(63);if(d.xe)throw new J(10);try{M.willDeletePath&&M.willDeletePath(a)}catch(f){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.ce.rmdir(b,c);Mb(d);try{if(M.onDeletePath)M.onDeletePath(a)}catch(f){k("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+f.message)}return 0}catch(f){return"undefined"!==typeof vc&&f instanceof J||l(f),-f.ne}},qa:function(a,b){try{a=D(a);a:{try{var c=Ib(a,{He:!0}).node;if(!c)throw new J(44);if(!c.ce.qe)throw new J(63);var d=c.ce.qe(c)}catch(f){if(f&&f.node&&nb(a)!==nb(Kb(f.node))){var e=-54;break a}throw f;}w[b>>2]=d.dev;w[b+4>>2]=0;w[b+8>>2]=d.ino;w[b+12>>2]=d.mode;w[b+16>>2]=d.nlink;w[b+20>>2]=d.uid;w[b+24>>2]=d.gid;w[b+28>>2]=d.rdev;w[b+32>>2]=0;x=[d.size>>>0,(y=d.size,1<=+Math.abs(y)?
0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[b+40>>2]=x[0];w[b+44>>2]=x[1];w[b+48>>2]=4096;w[b+52>>2]=d.blocks;w[b+56>>2]=d.atime.getTime()/1E3|0;w[b+60>>2]=0;w[b+64>>2]=d.mtime.getTime()/1E3|0;w[b+68>>2]=0;w[b+72>>2]=d.ctime.getTime()/1E3|0;w[b+76>>2]=0;x=[d.ino>>>0,(y=d.ino,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[b+80>>2]=x[0];w[b+84>>2]=x[1];e=0}return e}catch(f){return"undefined"!==
typeof vc&&f instanceof J||l(f),-f.ne}},pa:function(a){try{return a=D(a),ac(a),0}catch(b){return"undefined"!==typeof vc&&b instanceof J||l(b),-b.ne}},ra:function(){l()},o:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=zc();else return kb(28),-1;w[b>>2]=a/1E3|0;w[b+4>>2]=a%1E3*1E6|0;return 0},ua:function(){l("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},La:function(a){if(12448==a)return P=12288,1;P=12300;
return 0},xb:function(a,b,c,d,e){if(62E3!=a)P=12296,c=0;else{if(b)for(;;){a=w[b>>2];if(12321==a)Q.alpha=0<w[b+4>>2];else if(12325==a)Q.depth=0<w[b+4>>2];else if(12326==a)Q.stencil=0<w[b+4>>2];else if(12337==a)a=w[b+4>>2],Q.antialias=0<a;else if(12338==a)a=w[b+4>>2],Q.antialias=1==a;else if(12544==a)Q.dg=12547!=w[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(w[e>>2]=1),c&&0<d&&(w[c>>2]=62002),P=12288,c=1):(P=12300,c=0)}return c},Ba:function(a,b,c,d){if(62E3!=a)return P=12296,0;for(a=1;;){b=w[d>>
2];if(12440==b)a=w[d+4>>2];else if(12344==b)break;else return P=12292,0;d+=8}if(2!=a)return P=12293,0;Q.lf=a-1;Q.eg=0;qd=$c(h.canvas,Q);if(0!=qd)return P=12288,bd(qd),h.Tf=!0,Rc.forEach(function(e){e()}),bd(null),62004;P=12297;return 0},Da:function(a,b){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;P=12288;return 62006},Ca:function(a,b){if(62E3!=a)return P=12296,0;if(62004!=b)return P=12294,0;a=qd;Hd===ad[a]&&(Hd=null);if("object"===typeof Vd)for(var c=ad[a].te.canvas,d=0;d<Kd.length;++d)Kd[d].target!=
c||Ld(d--);ad[a]&&ad[a].te.canvas&&(ad[a].te.canvas.Ae=void 0);ad[a]=null;P=12288;md==b&&(md=0);return 1},Ea:function(a,b){if(62E3!=a)return P=12296,0;if(62006!=b)return P=12301,1;nd==b&&(nd=0);od==b&&(od=0);P=12288;return 1},Ib:function(a,b,c,d){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;if(!d)return P=12300,0;P=12288;switch(c){case 12320:return w[d>>2]=Q.alpha?32:24,1;case 12321:return w[d>>2]=Q.alpha?8:0,1;case 12322:return w[d>>2]=8,1;case 12323:return w[d>>2]=8,1;case 12324:return w[d>>
2]=8,1;case 12325:return w[d>>2]=Q.depth?24:0,1;case 12326:return w[d>>2]=Q.stencil?8:0,1;case 12327:return w[d>>2]=12344,1;case 12328:return w[d>>2]=62002,1;case 12329:return w[d>>2]=0,1;case 12330:return w[d>>2]=4096,1;case 12331:return w[d>>2]=16777216,1;case 12332:return w[d>>2]=4096,1;case 12333:return w[d>>2]=0,1;case 12334:return w[d>>2]=0,1;case 12335:return w[d>>2]=12344,1;case 12337:return w[d>>2]=Q.antialias?4:0,1;case 12338:return w[d>>2]=Q.antialias?1:0,1;case 12339:return w[d>>2]=4,
1;case 12340:return w[d>>2]=12344,1;case 12341:case 12342:case 12343:return w[d>>2]=-1,1;case 12345:case 12346:return w[d>>2]=0,1;case 12347:return w[d>>2]=0,1;case 12348:return w[d>>2]=1;case 12349:case 12350:return w[d>>2]=0,1;case 12351:return w[d>>2]=12430,1;case 12352:return w[d>>2]=4,1;case 12354:return w[d>>2]=0,1;default:return P=12292,0}},X:function(){P=12288;return 62E3},Aa:function(){return P},Ma:function(a){return Ye(a)},bb:function(a,b,c){if(62E3==a)return b&&(w[b>>2]=1),c&&(w[c>>2]=
4),ld=!0,P=12288,1;P=12296;return 0},Fa:function(a,b,c,d){if(62E3!=a)return P=12296,0;if(0!=d&&62004!=d)return P=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return P=12301,0;bd(d?qd:null);md=d;od=b;nd=c;P=12288;return 1},za:function(a,b){if(62E3!=a)return P=12296,0;P=12288;if(pd[b])return pd[b];switch(b){case 12371:a=Ha("Emscripten");break;case 12372:a=Ha("1.4 Emscripten EGL");break;case 12373:a=Ha("");break;case 12429:a=Ha("OpenGL_ES");break;default:return P=12300,0}return pd[b]=a},Ga:function(){if(ld)if(h.pe)if(h.pe.isContextLost())P=
12302;else return P=12288,1;else P=12290;else P=12289;return 0},Ha:function(a,b){if(62E3!=a)return P=12296,0;0==b?Ac(0,0):Ac(1,b);P=12288;return 1},mb:function(a){if(62E3!=a)return P=12296,0;od=nd=md=0;ld=!1;P=12288;return 1},Ka:function(){P=12288;return 1},Ja:function(){P=12288;return 1},d:function(a,b,c){Ue.length=0;var d;for(c>>=2;d=E[b++];)(d=105>d)&&c&1&&c++,Ue.push(d?B[c++>>1]:w[c]),++c;return hb[a].apply(null,Ue)},va:function(){if(!Ud())return-1;Od(pe);var a=ie[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},xa:function(){Od(qe);if(document.exitPointerLock)document.exitPointerLock();else if(document.ge)document.ge();else return-1;return 0},j:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},g:function(a,b,c){a=V(a);if(!a)return-4;a=oe(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},A:function(a,b){if(0>a||a>=Wd.length)return-5;if(!Wd[a])return-7;re(b,Wd[a]);
return 0},ta:function(){return Wd.length},Ia:se,ya:function(a,b,c){a=h._fileno(a);return(a=Eb[a])?se(a.path,b,c):0},Dd:function(a){O.activeTexture(a)},Cd:function(a,b){O.attachShader(R[a],T[b])},da:function(a,b){O.me.beginQueryEXT(a,Ad[b])},Bd:function(a,b,c){O.bindAttribLocation(R[a],b,D(c))},Ad:function(a,b){O.bindBuffer(a,vd[b])},zd:function(a,b){O.bindFramebuffer(a,wd[b])},yd:function(a,b){O.bindRenderbuffer(a,xd[b])},xd:function(a,b){O.bindTexture(a,yd[b])},Ld:function(a){O.bindVertexArray(zd[a])},
wd:function(a,b,c,d){O.blendColor(a,b,c,d)},vd:function(a){O.blendEquation(a)},ud:function(a,b){O.blendEquationSeparate(a,b)},td:function(a,b){O.blendFunc(a,b)},sd:function(a,b,c,d){O.blendFuncSeparate(a,b,c,d)},rd:function(a,b,c,d){O.bufferData(a,c?E.subarray(c,c+b):b,d)},qd:function(a,b,c,d){O.bufferSubData(a,b,E.subarray(d,d+c))},pd:function(a){return O.checkFramebufferStatus(a)},od:function(a){O.clear(a)},nd:function(a,b,c,d){O.clearColor(a,b,c,d)},md:function(a){O.clearDepth(a)},ld:function(a){O.clearStencil(a)},
kd:function(a,b,c,d){O.colorMask(!!a,!!b,!!c,!!d)},jd:function(a){O.compileShader(T[a])},id:function(a,b,c,d,e,f,g,m){O.compressedTexImage2D(a,b,c,d,e,f,m?E.subarray(m,m+g):null)},hd:function(a,b,c,d,e,f,g,m,n){O.compressedTexSubImage2D(a,b,c,d,e,f,g,n?E.subarray(n,n+m):null)},gd:function(a,b,c,d,e,f,g,m){O.copyTexImage2D(a,b,c,d,e,f,g,m)},fd:function(a,b,c,d,e,f,g,m){O.copyTexSubImage2D(a,b,c,d,e,f,g,m)},ed:function(){var a=Fd(R),b=O.createProgram();b.name=a;R[a]=b;return a},dd:function(a){var b=
Fd(T);T[b]=O.createShader(a);return b},cd:function(a){O.cullFace(a)},bd:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=vd[d];e&&(O.deleteBuffer(e),e.name=0,vd[d]=null)}},ad:function(a,b){for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=wd[d];e&&(O.deleteFramebuffer(e),e.name=0,wd[d]=null)}},$c:function(a){if(a){var b=R[a];b?(O.deleteProgram(b),b.name=0,R[a]=null,Bd[a]=null):U(1281)}},fa:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Ad[d];e&&(O.me.deleteQueryEXT(e),Ad[d]=null)}},_c:function(a,
b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=xd[d];e&&(O.deleteRenderbuffer(e),e.name=0,xd[d]=null)}},Zc:function(a){if(a){var b=T[a];b?(O.deleteShader(b),T[a]=null):U(1281)}},Yc:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=yd[d];e&&(O.deleteTexture(e),e.name=0,yd[d]=null)}},Kd:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];O.deleteVertexArray(zd[d]);zd[d]=null}},Xc:function(a){O.depthFunc(a)},Wc:function(a){O.depthMask(!!a)},Vc:function(a,b){O.depthRange(a,b)},Uc:function(a,b){O.detachShader(R[a],
T[b])},Tc:function(a){O.disable(a)},Sc:function(a){O.disableVertexAttribArray(a)},Rc:function(a,b,c){O.drawArrays(a,b,c)},Gd:function(a,b,c,d){O.drawArraysInstanced(a,b,c,d)},Hd:function(a,b){for(var c=te[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];O.drawBuffers(c)},Qc:function(a,b,c,d){O.drawElements(a,b,c,d)},Fd:function(a,b,c,d,e){O.drawElementsInstanced(a,b,c,d,e)},Pc:function(a){O.enable(a)},Oc:function(a){O.enableVertexAttribArray(a)},ca:function(a){O.me.endQueryEXT(a)},Nc:function(){O.finish()},Mc:function(){O.flush()},
Lc:function(a,b,c,d){O.framebufferRenderbuffer(a,b,c,xd[d])},Kc:function(a,b,c,d,e){O.framebufferTexture2D(a,b,c,yd[d],e)},Jc:function(a){O.frontFace(a)},Hc:function(a,b){ue(a,b,"createBuffer",vd)},Fc:function(a,b){ue(a,b,"createFramebuffer",wd)},ga:function(a,b){for(var c=0;c<a;c++){var d=O.me.createQueryEXT();if(!d){for(U(1282);c<a;)w[b+4*c++>>2]=0;break}var e=Fd(Ad);d.name=e;Ad[e]=d;w[b+4*c>>2]=e}},Ec:function(a,b){ue(a,b,"createRenderbuffer",xd)},Dc:function(a,b){ue(a,b,"createTexture",yd)},Jd:function(a,
b){ue(a,b,"createVertexArray",zd)},Gc:function(a){O.generateMipmap(a)},Cc:function(a,b,c,d,e,f,g){ve("getActiveAttrib",a,b,c,d,e,f,g)},Bc:function(a,b,c,d,e,f,g){ve("getActiveUniform",a,b,c,d,e,f,g)},Ac:function(a,b,c,d){a=O.getAttachedShaders(R[a]);var e=a.length;e>b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+4*b>>2]=T.indexOf(a[b])},zc:function(a,b){return O.getAttribLocation(R[a],D(b))},yc:function(a,b){xe(a,b,4)},wc:function(a,b,c){c?w[c>>2]=O.getBufferParameter(a,b):U(1281)},vc:function(){var a=O.getError()||
Ed;Ed=0;return a},uc:function(a,b){xe(a,b,2)},tc:function(a,b,c,d){a=O.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},sc:function(a,b){xe(a,b,0)},qc:function(a,b,c,d){a=O.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,d,b):0;c&&(w[c>>2]=b)},rc:function(a,b,c){if(c)if(a>=ud)U(1281);else{var d=Bd[a];if(d)if(35716==b)a=O.getProgramInfoLog(R[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==
b)w[c>>2]=d.Re;else if(35722==b){if(-1==d.Ce){a=R[a];var e=O.getProgramParameter(a,35721);for(b=d.Ce=0;b<e;++b)d.Ce=Math.max(d.Ce,O.getActiveAttrib(a,b).name.length+1)}w[c>>2]=d.Ce}else if(35381==b){if(-1==d.De)for(a=R[a],e=O.getProgramParameter(a,35382),b=d.De=0;b<e;++b)d.De=Math.max(d.De,O.getActiveUniformBlockName(a,b).length+1);w[c>>2]=d.De}else w[c>>2]=O.getProgramParameter(R[a],b);else U(1282)}else U(1281)},Nd:function(a,b,c){if(c){a=O.me.getQueryObjectEXT(Ad[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;we(c,d)}else U(1281)},$:function(a,b,c){if(c){a=O.me.getQueryObjectEXT(Ad[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else U(1281)},Md:function(a,b,c){if(c){a=O.me.getQueryObjectEXT(Ad[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;we(c,d)}else U(1281)},Od:function(a,b,c){if(c){a=O.me.getQueryObjectEXT(Ad[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else U(1281)},aa:function(a,b,c){c?w[c>>2]=O.me.getQueryEXT(a,b):U(1281)},pc:function(a,b,c){c?w[c>>2]=O.getRenderbufferParameter(a,
b):U(1281)},nc:function(a,b,c,d){a=O.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,d,b):0;c&&(w[c>>2]=b)},mc:function(a,b,c,d){a=O.getShaderPrecisionFormat(a,b);w[c>>2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},lc:function(a,b,c,d){if(a=O.getShaderSource(T[a]))b=0<b&&d?F(a,d,b):0,c&&(w[c>>2]=b)},oc:function(a,b,c){c?35716==b?(a=O.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(T[a]),w[c>>2]=a?a.length+1:
0):w[c>>2]=O.getShaderParameter(T[a],b):U(1281)},kc:function(a){if(Cd[a])return Cd[a];switch(a){case 7939:var b=O.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ye(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=O.getParameter(a))||U(1280);b=ye(b);break;case 7938:b=ye("OpenGL ES 2.0 ("+O.getParameter(7938)+")");break;case 35724:b=O.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),
b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ye(b);break;default:return U(1280),0}return Cd[a]=b},jc:function(a,b,c){c?A[c>>2]=O.getTexParameter(a,b):U(1281)},ic:function(a,b,c){c?w[c>>2]=O.getTexParameter(a,b):U(1281)},fc:function(a,b){b=D(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Bd[a]&&Bd[a].tf[b])&&0<=c&&c<a[0]?a[1]+c:-1},hc:function(a,b,c){ze(a,b,c,2)},gc:function(a,b,c){ze(a,b,c,0)},cc:function(a,b,c){c?w[c>>2]=O.getVertexAttribOffset(a,
b):U(1281)},ec:function(a,b,c){Ae(a,b,c,2)},dc:function(a,b,c){Ae(a,b,c,5)},bc:function(a,b){O.hint(a,b)},ac:function(a){return(a=vd[a])?O.isBuffer(a):0},$b:function(a){return O.isEnabled(a)},_b:function(a){return(a=wd[a])?O.isFramebuffer(a):0},Zb:function(a){return(a=R[a])?O.isProgram(a):0},ea:function(a){return(a=Ad[a])?O.me.isQueryEXT(a):0},Yb:function(a){return(a=xd[a])?O.isRenderbuffer(a):0},Xb:function(a){return(a=T[a])?O.isShader(a):0},Wb:function(a){return(a=yd[a])?O.isTexture(a):0},Id:function(a){return(a=
zd[a])?O.isVertexArray(a):0},Vb:function(a){O.lineWidth(a)},Sb:function(a){O.linkProgram(R[a]);var b=R[a];a=Bd[a]={tf:{},Re:0,Ce:-1,De:-1};for(var c=a.tf,d=O.getProgramParameter(b,35718),e=0;e<d;++e){var f=O.getActiveUniform(b,e),g=f.name;a.Re=Math.max(a.Re,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var m=O.getUniformLocation(b,g);if(m){var n=Fd(S);c[g]=[f.size,n];S[n]=m;for(var r=1;r<f.size;++r)m=O.getUniformLocation(b,g+"["+r+"]"),n=Fd(S),S[n]=m}}},Rb:function(a,b){3317==a&&
(Dd=b);O.pixelStorei(a,b)},Qb:function(a,b){O.polygonOffset(a,b)},ba:function(a,b){O.me.queryCounterEXT(Ad[a],b)},Pb:function(a,b,c,d,e,f,g){(g=Be(f,e,c,d,g))?O.readPixels(a,b,c,d,e,f,g):U(1280)},Ob:function(){},Nb:function(a,b,c,d){O.renderbufferStorage(a,b,c,d)},Mb:function(a,b){O.sampleCoverage(a,!!b)},Lb:function(a,b,c,d){O.scissor(a,b,c,d)},Kb:function(){U(1280)},Jb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?w[d+4*f>>2]:-1;e+=D(w[c+4*f>>2],0>g?void 0:g)}O.shaderSource(T[a],e)},Hb:function(a,
b,c){O.stencilFunc(a,b,c)},Gb:function(a,b,c,d){O.stencilFuncSeparate(a,b,c,d)},Fb:function(a){O.stencilMask(a)},Eb:function(a,b){O.stencilMaskSeparate(a,b)},Db:function(a,b,c){O.stencilOp(a,b,c)},Cb:function(a,b,c,d){O.stencilOpSeparate(a,b,c,d)},Bb:function(a,b,c,d,e,f,g,m,n){O.texImage2D(a,b,c,d,e,f,g,m,n?Be(m,g,d,e,n):null)},Ab:function(a,b,c){O.texParameterf(a,b,c)},zb:function(a,b,c){O.texParameterf(a,b,A[c>>2])},yb:function(a,b,c){O.texParameteri(a,b,c)},wb:function(a,b,c){O.texParameteri(a,
b,w[c>>2])},vb:function(a,b,c,d,e,f,g,m,n){var r=null;n&&(r=Be(m,g,e,f,n));O.texSubImage2D(a,b,c,d,e,f,g,m,r)},ub:function(a,b){O.uniform1f(S[a],b)},tb:function(a,b,c){if(288>=b)for(var d=Ce[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);O.uniform1fv(S[a],d)},sb:function(a,b){O.uniform1i(S[a],b)},rb:function(a,b,c){if(288>=b)for(var d=De[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);O.uniform1iv(S[a],d)},qb:function(a,b,c){O.uniform2f(S[a],b,c)},pb:function(a,
b,c){if(144>=b)for(var d=Ce[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);O.uniform2fv(S[a],d)},ob:function(a,b,c){O.uniform2i(S[a],b,c)},nb:function(a,b,c){if(144>=b)for(var d=De[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);O.uniform2iv(S[a],d)},lb:function(a,b,c,d){O.uniform3f(S[a],b,c,d)},kb:function(a,b,c){if(96>=b)for(var d=Ce[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=
A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);O.uniform3fv(S[a],d)},jb:function(a,b,c,d){O.uniform3i(S[a],b,c,d)},ib:function(a,b,c){if(96>=b)for(var d=De[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);O.uniform3iv(S[a],d)},hb:function(a,b,c,d,e){O.uniform4f(S[a],b,c,d,e)},gb:function(a,b,c){if(72>=b){var d=Ce[4*b-1],e=A;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=A.subarray(c>>
2,c+16*b>>2);O.uniform4fv(S[a],d)},fb:function(a,b,c,d,e){O.uniform4i(S[a],b,c,d,e)},eb:function(a,b,c){if(72>=b)for(var d=De[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);O.uniform4iv(S[a],d)},db:function(a,b,c,d){if(72>=b)for(var e=Ce[4*b-1],f=0;f<4*b;f+=4)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);O.uniformMatrix2fv(S[a],
!!c,e)},cb:function(a,b,c,d){if(32>=b)for(var e=Ce[9*b-1],f=0;f<9*b;f+=9)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2],e[f+4]=A[d+(4*f+16)>>2],e[f+5]=A[d+(4*f+20)>>2],e[f+6]=A[d+(4*f+24)>>2],e[f+7]=A[d+(4*f+28)>>2],e[f+8]=A[d+(4*f+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);O.uniformMatrix3fv(S[a],!!c,e)},ab:function(a,b,c,d){if(18>=b){var e=Ce[16*b-1],f=A;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+
4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(S[a],!!c,e)},$a:function(a){O.useProgram(R[a])},_a:function(a){O.validateProgram(R[a])},Za:function(a,b){O.vertexAttrib1f(a,b)},Ya:function(a,b){O.vertexAttrib1f(a,A[b>>2])},Xa:function(a,b,c){O.vertexAttrib2f(a,b,c)},Wa:function(a,b){O.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},Va:function(a,
b,c,d){O.vertexAttrib3f(a,b,c,d)},Ua:function(a,b){O.vertexAttrib3f(a,A[b>>2],A[b+4>>2],A[b+8>>2])},Ta:function(a,b,c,d,e){O.vertexAttrib4f(a,b,c,d,e)},Sa:function(a,b){O.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+8>>2],A[b+12>>2])},Ed:function(a,b){O.vertexAttribDivisor(a,b)},Ra:function(a,b,c,d,e,f){O.vertexAttribPointer(a,b,c,!!d,e,f)},Qa:function(a,b,c,d){O.viewport(a,b,c,d)},r:function(){return 0},e:function(a,b){Z(a,b||1);throw"longjmp";},ha:function(a,b,c){E.copyWithin(a,b,b+c)},wa:function(a,
b,c){return Ee(a,{Ue:w[c>>2],Me:w[c+4>>2],Df:w[c+8>>2],Af:b,Ge:w[c+12>>2],Ze:w[c+16>>2]})},W:function(a,b){a=V(a);return a?a.requestPointerLock||a.Ke?Id&&Qd.ue?qe(a):b?(Nd(qe,2,[a]),1):-2:-1:-4},ia:function(a){a>>>=0;var b=E.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{Ba.grow(Math.min(2147483648,d)-Ka.byteLength+65535>>>16);Na(Ba.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
B:function(){return(Wd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},C:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;Fe(a,b);return 0},O:function(a,b,c,d){Ge(a,b,c,d,12,"blur");return 0},i:ke,p:function(a,b,c){a=V(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},P:function(a,b,c,d){Ge(a,b,c,d,13,"focus");return 0},F:function(a,b,c,d){if(!Ud())return-1;a=V(a);if(!a)return-4;
He(a,b,c,d,"fullscreenchange");He(a,b,c,d,"webkitfullscreenchange");return 0},z:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Ie(a,b,c,26,"gamepadconnected");return 0},y:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Ie(a,b,c,27,"gamepaddisconnected");return 0},I:function(a,b,c,d){Je(a,b,c,d,2,"keydown");return 0},G:function(a,b,c,d){Je(a,b,c,d,1,"keypress");return 0},H:function(a,b,c,d){Je(a,b,c,d,3,"keyup");return 0},Ub:function(a,
b,c,d,e){Ic(function(){I.get(a)()},b,c,d,e)},U:function(a,b,c,d){Le(a,b,c,d,5,"mousedown");return 0},S:function(a,b,c,d){Le(a,b,c,d,33,"mouseenter");return 0},R:function(a,b,c,d){Le(a,b,c,d,34,"mouseleave");return 0},V:function(a,b,c,d){Le(a,b,c,d,8,"mousemove");return 0},T:function(a,b,c,d){Le(a,b,c,d,6,"mouseup");return 0},J:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ge||document.body.Be||document.body.Ke))return-1;a=V(a);if(!a)return-4;Me(a,
b,c,d,"pointerlockchange");Me(a,b,c,d,"mozpointerlockchange");Me(a,b,c,d,"webkitpointerlockchange");Me(a,b,c,d,"mspointerlockchange");return 0},E:function(a,b,c,d){Ne(a,b,c,d);return 0},K:function(a,b,c,d){Oe(a,b,c,d,25,"touchcancel");return 0},M:function(a,b,c,d){Oe(a,b,c,d,23,"touchend");return 0},L:function(a,b,c,d){Oe(a,b,c,d,24,"touchmove");return 0},N:function(a,b,c,d){Oe(a,b,c,d,22,"touchstart");return 0},D:function(a,b,c){if(!ie[1])return-4;Pe(a,b,c);return 0},Q:function(a,b,c,d){a=V(a);return"undefined"!==
typeof a.onwheel?(Qe(a,b,c,d),0):-1},q:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},ja:function(a,b){var c=0;Se().forEach(function(d,e){var f=b+c;e=w[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++>>0]=d.charCodeAt(f);q[e>>0]=0;c+=d.length+1});return 0},ka:function(a,b){var c=Se();w[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});w[b>>2]=d;return 0},t:function(a){Ze(a)},w:function(a){try{var b=yc(a);ec(b);return 0}catch(c){return"undefined"!==
typeof vc&&c instanceof J||l(c),c.ne}},la:function(a,b,c,d){try{a:{for(var e=yc(a),f=a=0;f<c;f++){var g=w[b+(8*f+4)>>2],m=e,n=w[b+8*f>>2],r=g,p=void 0,t=q;if(0>r||0>p)throw new J(28);if(null===m.fd)throw new J(8);if(1===(m.flags&2097155))throw new J(8);if(L(m.node.mode))throw new J(31);if(!m.de.read)throw new J(28);var u="undefined"!==typeof p;if(!u)p=m.position;else if(!m.seekable)throw new J(70);var v=m.de.read(m,t,n,r,p);u||(m.position+=v);var z=v;if(0>z){var C=-1;break a}a+=z;if(z<g)break}C=a}w[d>>
2]=C;return 0}catch(H){return"undefined"!==typeof vc&&H instanceof J||l(H),H.ne}},Na:function(a,b,c,d,e){try{var f=yc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;fc(f,a,d);x=[f.position>>>0,(y=f.position,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[e>>2]=x[0];w[e+4>>2]=x[1];f.Pe&&0===a&&0===d&&(f.Pe=null);return 0}catch(g){return"undefined"!==typeof vc&&g instanceof J||l(g),g.ne}},
v:function(a,b,c,d){try{a:{for(var e=yc(a),f=a=0;f<c;f++){var g=hc(e,q,w[b+8*f>>2],w[b+(8*f+4)>>2],void 0);if(0>g){var m=-1;break a}a+=g}m=a}w[d>>2]=m;return 0}catch(n){return"undefined"!==typeof vc&&n instanceof J||l(n),n.ne}},b:function(){return wa|0},n:function(a){var b=Date.now();w[a>>2]=b/1E3|0;w[a+4>>2]=b%1E3*1E3|0;return 0},xc:$e,m:af,k:bf,s:cf,u:df,Ic:ef,Y:ff,Pa:gf,Oa:hf,h:jf,l:kf,Z:lf,a:Ba,sa:function(a,b){if(0===a)return kb(28),-1;var c=w[a>>2];a=w[a+4>>2];if(0>a||999999999<a||0>c)return kb(28),
-1;0!==b&&(w[b>>2]=0,w[b+4>>2]=0);b=1E6*c+a/1E3;for(c=zc();zc()-c<b/1E3;);},c:function(a){wa=a|0},f:function(){return 0},Tb:function(){return 0}};
(function(){function a(e){h.asm=e.exports;I=h.asm.Pd;Za("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return eb().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){k("failed to asynchronously prepare wasm: "+f);l(f)})}var d={a:mf};Ya("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return xa||"function"!==typeof WebAssembly.instantiateStreaming||
bb()||$a("file://")||"function"!==typeof fetch?c(b):fetch(ab,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Xe=h.___wasm_call_ctors=function(){return(Xe=h.___wasm_call_ctors=h.asm.Qd).apply(null,arguments)},G=h._malloc=function(){return(G=h._malloc=h.asm.Rd).apply(null,arguments)};
h._main=function(){return(h._main=h.asm.Sd).apply(null,arguments)};var lb=h.___errno_location=function(){return(lb=h.___errno_location=h.asm.Td).apply(null,arguments)},Ye=h._emscripten_GetProcAddress=function(){return(Ye=h._emscripten_GetProcAddress=h.asm.Ud).apply(null,arguments)};h._fileno=function(){return(h._fileno=h.asm.Vd).apply(null,arguments)};
var W=h.stackSave=function(){return(W=h.stackSave=h.asm.Wd).apply(null,arguments)},X=h.stackRestore=function(){return(X=h.stackRestore=h.asm.Xd).apply(null,arguments)},Ja=h.stackAlloc=function(){return(Ja=h.stackAlloc=h.asm.Yd).apply(null,arguments)},Z=h._setThrew=function(){return(Z=h._setThrew=h.asm.Zd).apply(null,arguments)};h.dynCall_iiji=function(){return(h.dynCall_iiji=h.asm._d).apply(null,arguments)};
var nf=h.dynCall_ji=function(){return(nf=h.dynCall_ji=h.asm.$d).apply(null,arguments)},of=h.dynCall_jiji=function(){return(of=h.dynCall_jiji=h.asm.ae).apply(null,arguments)};function af(a,b){var c=W();try{return I.get(a)(b)}catch(d){X(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function df(a,b,c,d,e){var f=W();try{return I.get(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}
function cf(a,b,c,d){var e=W();try{return I.get(a)(b,c,d)}catch(f){X(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function jf(a,b){var c=W();try{I.get(a)(b)}catch(d){X(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function lf(a,b,c,d){var e=W();try{I.get(a)(b,c,d)}catch(f){X(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function kf(a,b,c){var d=W();try{I.get(a)(b,c)}catch(e){X(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}
function bf(a,b,c){var d=W();try{return I.get(a)(b,c)}catch(e){X(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}function ff(a,b,c,d,e,f,g,m,n,r){var p=W();try{return I.get(a)(b,c,d,e,f,g,m,n,r)}catch(t){X(p);if(t!==t+0&&"longjmp"!==t)throw t;Z(1,0)}}function ef(a,b,c,d,e,f,g,m,n){var r=W();try{return I.get(a)(b,c,d,e,f,g,m,n)}catch(p){X(r);if(p!==p+0&&"longjmp"!==p)throw p;Z(1,0)}}function $e(a){var b=W();try{return I.get(a)()}catch(c){X(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}
function gf(a,b){var c=W();try{return nf(a,b)}catch(d){X(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function hf(a,b,c,d,e){var f=W();try{return of(a,b,c,d,e)}catch(g){X(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}h.addRunDependency=Ya;h.removeRunDependency=Za;h.FS_createPath=lc;h.FS_createDataFile=nc;h.FS_createPreloadedFile=sc;h.FS_createLazyFile=rc;h.FS_createDevice=oc;h.FS_unlink=ac;var pf;
function sa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Xa=function qf(){pf||rf();pf||(Xa=qf)};
function rf(a){function b(){if(!pf&&(pf=!0,h.calledRun=!0,!Ca)){h.noFSInit||jc||(jc=!0,ic(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?oc("/dev","stdin",h.stdin):$b("/dev/tty","/dev/stdin"),h.stdout?oc("/dev","stdout",null,h.stdout):$b("/dev/tty","/dev/stdout"),h.stderr?oc("/dev","stderr",null,h.stderr):$b("/dev/tty1","/dev/stderr"),cc("/dev/stdin","r"),cc("/dev/stdout","w"),cc("/dev/stderr","w"));jb(Qa);Hb=!1;jb(Ra);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(sf){var c=
a,d=h._main;c=c||[];var e=c.length+1,f=Ja(4*(e+1));w[f>>2]=Ia(da);for(var g=1;g<e;g++)w[(f>>2)+g]=Ia(c[g-1]);w[(f>>2)+e]=0;try{var m=d(e,f);Ze(m,!0)}catch(n){n instanceof sa||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),k("exception thrown: "+c),ea(1,n)))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Ta.unshift(c);jb(Ta)}}a=a||ca;if(!(0<Va)){if(h.preRun)for("function"==typeof h.preRun&&
(h.preRun=[h.preRun]);h.preRun.length;)Ua();jb(Pa);0<Va||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=rf;function Ze(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(h.onExit)h.onExit(a);Ca=!0}ea(a,new sa(a))}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var sf=!0;h.noInitialRun&&(sf=!1);noExitRuntime=!0;rf();
