var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.Oe||(h.Oe=0);h.Oe++;
h.ENVIRONMENT_IS_PTHREAD||h.$ww||function(a){function b(n,p,u,q){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(n,function(v,A){v?q(v):u(A.buffer)});else{var t=new XMLHttpRequest;t.open("GET",n,!0);t.responseType="arraybuffer";t.onprogress=function(v){var A=p;v.total&&(A=v.total);if(v.loaded){t.de?h.ve[n].loaded=v.loaded:(t.de=!0,h.ve||(h.ve={}),h.ve[n]={loaded:v.loaded,total:A});var C=A=v=0,D;for(D in h.ve){var S=h.ve[D];
v+=S.total;A+=S.loaded;C++}v=Math.ceil(v*h.Oe/C);h.setStatus&&h.setStatus("Downloading data... ("+A+"/"+v+")")}else!h.ve&&h.setStatus&&h.setStatus("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+n);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)u(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}}function c(n){console.error("package error:",n)}function d(){function n(t,v,A){this.start=t;this.end=
v;this.audio=A}function p(t){if(!t)throw"Loading data file failed."+Error().stack;if(t.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;t=new Uint8Array(t);n.prototype.Le=t;t=a.files;for(var v=0;v<t.length;++v)n.prototype.de[t[v].filename].onload();h.removeRunDependency("datafile_wasm/basque.data")}h.FS_createPath("/","assets",!0,!0);h.FS_createPath("/assets","audio",!0,!0);h.FS_createPath("/assets","data",!0,!0);h.FS_createPath("/assets","fonts",!0,!0);h.FS_createPath("/assets",
"icons",!0,!0);h.FS_createPath("/assets/icons","basque_logo.iconset",!0,!0);h.FS_createPath("/assets","images",!0,!0);n.prototype={de:{},open:function(t,v){this.name=v;this.de[v]=this;h.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Ae(this.Le.subarray(this.start,this.end))},Ae:function(t){h.FS_createDataFile(this.name,null,t,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.de[this.name]=null}};for(var u=a.files,q=0;q<u.length;++q)(new n(u[q].start,u[q].end,u[q].audio||
0)).open("GET",u[q].filename);h.addRunDependency("datafile_wasm/basque.data");h.qf||(h.qf={});h.qf["wasm/basque.data"]={$f:!1};m?(p(m),m=null):g=p}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof h.locateFilePackage||
h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=h.locateFile?h.locateFile("basque.data",""):"basque.data",f=a.remote_package_size,g=null,m=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;m||b(e,f,function(n){g?(g(n),g=null):m=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/assets/audio/Basque_sample_music.ogg",start:0,
end:4240906,audio:1},{filename:"/assets/data/map_attributes.txt",start:4240906,end:4243410},{filename:"/assets/data/map_layout.txt",start:4243410,end:4270941},{filename:"/assets/data/map_layout_0.txt",start:4270941,end:4298472},{filename:"/assets/data/map_layout_1.txt",start:4298472,end:4326003},{filename:"/assets/data/map_layout_2.txt",start:4326003,end:4353042},{filename:"/assets/data/map_layout_3.txt",start:4353042,end:4380085},{filename:"/assets/data/map_layout_4.txt",start:4380085,end:4407128},
{filename:"/assets/data/map_layout_5.txt",start:4407128,end:4434171},{filename:"/assets/data/map_layout_6.txt",start:4434171,end:4461214},{filename:"/assets/data/map_layout_7.txt",start:4461214,end:4488297},{filename:"/assets/data/map_layout_8.txt",start:4488297,end:4515424},{filename:"/assets/data/map_layout_9.txt",start:4515424,end:4542547},{filename:"/assets/data/map_library.txt",start:4542547,end:4542840},{filename:"/assets/fonts/BPtypewrite.ttf",start:4542840,end:4622012},{filename:"/assets/fonts/backpacker_license.pdf",
start:4622012,end:4928215},{filename:"/assets/icons/basque_logo.icns",start:4928215,end:5185942},{filename:"/assets/icons/basque_logo.ico",start:5185942,end:5288772},{filename:"/assets/icons/basque_logo.iconset/icon_1024x1024.png",start:5288772,end:5516561},{filename:"/assets/icons/basque_logo.iconset/icon_128x128.png",start:5516561,end:5536531},{filename:"/assets/icons/basque_logo.iconset/icon_128x128@2x.png",start:5536531,end:5588919},{filename:"/assets/icons/basque_logo.iconset/icon_16x16.png",
start:5588919,end:5591826},{filename:"/assets/icons/basque_logo.iconset/icon_16x16@2x.png",start:5591826,end:5596028},{filename:"/assets/icons/basque_logo.iconset/icon_256x256.png",start:5596028,end:5648416},{filename:"/assets/icons/basque_logo.iconset/icon_256x256@2x.png",start:5648416,end:5768787},{filename:"/assets/icons/basque_logo.iconset/icon_32x32.png",start:5768787,end:5772989},{filename:"/assets/icons/basque_logo.iconset/icon_32x32@2x.png",start:5772989,end:5781169},{filename:"/assets/icons/basque_logo.iconset/icon_512x512.png",
start:5781169,end:5901540},{filename:"/assets/icons/basque_logo.iconset/icon_512x512@2x.png",start:5901540,end:6129329},{filename:"/assets/icons/basque_logo.iconset/icon_64x64.png",start:6129329,end:6137509},{filename:"/assets/icons/basque_logo.iconset/icon_64x64@2x.png",start:6137509,end:6157479},{filename:"/assets/icons/basque_logo.iconset/icon_8x8@2x.png",start:6157479,end:6160386},{filename:"/assets/icons/basque_logo.png",start:6160386,end:6171029},{filename:"/assets/images/README.md",start:6171029,
end:6171215},{filename:"/assets/images/basque_logo.png",start:6171215,end:6172690},{filename:"/assets/images/basque_logo_scaled.png",start:6172690,end:6196554},{filename:"/assets/images/basque_logo_scaled_v2.png",start:6196554,end:6220329},{filename:"/assets/images/basque_logo_scaled_v3.png",start:6220329,end:6244453},{filename:"/assets/images/character.png",start:6244453,end:6248433},{filename:"/assets/images/tiles_packed.png",start:6248433,end:6255463}],remote_package_size:6255463});
var aa=Object.assign({},h),ba=[],ca="./this.program",ea=(a,b)=>{throw b;},fa="object"==typeof window,ha="function"==typeof importScripts,ia="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ja=!fa&&!ia&&!ha,ka="";function la(a){return h.locateFile?h.locateFile(a,ka):ka+a}var ma,na,oa,pa;
if(ia){var fs=require("fs"),qa=require("path");ka=ha?qa.dirname(ka)+"/":__dirname+"/";ma=(a,b)=>{a=a.startsWith("file://")?new URL(a):qa.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};oa=a=>{a=ma(a,!0);a.buffer||(a=new Uint8Array(a));return a};na=(a,b,c)=>{a=a.startsWith("file://")?new URL(a):qa.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=
h);process.on("uncaughtException",function(a){if(!(a instanceof sa))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",function(a){throw a;});ea=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;if(!(b instanceof sa)){var c=b;b&&"object"==typeof b&&b.stack&&(c=[b,b.stack]);k("exiting due to exception: "+c)}process.exit(a)};h.inspect=function(){return"[Emscripten Module object]"};"undefined"==typeof WebAssembly&&eval(fs.readFileSync(la("basque.wasm.js"))+"")}else if(fa||
ha)ha?ka=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ka=document.currentScript.src),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(oa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),na=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";
d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},pa=a=>{document.title=a};var ta=h.print||console.log.bind(console),k=h.printErr||console.warn.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(ea=h.quit);var ua;h.wasmBinary&&(ua=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0,va,wa=!1,xa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ya(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&xa)return xa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function l(a,b){return a?ya(r,a,b):""}
function za(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function w(a,b,c){return za(a,r,b,c)}
function Aa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var x,r,Ba,Ca,y,z,B,E;function Da(){var a=va.buffer;h.HEAP8=x=new Int8Array(a);h.HEAP16=Ba=new Int16Array(a);h.HEAP32=y=new Int32Array(a);h.HEAPU8=r=new Uint8Array(a);h.HEAPU16=Ca=new Uint16Array(a);h.HEAPU32=z=new Uint32Array(a);h.HEAPF32=B=new Float32Array(a);h.HEAPF64=E=new Float64Array(a)}var Ea=h.INITIAL_MEMORY||536870912;
268435456<=Ea||Fa("INITIAL_MEMORY should be larger than STACK_SIZE, was "+Ea+"! (STACK_SIZE=268435456)");h.wasmMemory?va=h.wasmMemory:va=new WebAssembly.Memory({initial:Ea/65536,maximum:32768});Da();Ea=va.buffer.byteLength;var Ga,Ha=[],Ia=[],Ja=[],Ka=[],La=[];function Ma(){var a=h.preRun.shift();Ha.unshift(a)}var Na=0,Oa=null,Pa=null;function Qa(){Na++;h.monitorRunDependencies&&h.monitorRunDependencies(Na)}
function Ra(){Na--;h.monitorRunDependencies&&h.monitorRunDependencies(Na);if(0==Na&&(null!==Oa&&(clearInterval(Oa),Oa=null),Pa)){var a=Pa;Pa=null;a()}}function Fa(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";k(a);wa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Sa(a){return a.startsWith("data:application/octet-stream;base64,")}var Ta;Ta="basque.wasm";Sa(Ta)||(Ta=la(Ta));
function Ua(a){try{if(a==Ta&&ua)return new Uint8Array(ua);if(oa)return oa(a);throw"both async and sync fetching of the wasm failed";}catch(b){Fa(b)}}
function Va(a){if(!ua&&(fa||ha)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return Ua(a)});if(na)return new Promise(function(b,c){na(a,function(d){b(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return Ua(a)})}
function Wa(a,b,c){return Va(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){k("failed to asynchronously prepare wasm: "+d);if("undefined"!=typeof location){var e=location.search;if(0>e.indexOf("_rwasm=0")){location.href+=(e?e+"&":"?")+"_rwasm=0";return}}Fa(d)})}
function Xa(a,b){var c=Ta;ua||"function"!=typeof WebAssembly.instantiateStreaming||Sa(c)||c.startsWith("file://")||ia||"function"!=typeof fetch?Wa(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){k("wasm streaming compile failed: "+e);k("falling back to ArrayBuffer instantiation");return Wa(c,a,b)})})}var F,G,Ya="basque.html.mem";
function Za(){Sa(Ya)||(Ya=la(Ya));if(ia||ja){var a=oa(Ya);r.set(a,1024)}else{Qa("memory initializer");var b=d=>{d.byteLength&&(d=new Uint8Array(d));r.set(d,1024);h.memoryInitializerRequest&&delete h.memoryInitializerRequest.response;Ra("memory initializer")},c=()=>{na(Ya,b,function(){throw Error("could not load memory initializer "+Ya);})};h.memoryInitializerRequest?(a=()=>{var d=h.memoryInitializerRequest,e=d.response;200!==d.status&&0!==d.status?(console.warn("a problem seems to have happened with Module.memoryInitializerRequest, status: "+
d.status+", retrying "+Ya),c()):b(e)},h.memoryInitializerRequest.response?setTimeout(a,0):h.memoryInitializerRequest.addEventListener("load",a)):c()}}
var fb={382624:a=>{a=l(a)+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return $a(ab(a),"i8",bb)},382849:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,382996:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,383230:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.ee||("undefined"!==
typeof AudioContext?b.ee=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ee=new webkitAudioContext),b.ee&&cb(b.ee));return void 0===b.ee?-1:0},383723:()=>h.SDL2.ee.sampleRate,383791:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.Be&&(clearTimeout(g.capture.Be),g.capture.Be=void 0);g.capture.Ie=g.ee.createMediaStreamSource(m);g.capture.ge=g.ee.createScriptProcessor(b,a,1);g.capture.ge.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),
g.capture.Ne=n.inputBuffer,db(c,[d]))};g.capture.Ie.connect(g.capture.ge);g.capture.ge.connect(g.ee.destination);g.capture.stream=m}var g=h.SDL2;g.capture.Ke=g.ee.createBuffer(a,b,g.ee.sampleRate);g.capture.Ke.getChannelData(0).fill(0);g.capture.Be=setTimeout(function(){g.capture.Ne=g.capture.Ke;db(c,[d])},b/g.ee.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&
navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},385443:(a,b,c,d)=>{var e=h.SDL2;e.audio.ge=e.ee.createScriptProcessor(b,0,a);e.audio.ge.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.bf=f.outputBuffer,db(c,[d]))};e.audio.ge.connect(e.ee.destination)},385853:(a,b)=>{for(var c=h.SDL2,d=c.capture.Ne.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ne.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+
b+" samples!";if(1==d)for(var g=0;g<b;++g)eb(a+4*g,f[g]);else for(g=0;g<b;++g)eb(a+4*(g*d+e),f[g])}},386458:(a,b)=>{for(var c=h.SDL2,d=c.audio.bf.numberOfChannels,e=0;e<d;++e){var f=c.audio.bf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=B[a+(g*d+e<<2)>>2]}},386938:a=>{var b=h.SDL2;if(a){void 0!==b.capture.Be&&clearTimeout(b.capture.Be);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();
for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.ge&&(b.capture.ge.onaudioprocess=function(){},b.capture.ge.disconnect(),b.capture.ge=void 0);void 0!==b.capture.Ie&&(b.capture.Ie.disconnect(),b.capture.Ie=void 0);void 0!==b.capture.Ke&&(b.capture.Ke=void 0);b.capture=void 0}else void 0!=b.audio.ge&&(b.audio.ge.disconnect(),b.audio.ge=void 0),b.audio=void 0;void 0!==b.ee&&void 0===b.audio&&void 0===b.capture&&(b.ee.close(),b.ee=void 0)},388110:(a,
b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.xf!==h.canvas&&(d.ne=h.createContext(h.canvas,!1,!0),d.xf=h.canvas);if(d.w!==a||d.Gf!==b||d.If!==d.ne)d.image=d.ne.createImageData(a,b),d.w=a,d.Gf=b,d.If=d.ne;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=y[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Af!==a&&(d.zf=new Int32Array(a.buffer),d.Bf=new Uint8Array(a.buffer),d.Af=a),a=d.zf,c=a.length,
a.set(y.subarray(b,b+c)),a=d.Bf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.ne.putImageData(d.image,0,0)},389579:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<
n;){var p=y[e];b[m]=p&255;b[m+1]=p>>8&255;b[m+2]=p>>16&255;b[m+3]=p>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(y.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=H(c.length+1);w(c,d,c.length+1);return d},390568:a=>{h.canvas&&(h.canvas.style.cursor=l(a))},390651:()=>{h.canvas&&(h.canvas.style.cursor="none")},390720:()=>window.innerWidth,390750:()=>window.innerHeight};
function sa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function gb(a,b,c){a.addEventListener(b,c,{once:!0})}function cb(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&gb(d,c,()=>{"suspended"===a.state&&a.resume()})})})}function hb(a){for(;0<a.length;)a.shift()(h)}var ib=[];
function I(a){var b=ib[a];b||(a>=ib.length&&(ib.length=a+1),ib[a]=b=Ga.get(a));return b}function db(a,b){if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else I(a).apply(null,b)}
function eb(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":x[a>>0]=b;break;case "i8":x[a>>0]=b;break;case "i16":Ba[a>>1]=b;break;case "i32":y[a>>2]=b;break;case "i64":G=[b>>>0,(F=b,1<=+Math.abs(F)?0<F?(Math.min(+Math.floor(F/4294967296),4294967295)|0)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)];y[a>>2]=G[0];y[a+4>>2]=G[1];break;case "float":B[a>>2]=b;break;case "double":E[a>>3]=b;break;case "*":z[a>>2]=b;break;default:Fa("invalid type for setValue: "+c)}}
var jb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},kb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=jb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},lb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},mb=a=>
{if("/"===a)return"/";a=kb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function nb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return()=>b.randomBytes(1)[0]}catch(c){}return()=>Fa("randomDevice")}
function ob(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=jb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function ab(a,b){var c=Array(Aa(a)+1);a=za(a,c,0,c.length);b&&(c.length=a);return c}var pb=[];function qb(a,b){pb[a]={input:[],output:[],ye:b};rb(a,sb)}
var sb={open:function(a){var b=pb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ye.fsync(a.tty)},fsync:function(a){a.tty.ye.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ye.ef)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.ye.ef(a.tty)}catch(m){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.ye.Se)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.ye.Se(a.tty,b[c+e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},tb={ef:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ab(b,!0)}return a.input.shift()},Se:function(a,b){null===b||10===b?(ta(ya(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(ta(ya(a.output,0)),a.output=[])}},ub={Se:function(a,b){null===b||10===b?(k(ya(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(k(ya(a.output,0)),a.output=[])}};
function vb(a){a=65536*Math.ceil(a/65536);var b=wb(65536,a);b?(r.fill(0,b,b+a),a=b):a=0;return a}
var K={pe:null,qe:function(){return K.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.pe||(K.pe={dir:{node:{oe:K.$d.oe,he:K.$d.he,lookup:K.$d.lookup,Je:K.$d.Je,rename:K.$d.rename,unlink:K.$d.unlink,rmdir:K.$d.rmdir,readdir:K.$d.readdir,symlink:K.$d.symlink},stream:{ue:K.be.ue}},file:{node:{oe:K.$d.oe,he:K.$d.he},stream:{ue:K.be.ue,read:K.be.read,write:K.be.write,Xe:K.be.Xe,Re:K.be.Re,lf:K.be.lf}},link:{node:{oe:K.$d.oe,he:K.$d.he,
readlink:K.$d.readlink},stream:{}},af:{node:{oe:K.$d.oe,he:K.$d.he},stream:xb}});c=yb(a,b,c,d);16384===(c.mode&61440)?(c.$d=K.pe.dir.node,c.be=K.pe.dir.stream,c.ae={}):32768===(c.mode&61440)?(c.$d=K.pe.file.node,c.be=K.pe.file.stream,c.ce=0,c.ae=null):40960===(c.mode&61440)?(c.$d=K.pe.link.node,c.be=K.pe.link.stream):8192===(c.mode&61440)&&(c.$d=K.pe.af.node,c.be=K.pe.af.stream);c.timestamp=Date.now();a&&(a.ae[b]=c,a.timestamp=c.timestamp);return c},bg:function(a){return a.ae?a.ae.subarray?a.ae.subarray(0,
a.ce):new Uint8Array(a.ae):new Uint8Array(0)},cf:function(a,b){var c=a.ae?a.ae.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ae,a.ae=new Uint8Array(b),0<a.ce&&a.ae.set(c.subarray(0,a.ce),0))},Qf:function(a,b){if(a.ce!=b)if(0==b)a.ae=null,a.ce=0;else{var c=a.ae;a.ae=new Uint8Array(b);c&&a.ae.set(c.subarray(0,Math.min(b,a.ce)));a.ce=b}},$d:{oe:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;
16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ce:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.wf=4096;b.blocks=Math.ceil(b.size/b.wf);return b},he:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.Qf(a,b.size)},lookup:function(){throw zb[44];},Je:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===
(a.mode&61440)){try{var d=Ab(b,c)}catch(f){}if(d)for(var e in d.ae)throw new J(55);}delete a.parent.ae[a.name];a.parent.timestamp=Date.now();a.name=c;b.ae[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.ae[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Ab(a,b),d;for(d in c.ae)throw new J(55);delete a.ae[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.ae)a.ae.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,
b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},be:{read:function(a,b,c,d,e){var f=a.node.ae;if(e>=a.node.ce)return 0;a=Math.min(a.node.ce-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===x.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ae||a.ae.subarray)){if(f)return a.ae=b.subarray(c,c+d),a.ce=d;if(0===a.ce&&0===e)return a.ae=
b.slice(c,c+d),a.ce=d;if(e+d<=a.ce)return a.ae.set(b.subarray(c,c+d),e),d}K.cf(a,e+d);if(a.ae.subarray&&b.subarray)a.ae.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ae[e+f]=b[c+f];a.ce=Math.max(a.ce,e+d);return d},ue:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ce);if(0>b)throw new J(28);return b},Xe:function(a,b,c){K.cf(a.node,b+c);a.node.ce=Math.max(a.node.ce,b+c)},Re:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.ae;if(e&2||
a.buffer!==x.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=vb(b);if(!b)throw new J(48);x.set(a,b)}else c=!1,b=a.byteOffset;return{Of:b,vf:c}},lf:function(a,b,c,d){K.be.write(a,b,0,d,c,!1);return 0}}};function Bb(a,b,c){var d="al "+a;na(a,e=>{e||Fa('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ra(d)},()=>{if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Qa(d)}
var Cb=null,Db={},Eb=[],Fb=1,Gb=null,Hb=!0,J=null,zb={},Jb=(a,b={})=>{a=ob(a);if(!a)return{path:"",node:null};b=Object.assign({df:!0,Te:0},b);if(8<b.Te)throw new J(32);a=a.split("/").filter(g=>!!g);for(var c=Cb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Ab(c,a[e]);d=kb(d+"/"+a[e]);c.we&&(!f||f&&b.df)&&(c=c.we.root);if(!f||b.Ee)for(f=0;40960===(c.mode&61440);)if(c=Ib(d),d=ob(lb(d),c),c=Jb(d,{Te:b.Te+1}).node,40<f++)throw new J(32);}return{path:d,node:c}},Kb=a=>{for(var b;;){if(a===
a.parent)return a=a.qe.kf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Lb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Gb.length},Mb=a=>{var b=Lb(a.parent.id,a.name);if(Gb[b]===a)Gb[b]=a.xe;else for(b=Gb[b];b;){if(b.xe===a){b.xe=a.xe;break}b=b.xe}},Ab=(a,b)=>{var c;if(c=(c=Nb(a,"x"))?c:a.$d.lookup?0:2)throw new J(c,a);for(c=Gb[Lb(a.id,b)];c;c=c.xe){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.$d.lookup(a,b)},yb=(a,b,
c,d)=>{a=new Ob(a,b,c,d);b=Lb(a.parent.id,a.name);a.xe=Gb[b];return Gb[b]=a},Pb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Qb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Nb=(a,b)=>{if(Hb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Rb=(a,b)=>{try{return Ab(a,b),20}catch(c){}return Nb(a,"wx")},Sb=(a,b,c)=>{try{var d=Ab(a,b)}catch(e){return e.le}if(a=Nb(a,"wx"))return a;if(c){if(16384!==(d.mode&
61440))return 54;if(d===d.parent||"/"===Kb(d))return 10}else if(16384===(d.mode&61440))return 31;return 0},Tb=(a=0)=>{for(;4096>=a;a++)if(!Eb[a])return a;throw new J(33);},Vb=(a,b)=>{Ub||(Ub=function(){this.de={}},Ub.prototype={},Object.defineProperties(Ub.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.de.flags},set:function(c){this.de.flags=c}},position:{get:function(){return this.de.position},set:function(c){this.de.position=c}}}));
a=Object.assign(new Ub,a);b=Tb(b);a.fd=b;return Eb[b]=a},xb={open:a=>{a.be=Db[a.node.rdev].be;a.be.open&&a.be.open(a)},ue:()=>{throw new J(70);}},rb=(a,b)=>{Db[a]={be:b}},Wb=(a,b)=>{var c="/"===b,d=!b;if(c&&Cb)throw new J(10);if(!c&&!d){var e=Jb(b,{df:!1});b=e.path;e=e.node;if(e.we)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);}b={type:a,hg:{},kf:b,Nf:[]};a=a.qe(b);a.qe=b;b.root=a;c?Cb=a:e&&(e.we=b,e.qe&&e.qe.Nf.push(b))},L=(a,b,c)=>{var d=Jb(a,{parent:!0}).node;a=mb(a);if(!a||"."===a||
".."===a)throw new J(28);var e=Rb(d,a);if(e)throw new J(e);if(!d.$d.Je)throw new J(63);return d.$d.Je(d,a,b,c)},Xb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return L(a,b|8192,c)},Yb=(a,b)=>{if(!ob(a))throw new J(44);var c=Jb(b,{parent:!0}).node;if(!c)throw new J(44);b=mb(b);var d=Rb(c,b);if(d)throw new J(d);if(!c.$d.symlink)throw new J(63);c.$d.symlink(c,b,a)},Zb=a=>{var b=Jb(a,{parent:!0}).node;a=mb(a);var c=Ab(b,a),d=Sb(b,a,!0);if(d)throw new J(d);if(!b.$d.rmdir)throw new J(63);if(c.we)throw new J(10);
b.$d.rmdir(b,a);Mb(c)},$b=a=>{var b=Jb(a,{parent:!0}).node;if(!b)throw new J(44);a=mb(a);var c=Ab(b,a),d=Sb(b,a,!1);if(d)throw new J(d);if(!b.$d.unlink)throw new J(63);if(c.we)throw new J(10);b.$d.unlink(b,a);Mb(c)},Ib=a=>{a=Jb(a).node;if(!a)throw new J(44);if(!a.$d.readlink)throw new J(28);return ob(Kb(a.parent),a.$d.readlink(a))},ac=(a,b)=>{a="string"==typeof a?Jb(a,{Ee:!0}).node:a;if(!a.$d.he)throw new J(63);a.$d.he(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},cc=(a,b,c)=>{if(""===a)throw new J(44);
if("string"==typeof b){var d=Pb[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=kb(a);try{e=Jb(a,{Ee:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new J(20);}else e=L(a,c,0),d=!0;if(!e)throw new J(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new J(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Qb(b)||b&512)?31:
Nb(e,Qb(b)):44))throw new J(c);if(b&512&&!d){c=e;c="string"==typeof c?Jb(c,{Ee:!0}).node:c;if(!c.$d.he)throw new J(63);if(16384===(c.mode&61440))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(d=Nb(c,"w"))throw new J(d);c.$d.he(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Vb({node:e,path:Kb(e),flags:b,seekable:!0,position:0,be:e.be,Tf:[],error:!1});e.be.open&&e.be.open(e);!h.logReadFiles||b&1||(bc||(bc={}),a in bc||(bc[a]=1));return e},dc=a=>{if(null===a.fd)throw new J(8);a.Pe&&(a.Pe=
null);try{a.be.close&&a.be.close(a)}catch(b){throw b;}finally{Eb[a.fd]=null}a.fd=null},ec=(a,b,c)=>{if(null===a.fd)throw new J(8);if(!a.seekable||!a.be.ue)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.be.ue(a,b,c);a.Tf=[]},fc=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(16384===(a.node.mode&61440))throw new J(31);if(!a.be.write)throw new J(28);a.seekable&&a.flags&1024&&ec(a,0,2);var g="undefined"!=typeof e;
if(!g)e=a.position;else if(!a.seekable)throw new J(70);b=a.be.write(a,b,c,d,e,f);g||(a.position+=b);return b},gc=()=>{J||(J=function(a,b){this.name="ErrnoError";this.node=b;this.Rf=function(c){this.le=c};this.Rf(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(a=>{zb[a]=new J(a);zb[a].stack="<generic error, no stack>"}))},hc,ic=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},jc=(a,b)=>{a="string"==typeof a?a:Kb(a);for(b=b.split("/").reverse();b.length;){var c=
b.pop();if(c){var d=kb(a+"/"+c);try{L(d,16895,0)}catch(e){}a=d}}return d},kc=(a,b,c,d)=>{a=kb(("string"==typeof a?a:Kb(a))+"/"+b);c=ic(c,d);return L(a,(void 0!==c?c:438)&4095|32768,0)},lc=(a,b,c,d,e,f)=>{var g=b;a&&(a="string"==typeof a?a:Kb(a),g=b?kb(a+"/"+b):a);a=ic(d,e);g=L(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}ac(g,a|146);b=cc(g,577);fc(b,c,0,c.length,0,f);dc(b);ac(g,a)}return g},nc=(a,b,c,d)=>{a=kb(("string"==
typeof a?a:Kb(a))+"/"+b);b=ic(!!c,!!d);nc.hf||(nc.hf=64);var e=nc.hf++<<8|0;rb(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,g,m,n)=>{for(var p=0,u=0;u<n;u++){try{var q=c()}catch(t){throw new J(29);}if(void 0===q&&0===p)throw new J(6);if(null===q||void 0===q)break;p++;g[m+u]=q}p&&(f.node.timestamp=Date.now());return p},write:(f,g,m,n)=>{for(var p=0;p<n;p++)try{d(g[m+p])}catch(u){throw new J(29);}n&&(f.node.timestamp=Date.now());return p}});return Xb(a,b,e)},oc=
a=>{if(!(a.Lf||a.Mf||a.link||a.ae)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ma)try{a.ae=ab(ma(a.url),!0),a.ce=a.ae.length}catch(b){throw new J(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},pc=(a,b,c,d,e)=>{function f(){this.Qe=!1;this.de=[]}function g(q,t,v,A,C){q=
q.node.ae;if(C>=q.length)return 0;A=Math.min(q.length-C,A);if(q.slice)for(var D=0;D<A;D++)t[v+D]=q[C+D];else for(D=0;D<A;D++)t[v+D]=q.get(C+D);return A}f.prototype.get=function(q){if(!(q>this.length-1||0>q)){var t=q%this.chunkSize;return this.ff(q/this.chunkSize|0)[t]}};f.prototype.Ae=function(q){this.ff=q};f.prototype.Ze=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var t=
Number(q.getResponseHeader("Content-length")),v,A=(v=q.getResponseHeader("Accept-Ranges"))&&"bytes"===v;q=(v=q.getResponseHeader("Content-Encoding"))&&"gzip"===v;var C=1048576;A||(C=t);var D=this;D.Ae(S=>{var da=S*C,ra=(S+1)*C-1;ra=Math.min(ra,t-1);if("undefined"==typeof D.de[S]){var mc=D.de;if(da>ra)throw Error("invalid range ("+da+", "+ra+") or no bytes requested!");if(ra>t-1)throw Error("only "+t+" bytes available! programmer error!");var X=new XMLHttpRequest;X.open("GET",c,!1);t!==C&&X.setRequestHeader("Range",
"bytes="+da+"-"+ra);X.responseType="arraybuffer";X.overrideMimeType&&X.overrideMimeType("text/plain; charset=x-user-defined");X.send(null);if(!(200<=X.status&&300>X.status||304===X.status))throw Error("Couldn't load "+c+". Status: "+X.status);da=void 0!==X.response?new Uint8Array(X.response||[]):ab(X.responseText||"",!0);mc[S]=da}if("undefined"==typeof D.de[S])throw Error("doXHR failed!");return D.de[S]});if(q||!t)C=t=1,C=t=this.ff(0).length,ta("LazyFiles on gzip forces download of the whole file when length is accessed");
this.uf=t;this.tf=C;this.Qe=!0};if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var m=new f;Object.defineProperties(m,{length:{get:function(){this.Qe||this.Ze();return this.uf}},chunkSize:{get:function(){this.Qe||this.Ze();return this.tf}}});var n=void 0}else n=c,m=void 0;var p=kc(a,b,d,e);m?p.ae=m:n&&(p.ae=null,p.url=n);Object.defineProperties(p,{ce:{get:function(){return this.ae.length}}});
var u={};Object.keys(p.be).forEach(q=>{var t=p.be[q];u[q]=function(){oc(p);return t.apply(null,arguments)}});u.read=(q,t,v,A,C)=>{oc(p);return g(q,t,v,A,C)};u.Re=(q,t,v)=>{oc(p);var A=vb(t);if(!A)throw new J(48);g(q,x,A,t,v);return{Of:A,vf:!0}};p.be=u;return p},rc=(a,b,c,d,e,f,g,m,n,p)=>{function u(v){function A(C){p&&p();m||lc(a,b,C,d,e,n);f&&f();Ra(t)}qc(v,q,A,()=>{g&&g();Ra(t)})||A(v)}var q=b?ob(kb(a+"/"+b)):a,t="cp "+q;Qa(t);"string"==typeof c?Bb(c,v=>u(v),g):u(c)},sc={},Ub,bc;
function tc(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":uc(a).path;if(0==b.length)throw new J(44);return kb(a+"/"+b)}var vc=void 0;function wc(){vc+=4;return y[vc-4>>2]}function uc(a){a=Eb[a];if(!a)throw new J(8);return a}
function xc(a,b){yc=a;zc=b;if(Ac)if(Bc||(Bc=!0),0==a)Cc=function(){var d=Math.max(0,Dc+b-Ec())|0;setTimeout(Fc,d)};else if(1==a)Cc=function(){Gc(Fc)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Cc=function(){setImmediate(Fc)}}}var Ec;Ec=ia?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();
function Hc(a,b,c,d,e){!Ac||Fa("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ac=a;Ic=d;var f=Jc;Bc=!1;Fc=function(){if(!wa)if(0<Kc.length){var g=Date.now(),m=Kc.shift();m.ag(m.Wf);if(Lc){var n=Lc,p=0==n%1?n-1:Math.floor(n);Lc=m.Yf?p:(8*n+(p+.5))/9}ta('main loop blocker "'+m.name+'" took '+(Date.now()-g)+" ms");h.setStatus&&(g=h.statusMessage||"Please wait...",
m=Lc,n=Mc.Zf,m?m<n?h.setStatus(g+" ("+(n-m)+"/"+n+")"):h.setStatus(g):h.setStatus(""));f<Jc||setTimeout(Fc,0)}else f<Jc||(Nc=Nc+1|0,1==yc&&1<zc&&0!=Nc%zc?Cc():(0==yc&&(Dc=Ec()),wa||h.preMainLoop&&!1===h.preMainLoop()||(Oc(a),h.postMainLoop&&h.postMainLoop()),f<Jc||("object"==typeof SDL&&SDL.audio&&SDL.audio.Pf&&SDL.audio.Pf(),Cc())))};e||(b&&0<b?xc(0,1E3/b):xc(1,1),Cc());if(c)throw"unwind";}function Pc(a){a instanceof sa||"unwind"==a||ea(1,a)}function Oc(a){if(!wa)try{a()}catch(b){Pc(b)}}
function Qc(a){setTimeout(function(){Oc(a)},1E4)}function Rc(a){Sc||(Sc={});Sc[a]||(Sc[a]=1,ia&&(a="warning: "+a),k(a))}var Sc,Bc=!1,Cc=null,Jc=0,Ac=null,Ic=0,yc=0,zc=0,Nc=0,Kc=[],Mc={},Dc,Fc,Lc,Tc=!1,Uc=!1,Vc=[];
function Wc(){function a(){Uc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!Xc){Xc=!0;try{Yc=!0}catch(c){Yc=!1,k("warning: no blob constructor, cannot create blobs with mimetypes")}Zc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Yc?null:k("warning: no BlobBuilder");$c="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;h.mf||"undefined"!=typeof $c||(k("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.mf=!0);h.preloadPlugins.push({canHandle:function(c){return!h.mf&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(Yc)try{g=new Blob([c],{type:ad(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:ad(d)}))}catch(p){Rc("Blob constructor present but fails: "+
p+"; falling back to blob builder")}g||(g=new Zc,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var m=$c.createObjectURL(g),n=new Image;n.onload=()=>{n.complete||Fa("Image "+d+" could not be decoded");var p=document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);bd[d]=p;$c.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{ta("Image "+m+" could not be decoded");f&&f()};n.src=m}});h.preloadPlugins.push({canHandle:function(c){return!h.gg&&c.substr(-4)in{".ogg":1,
".wav":1,".mp3":1}},handle:function(c,d,e,f){function g(){n||(n=!0,e&&e(c))}function m(){n||(n=!0,new Audio,f&&f())}var n=!1;if(Yc){try{var p=new Blob([c],{type:ad(d)})}catch(q){return m()}p=$c.createObjectURL(p);var u=new Audio;u.addEventListener("canplaythrough",()=>g(u),!1);u.onerror=function(){if(!n){k("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var q="",t=0,v=0,A=0;A<c.length;A++)for(t=t<<8|c[A],v+=8;6<=v;){var C=t>>v-6&63;v-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[C]}2==
v?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],q+="=="):4==v&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],q+="=");u.src="data:audio/x-"+d.substr(-3)+";base64,"+q;g(u)}};u.src=p;Qc(function(){g(u)})}else return m()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Uc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function qc(a,b,c,d){Wc();var e=!1;h.preloadPlugins.forEach(function(f){!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e}
function cd(a,b,c,d){if(b&&h.ne&&a==h.canvas)return h.ne;var e;if(b){var f={antialias:!1,alpha:!1,jf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof dd&&(e=ed(a,f)))var m=fd[e].re}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof M||Fa("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.ne=m,b&&gd(e),h.Uf=b,Vc.forEach(function(n){n()}),Wc());return m}var hd=!1,jd=void 0,kd=void 0;
function ld(a,b){function c(){Tc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=md,jd&&d.requestPointerLock(),Tc=!0,kd?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]|8388608),nd(h.canvas),od()):nd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),kd?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]&
-8388609),nd(h.canvas),od()):nd(d));if(h.onFullScreen)h.onFullScreen(Tc);if(h.onFullscreen)h.onFullscreen(Tc)}jd=a;kd=b;"undefined"==typeof jd&&(jd=!0);"undefined"==typeof kd&&(kd=!1);var d=h.canvas;hd||(hd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function md(){if(!Tc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var pd=0;function Gc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===pd)pd=b+1E3/60;else for(;b+2>=pd;)pd+=1E3/60;setTimeout(a,Math.max(pd-b,0))}}
function ad(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var qd=[];function od(){var a=h.canvas;qd.forEach(function(b){b(a.width,a.height)})}
function nd(a,b,c){b&&c?(a.Vf=b,a.Hf=c):(b=a.Vf,c=a.Hf);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}kd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Xc,Yc,Zc,$c,N=12288,rd=!1,sd=0,td=0,ud=0,O={alpha:!1,depth:!1,stencil:!1,antialias:!1},vd={},wd;function xd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function yd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function zd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Ad=1,Bd=[],P=[],Cd=[],Dd=[],Ed=[],Q=[],Fd=[],fd=[],Gd=[],Hd={},Id=4;
function R(a){Jd||(Jd=a)}function Kd(a){for(var b=Ad++,c=a.length;c<b;c++)a[c]=null;return b}function ed(a,b){a.de||(a.de=a.getContext,a.getContext=function(d,e){e=a.de(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Ld(c,b):0}function Ld(a,b){var c=Kd(fd),d={cg:c,attributes:b,version:b.jf,re:a};a.canvas&&(a.canvas.ze=d);fd[c]=d;("undefined"==typeof b.Df||b.Df)&&Md(d);return c}function gd(a){Nd=fd[a];h.ne=M=Nd&&Nd.re}
function Md(a){a||(a=Nd);if(!a.Jf){a.Jf=!0;var b=a.re;xd(b);yd(b);zd(b);b.ke=b.getExtension("EXT_disjoint_timer_query");b.fg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var dd={},Jd,Nd;function Od(a){var b=Aa(a)+1,c=H(b);c&&za(a,x,c,b);return c}var Pd=[];function Qd(a,b){Pd.length=0;var c;for(b>>=2;c=r[a++];)b+=105!=c&b,Pd.push(105==c?y[b]:E[b++>>1]),++b;return Pd}
function Rd(a){var b=T();a=a();U(b);return a}var Sd=0;function Td(){for(var a=Ud.length-1;0<=a;--a)Vd(a);Ud=[];Wd=[]}var Wd=[];function Xd(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in Wd){var f=Wd[e];if(f.Ve==a&&d(f.Ye,c))return}Wd.push({Ve:a,pf:b,Ye:c});Wd.sort(function(g,m){return g.pf<m.pf})}function Yd(a){for(var b=0;b<Wd.length;++b)Wd[b].Ve==a&&(Wd.splice(b,1),--b)}
function Zd(){if(Sd&&$d.te)for(var a=0;a<Wd.length;++a){var b=Wd[a];Wd.splice(a,1);--a;b.Ve.apply(null,b.Ye)}}var Ud=[];function Vd(a){var b=Ud[a];b.target.removeEventListener(b.fe,b.Ef,b.ie);Ud.splice(a,1)}function ae(a){function b(d){++Sd;$d=a;Zd();a.me(d);Zd();--Sd}if(a.je)a.Ef=b,a.target.addEventListener(a.fe,b,a.ie),Ud.push(a),be||(Ka.push(Td),be=!0);else for(var c=0;c<Ud.length;++c)Ud[c].target==a.target&&Ud[c].fe==a.fe&&Vd(c--)}
function ce(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function de(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var ee={},be,$d,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re={},se=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function V(a){a=2<a?l(a):a;return se[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}
function te(a){return Rd(function(){var b=ue(8),c=b+4,d=ue(a.id.length+1);w(a.id,d,a.id.length+1);if(d=V(d))y[b>>2]=d.width,y[c>>2]=d.height;return[y[b>>2],y[c>>2]]})}function ve(a,b,c){a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0}function we(a,b,c){a.Xf?Rd(function(){var d=ue(a.id.length+1);w(a.id,d,a.id.length+1);ve(d,b,c)}):(a.width=b,a.height=c)}
function xe(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),we(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=u,a.style.paddingTop=q,a.style.paddingBottom=t,a.style.marginLeft=v,a.style.marginRight=A,a.style.marginTop=
C,a.style.marginBottom=D,document.body.style.margin=S,document.documentElement.style.overflow=da,document.body.scroll=ra,a.style.se=mc,a.ze&&a.ze.re.viewport(0,0,d,e),re.De&&I(re.De)(37,0,re.$e))}var c=te(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,u=a.style.paddingRight,q=a.style.paddingTop,t=a.style.paddingBottom,v=a.style.marginLeft,A=a.style.marginRight,C=a.style.marginTop,D=a.style.marginBottom,S=document.body.style.margin,
da=document.documentElement.style.overflow,ra=document.body.scroll,mc=a.style.se;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function ye(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function ze(a){return 0>se.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Ae(a,b){if(0!=b.Ue||0!=b.Me){xe(a);var c=b.Sf?innerWidth:screen.width,d=b.Sf?innerHeight:screen.height,e=ze(a),f=e.width;e=e.height;var g=te(a),m=g[0];g=g[1];3==b.Ue?(ye(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Ue&&(c*g<m*d?(f=g*c/m,ye(a,(d-f)/2,0),d=f):(f=m*d/g,ye(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Ff&&(a.style.se="optimizeSpeed",
a.style.se="-moz-crisp-edges",a.style.se="-o-crisp-edges",a.style.se="-webkit-optimize-contrast",a.style.se="optimize-contrast",a.style.se="crisp-edges",a.style.se="pixelated");f=2==b.Me?devicePixelRatio:1;0!=b.Me&&(c=c*f|0,d=d*f|0,we(a,c,d),a.ze&&a.ze.re.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return de()?-3:-1;re=b;b.De&&I(b.De)(37,0,b.$e);return 0}
function Be(a){if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0}
function Ce(a,b){E[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)E[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)E[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)y[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];y[a+1296>>2]=b.connected;y[a+1300>>2]=b.index;y[a+8>>2]=b.axes.length;y[a+12>>2]=b.buttons.length;w(b.id,a+1304,64);w(b.mapping,a+1368,64)}
function De(a,b,c){(a|0)===a&&(a=l(a));a=ob(a);if(a=bd[a]){var d=a.getContext("2d").getImageData(0,0,a.width,a.height),e=H(a.width*a.height*4);r.set(d.data,e);y[b>>2]=a.width;y[c>>2]=a.height;return e}return 0}var Ee=[];function Fe(a,b,c,d){for(var e=0;e<a;e++){var f=M[c](),g=f&&Kd(d);f?(f.name=g,d[g]=f):R(1282);y[b+4*e>>2]=g}}function Ge(a,b,c,d,e,f,g,m){b=P[b];if(a=M[a](b,c))d=m&&w(a.name,m,d),e&&(y[e>>2]=d),f&&(y[f>>2]=a.size),g&&(y[g>>2]=a.type)}
function He(a,b){z[a>>2]=b;z[a+4>>2]=(b-z[a>>2])/4294967296}
function Ie(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=M.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=M.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:y[b+4*a>>2]=e[a];break;case 2:B[b+4*a>>2]=e[a];break;case 4:x[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){R(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:R(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:He(b,
d);break;case 0:y[b>>2]=d;break;case 2:B[b>>2]=d;break;case 4:x[b>>0]=d?1:0}}else R(1281)}function Je(a){var b=Aa(a)+1,c=H(b);w(a,c,b);return c}function Ke(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Le(a){var b=a.Ce,c=a.sf,d;if(!b)for(a.Ce=b={},a.rf={},d=0;d<M.getProgramParameter(a,35718);++d){var e=M.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Ke(f);g=0<g?f.slice(0,g):f;var m=a.We;a.We+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.rf[m++]=g}}
function W(a){var b=M.yf;if(b){var c=b.Ce[a];"number"==typeof c&&(b.Ce[a]=c=M.getUniformLocation(b,b.rf[a]+(0<c?"["+c+"]":"")));return c}R(1282)}function Me(a,b,c,d){if(c)if(a=P[a],Le(a),a=M.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:y[c>>2]=a;break;case 2:B[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:y[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b]}else R(1281)}
function Ne(a,b,c,d){if(c)if(a=M.getVertexAttrib(a,b),34975==b)y[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:y[c>>2]=a;break;case 2:B[c>>2]=a;break;case 5:y[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:y[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b];break;case 5:y[c+4*b>>2]=Math.fround(a[b])}else R(1281)}
function Oe(a,b,c,d,e){a-=5120;a=1==a?r:4==a?y:6==a?B:5==a||28922==a?z:Ca;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Id;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var Pe=[],Qe=[];function Re(a,b){if(!de())return-1;a=V(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Sd&&$d.te?Ae(a,b):b.Cf?(Xd(Ae,1,[a,b]),1):-2:-3:-4}
function Se(a,b){var c={target:V(2),fe:"beforeunload",je:b,me:function(d=event){var e=I(b)(28,0,a);e&&(e=l(e));if(e)return d.preventDefault(),d.returnValue=e},ie:!0};ae(c)}function Te(a,b,c,d,e,f){ge||(ge=H(256));a={target:V(a),fe:f,je:d,me:function(g=event){var m=g.target.id?g.target.id:"",n=ge;w(ce(g.target),n+0,128);w(m,n+128,128);I(d)(e,n,b)&&g.preventDefault()},ie:c};ae(a)}
function Ue(a,b,c,d,e){ie||(ie=H(280));ae({target:a,fe:e,je:d,me:function(f=event){var g=ie,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;y[g>>2]=n;y[g+4>>2]=de();var p=n?m:he,u=p&&p.id?p.id:"";w(ce(p),g+8,128);w(u,g+136,128);y[g+264>>2]=p?p.clientWidth:0;y[g+268>>2]=p?p.clientHeight:0;y[g+272>>2]=screen.width;y[g+276>>2]=screen.height;n&&(he=m);I(d)(19,g,b)&&f.preventDefault()},ie:c})}
function Ve(a,b,c,d,e){je||(je=H(1432));b={target:V(2),te:!0,fe:e,je:c,me:function(f=event){var g=je;Ce(g,f.gamepad);I(c)(d,g,a)&&f.preventDefault()},ie:b};ae(b)}
function We(a,b,c,d,e,f){ke||(ke=H(176));a={target:V(a),te:!0,fe:f,je:d,me:function(g){var m=ke;E[m>>3]=g.timeStamp;var n=m>>2;y[n+2]=g.location;y[n+3]=g.ctrlKey;y[n+4]=g.shiftKey;y[n+5]=g.altKey;y[n+6]=g.metaKey;y[n+7]=g.repeat;y[n+8]=g.charCode;y[n+9]=g.keyCode;y[n+10]=g.which;w(g.key||"",m+44,32);w(g.code||"",m+76,32);w(g.char||"",m+108,32);w(g.locale||"",m+140,32);I(d)(e,m,b)&&g.preventDefault()},ie:c};ae(a)}
function Xe(a,b,c){E[a>>3]=b.timeStamp;a>>=2;y[a+2]=b.screenX;y[a+3]=b.screenY;y[a+4]=b.clientX;y[a+5]=b.clientY;y[a+6]=b.ctrlKey;y[a+7]=b.shiftKey;y[a+8]=b.altKey;y[a+9]=b.metaKey;Ba[2*a+20]=b.button;Ba[2*a+21]=b.buttons;y[a+11]=b.movementX;y[a+12]=b.movementY;c=ze(c);y[a+13]=b.clientX-c.left;y[a+14]=b.clientY-c.top}
function Ye(a,b,c,d,e,f){le||(le=H(72));a=V(a);ae({target:a,te:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,fe:f,je:d,me:function(g=event){Xe(le,g,a);I(d)(e,le,b)&&g.preventDefault()},ie:c})}function Ze(a,b,c,d,e){me||(me=H(260));ae({target:a,fe:e,je:d,me:function(f=event){var g=me,m=document.pointerLockElement||document.de||document.Le||document.Ae;y[g>>2]=!!m;var n=m&&m.id?m.id:"";w(ce(m),g+4,128);w(n,g+132,128);I(d)(20,g,b)&&f.preventDefault()},ie:c})}
function $e(a,b,c,d){ne||(ne=H(36));a=V(a);ae({target:a,fe:"resize",je:d,me:function(e=event){if(e.target==a){var f=document.body;if(f){var g=ne;y[g>>2]=e.detail;y[g+4>>2]=f.clientWidth;y[g+8>>2]=f.clientHeight;y[g+12>>2]=innerWidth;y[g+16>>2]=innerHeight;y[g+20>>2]=outerWidth;y[g+24>>2]=outerHeight;y[g+28>>2]=pageXOffset;y[g+32>>2]=pageYOffset;I(d)(10,g,b)&&e.preventDefault()}}},ie:c})}
function af(a,b,c,d,e,f){oe||(oe=H(1696));a=V(a);ae({target:a,te:"touchstart"==f||"touchend"==f,fe:f,je:d,me:function(g){for(var m,n={},p=g.touches,u=0;u<p.length;++u)m=p[u],m.gf=m.nf=0,n[m.identifier]=m;for(u=0;u<g.changedTouches.length;++u)m=g.changedTouches[u],m.gf=1,n[m.identifier]=m;for(u=0;u<g.targetTouches.length;++u)n[g.targetTouches[u].identifier].nf=1;p=oe;E[p>>3]=g.timeStamp;var q=p>>2;y[q+3]=g.ctrlKey;y[q+4]=g.shiftKey;y[q+5]=g.altKey;y[q+6]=g.metaKey;q+=7;var t=ze(a),v=0;for(u in n)if(m=
n[u],y[q]=m.identifier,y[q+1]=m.screenX,y[q+2]=m.screenY,y[q+3]=m.clientX,y[q+4]=m.clientY,y[q+5]=m.pageX,y[q+6]=m.pageY,y[q+7]=m.gf,y[q+8]=m.nf,y[q+9]=m.clientX-t.left,y[q+10]=m.clientY-t.top,q+=13,31<++v)break;y[p+8>>2]=v;I(d)(e,p,b)&&g.preventDefault()},ie:c})}
function bf(a,b,c){var d=se[1];pe||(pe=H(8));ae({target:d,fe:"visibilitychange",je:c,me:function(e=event){var f=pe,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);y[f>>2]=document.hidden;y[f+4>>2]=g;I(c)(21,f,a)&&e.preventDefault()},ie:b})}
function cf(a,b,c,d){qe||(qe=H(104));ae({target:a,te:!0,fe:"wheel",je:d,me:function(e=event){var f=qe;Xe(f,e,a);E[f+72>>3]=e.deltaX;E[f+80>>3]=e.deltaY;E[f+88>>3]=e.deltaZ;y[f+96>>2]=e.deltaMode;I(d)(9,f,b)&&e.preventDefault()},ie:c})}var df={};
function ef(){if(!ff){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in df)void 0===df[b]?delete a[b]:a[b]=df[b];var c=[];for(b in a)c.push(b+"="+a[b]);ff=c}return ff}var ff;function gf(a){if(!noExitRuntime){if(h.onExit)h.onExit(a);wa=!0}ea(a,new sa(a))}var bb=0,hf=1;
function $a(a,b){b=b==hf?ue(a.length):H(a.length);a.subarray||a.slice||(a=new Uint8Array(a));r.set(a,b);return b}function Ob(a,b,c,d){a||(a=this);this.parent=a;this.qe=a.qe;this.we=null;this.id=Fb++;this.name=b;this.mode=c;this.$d={};this.be={};this.rdev=d}
Object.defineProperties(Ob.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Mf:{get:function(){return 16384===(this.mode&61440)}},Lf:{get:function(){return 8192===(this.mode&61440)}}});gc();Gb=Array(4096);Wb(K,"/");L("/tmp",16895,0);L("/home",16895,0);L("/home/web_user",16895,0);
(()=>{L("/dev",16895,0);rb(259,{read:()=>0,write:(b,c,d,e)=>e});Xb("/dev/null",259);qb(1280,tb);qb(1536,ub);Xb("/dev/tty",1280);Xb("/dev/tty1",1536);var a=nb();nc("/dev","random",a);nc("/dev","urandom",a);L("/dev/shm",16895,0);L("/dev/shm/tmp",16895,0)})();
(()=>{L("/proc",16895,0);var a=L("/proc/self",16895,0);L("/proc/self/fd",16895,0);Wb({qe:()=>{var b=yb(a,"fd",16895,73);b.$d={lookup:(c,d)=>{var e=Eb[+d];if(!e)throw new J(8);c={parent:null,qe:{kf:"fake"},$d:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=jc;h.FS_createDataFile=lc;h.FS_createPreloadedFile=rc;h.FS_unlink=$b;h.FS_createLazyFile=pc;h.FS_createDevice=nc;h.requestFullscreen=function(a,b){ld(a,b)};h.requestAnimationFrame=function(a){Gc(a)};
h.setCanvasSize=function(a,b,c){nd(h.canvas,a,b);c||od()};h.pauseMainLoop=function(){Cc=null;Jc++};h.resumeMainLoop=function(){Jc++;var a=yc,b=zc,c=Ac;Ac=null;Hc(c,0,!1,Ic,!0);xc(a,b);Cc()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return cd(a,b,c,d)};for(var bd={},M,Y=0;32>Y;++Y)Ee.push(Array(Y));var jf=new Float32Array(288);
for(Y=0;288>Y;++Y)Pe[Y]=jf.subarray(0,Y+1);var kf=new Int32Array(288);for(Y=0;288>Y;++Y)Qe[Y]=kf.subarray(0,Y+1);
var zf={W:function(a,b,c,d){Fa("Assertion failed: "+l(a)+", at: "+[b?l(b):"unknown filename",c,d?l(d):"unknown function"])},N:function(a,b,c){vc=c;try{var d=uc(a);switch(b){case 0:var e=wc();return 0>e?-28:Vb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=wc(),d.flags|=e,0;case 5:return e=wc(),Ba[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return y[lf()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof sc||"ErrnoError"!==f.name)throw f;return-f.le}},
eb:function(a,b,c){vc=c;try{var d=uc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=wc();return y[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=wc();if(!d.be.Kf)throw new J(59);return d.be.Kf(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:return-28}}catch(f){if("undefined"==typeof sc||"ErrnoError"!==f.name)throw f;return-f.le}},fb:function(a,
b,c,d){vc=d;try{b=l(b);b=tc(a,b);var e=d?wc():0;return cc(b,c,e).fd}catch(f){if("undefined"==typeof sc||"ErrnoError"!==f.name)throw f;return-f.le}},_a:function(a){try{return a=l(a),Zb(a),0}catch(b){if("undefined"==typeof sc||"ErrnoError"!==b.name)throw b;return-b.le}},cb:function(a,b){try{a=l(a);a:{try{var c=Jb(a,{Ee:!0}).node;if(!c)throw new J(44);if(!c.$d.oe)throw new J(63);var d=c.$d.oe(c)}catch(n){if(n&&n.node&&kb(a)!==kb(Kb(n.node))){var e=-54;break a}throw n;}y[b>>2]=d.dev;y[b+8>>2]=d.ino;y[b+
12>>2]=d.mode;z[b+16>>2]=d.nlink;y[b+20>>2]=d.uid;y[b+24>>2]=d.gid;y[b+28>>2]=d.rdev;G=[d.size>>>0,(F=d.size,1<=+Math.abs(F)?0<F?(Math.min(+Math.floor(F/4294967296),4294967295)|0)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)];y[b+40>>2]=G[0];y[b+44>>2]=G[1];y[b+48>>2]=4096;y[b+52>>2]=d.blocks;var f=d.atime.getTime(),g=d.mtime.getTime(),m=d.ctime.getTime();G=[Math.floor(f/1E3)>>>0,(F=Math.floor(f/1E3),1<=+Math.abs(F)?0<F?(Math.min(+Math.floor(F/4294967296),4294967295)|0)>>>0:~~+Math.ceil((F-
+(~~F>>>0))/4294967296)>>>0:0)];y[b+56>>2]=G[0];y[b+60>>2]=G[1];z[b+64>>2]=f%1E3*1E3;G=[Math.floor(g/1E3)>>>0,(F=Math.floor(g/1E3),1<=+Math.abs(F)?0<F?(Math.min(+Math.floor(F/4294967296),4294967295)|0)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)];y[b+72>>2]=G[0];y[b+76>>2]=G[1];z[b+80>>2]=g%1E3*1E3;G=[Math.floor(m/1E3)>>>0,(F=Math.floor(m/1E3),1<=+Math.abs(F)?0<F?(Math.min(+Math.floor(F/4294967296),4294967295)|0)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)];y[b+88>>2]=G[0];y[b+92>>2]=
G[1];z[b+96>>2]=m%1E3*1E3;G=[d.ino>>>0,(F=d.ino,1<=+Math.abs(F)?0<F?(Math.min(+Math.floor(F/4294967296),4294967295)|0)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)];y[b+104>>2]=G[0];y[b+108>>2]=G[1];e=0}return e}catch(n){if("undefined"==typeof sc||"ErrnoError"!==n.name)throw n;return-n.le}},$a:function(a,b,c){try{return b=l(b),b=tc(a,b),0===c?$b(b):512===c?Zb(b):Fa("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof sc||"ErrnoError"!==d.name)throw d;return-d.le}},gb:function(){return!0},
Wa:function(){throw Infinity;},Oc:function(){Fa("")},Oa:function(a){if(12448==a)return N=12288,1;N=12300;return 0},Sa:function(a,b,c,d,e){if(62E3!=a)N=12296,c=0;else{if(b)for(;;){a=y[b>>2];if(12321==a)O.alpha=0<y[b+4>>2];else if(12325==a)O.depth=0<y[b+4>>2];else if(12326==a)O.stencil=0<y[b+4>>2];else if(12337==a)a=y[b+4>>2],O.antialias=0<a;else if(12338==a)a=y[b+4>>2],O.antialias=1==a;else if(12544==a)O.dg=12547!=y[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(y[e>>2]=1),c&&0<d&&(y[c>>2]=62002),
N=12288,c=1):(N=12300,c=0)}return c},Fa:function(a,b,c,d){if(62E3!=a)return N=12296,0;for(a=1;;){b=y[d>>2];if(12440==b)a=y[d+4>>2];else if(12344==b)break;else return N=12292,0;d+=8}if(2!=a)return N=12293,0;O.jf=a-1;O.eg=0;wd=ed(h.canvas,O);if(0!=wd)return N=12288,gd(wd),h.Uf=!0,Vc.forEach(function(e){e()}),gd(null),62004;N=12297;return 0},Ha:function(a,b){if(62E3!=a)return N=12296,0;if(62002!=b)return N=12293,0;N=12288;return 62006},Ga:function(a,b){if(62E3!=a)return N=12296,0;if(62004!=b)return N=
12294,0;a=wd;Nd===fd[a]&&(Nd=null);if("object"==typeof ee)for(var c=fd[a].re.canvas,d=0;d<Ud.length;++d)Ud[d].target!=c||Vd(d--);fd[a]&&fd[a].re.canvas&&(fd[a].re.canvas.ze=void 0);fd[a]=null;N=12288;sd==b&&(sd=0);return 1},Ia:function(a,b){if(62E3!=a)return N=12296,0;if(62006!=b)return N=12301,1;td==b&&(td=0);ud==b&&(ud=0);N=12288;return 1},Xa:function(a,b,c,d){if(62E3!=a)return N=12296,0;if(62002!=b)return N=12293,0;if(!d)return N=12300,0;N=12288;switch(c){case 12320:return y[d>>2]=O.alpha?32:24,
1;case 12321:return y[d>>2]=O.alpha?8:0,1;case 12322:return y[d>>2]=8,1;case 12323:return y[d>>2]=8,1;case 12324:return y[d>>2]=8,1;case 12325:return y[d>>2]=O.depth?24:0,1;case 12326:return y[d>>2]=O.stencil?8:0,1;case 12327:return y[d>>2]=12344,1;case 12328:return y[d>>2]=62002,1;case 12329:return y[d>>2]=0,1;case 12330:return y[d>>2]=4096,1;case 12331:return y[d>>2]=16777216,1;case 12332:return y[d>>2]=4096,1;case 12333:return y[d>>2]=0,1;case 12334:return y[d>>2]=0,1;case 12335:return y[d>>2]=
12344,1;case 12337:return y[d>>2]=O.antialias?4:0,1;case 12338:return y[d>>2]=O.antialias?1:0,1;case 12339:return y[d>>2]=4,1;case 12340:return y[d>>2]=12344,1;case 12341:case 12342:case 12343:return y[d>>2]=-1,1;case 12345:case 12346:return y[d>>2]=0,1;case 12347:return y[d>>2]=0,1;case 12348:return y[d>>2]=1;case 12349:case 12350:return y[d>>2]=0,1;case 12351:return y[d>>2]=12430,1;case 12352:return y[d>>2]=4,1;case 12354:return y[d>>2]=0,1;default:return N=12292,0}},L:function(){N=12288;return 62E3},
Da:function(){return N},Qa:function(a,b,c){if(62E3!=a)return N=12296,0;b&&(y[b>>2]=1);c&&(y[c>>2]=4);rd=!0;N=12288;return 1},Ja:function(a,b,c,d){if(62E3!=a)return N=12296,0;if(0!=d&&62004!=d)return N=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return N=12301,0;gd(d?wd:null);sd=d;ud=b;td=c;N=12288;return 1},Ca:function(a,b){if(62E3!=a)return N=12296,0;N=12288;if(vd[b])return vd[b];switch(b){case 12371:a=Od("Emscripten");break;case 12372:a=Od("1.4 Emscripten EGL");break;case 12373:a=Od("");break;case 12429:a=
Od("OpenGL_ES");break;default:return N=12300,0}return vd[b]=a},Ka:function(){if(rd)if(h.ne)if(h.ne.isContextLost())N=12302;else return N=12288,1;else N=12290;else N=12289;return 0},La:function(a,b){if(62E3!=a)return N=12296,0;0==b?xc(0,0):xc(1,b);N=12288;return 1},Ra:function(a){if(62E3!=a)return N=12296,0;ud=td=sd=0;rd=!1;N=12288;return 1},Na:function(){N=12288;return 1},Ma:function(){N=12288;return 1},T:function(a,b,c){b=Qd(b,c);return fb[a].apply(null,b)},b:function(a,b,c){b=Qd(b,c);return fb[a].apply(null,
b)},hb:function(){return Date.now()},xa:function(){if(!de())return-1;Yd(Ae);var a=se[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Aa:function(){Yd(Be);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},f:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},d:function(a,b,c){a=V(a);if(!a)return-4;a=ze(a);E[b>>3]=a.width;E[c>>3]=
a.height;return 0},R:function(a,b){if(0>a||a>=fe.length)return-5;if(!fe[a])return-7;Ce(b,fe[a]);return 0},Za:function(){return 2147483648},n:Ec,$b:function(){return fe.length},Pa:De,Ea:function(a,b,c){a=mf(a);return(a=Eb[a])?De(a.path,b,c):0},Ba:function(a,b){y[a>>2]=screen.width;y[b>>2]=screen.height},da:function(a){M.activeTexture(a)},ca:function(a,b){M.attachShader(P[a],Q[b])},ta:function(a,b){M.ke.beginQueryEXT(a,Gd[b])},ba:function(a,b,c){M.bindAttribLocation(P[a],b,l(c))},aa:function(a,b){M.bindBuffer(a,
Bd[b])},$:function(a,b){M.bindFramebuffer(a,Cd[b])},_:function(a,b){M.bindRenderbuffer(a,Dd[b])},Z:function(a,b){M.bindTexture(a,Ed[b])},la:function(a){M.bindVertexArray(Fd[a])},Y:function(a,b,c,d){M.blendColor(a,b,c,d)},X:function(a){M.blendEquation(a)},Md:function(a,b){M.blendEquationSeparate(a,b)},Ld:function(a,b){M.blendFunc(a,b)},Kd:function(a,b,c,d){M.blendFuncSeparate(a,b,c,d)},Jd:function(a,b,c,d){M.bufferData(a,c?r.subarray(c,c+b):b,d)},Id:function(a,b,c,d){M.bufferSubData(a,b,r.subarray(d,
d+c))},Hd:function(a){return M.checkFramebufferStatus(a)},Gd:function(a){M.clear(a)},Fd:function(a,b,c,d){M.clearColor(a,b,c,d)},Ed:function(a){M.clearDepth(a)},Dd:function(a){M.clearStencil(a)},Cd:function(a,b,c,d){M.colorMask(!!a,!!b,!!c,!!d)},Bd:function(a){M.compileShader(Q[a])},Ad:function(a,b,c,d,e,f,g,m){M.compressedTexImage2D(a,b,c,d,e,f,m?r.subarray(m,m+g):null)},zd:function(a,b,c,d,e,f,g,m,n){M.compressedTexSubImage2D(a,b,c,d,e,f,g,n?r.subarray(n,n+m):null)},yd:function(a,b,c,d,e,f,g,m){M.copyTexImage2D(a,
b,c,d,e,f,g,m)},xd:function(a,b,c,d,e,f,g,m){M.copyTexSubImage2D(a,b,c,d,e,f,g,m)},wd:function(){var a=Kd(P),b=M.createProgram();b.name=a;b.He=b.Fe=b.Ge=0;b.We=1;P[a]=b;return a},vd:function(a){var b=Kd(Q);Q[b]=M.createShader(a);return b},ud:function(a){M.cullFace(a)},td:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Bd[d];e&&(M.deleteBuffer(e),e.name=0,Bd[d]=null)}},sd:function(a,b){for(var c=0;c<a;++c){var d=y[b+4*c>>2],e=Cd[d];e&&(M.deleteFramebuffer(e),e.name=0,Cd[d]=null)}},rd:function(a){if(a){var b=
P[a];b?(M.deleteProgram(b),b.name=0,P[a]=null):R(1281)}},va:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Gd[d];e&&(M.ke.deleteQueryEXT(e),Gd[d]=null)}},qd:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Dd[d];e&&(M.deleteRenderbuffer(e),e.name=0,Dd[d]=null)}},pd:function(a){if(a){var b=Q[a];b?(M.deleteShader(b),Q[a]=null):R(1281)}},od:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Ed[d];e&&(M.deleteTexture(e),e.name=0,Ed[d]=null)}},ka:function(a,b){for(var c=0;c<a;c++){var d=
y[b+4*c>>2];M.deleteVertexArray(Fd[d]);Fd[d]=null}},nd:function(a){M.depthFunc(a)},md:function(a){M.depthMask(!!a)},ld:function(a,b){M.depthRange(a,b)},kd:function(a,b){M.detachShader(P[a],Q[b])},jd:function(a){M.disable(a)},hd:function(a){M.disableVertexAttribArray(a)},gd:function(a,b,c){M.drawArrays(a,b,c)},ga:function(a,b,c,d){M.drawArraysInstanced(a,b,c,d)},ha:function(a,b){for(var c=Ee[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];M.drawBuffers(c)},fd:function(a,b,c,d){M.drawElements(a,b,c,d)},fa:function(a,
b,c,d,e){M.drawElementsInstanced(a,b,c,d,e)},ed:function(a){M.enable(a)},dd:function(a){M.enableVertexAttribArray(a)},sa:function(a){M.ke.endQueryEXT(a)},cd:function(){M.finish()},bd:function(){M.flush()},ad:function(a,b,c,d){M.framebufferRenderbuffer(a,b,c,Dd[d])},$c:function(a,b,c,d,e){M.framebufferTexture2D(a,b,c,Ed[d],e)},_c:function(a){M.frontFace(a)},Yc:function(a,b){Fe(a,b,"createBuffer",Bd)},Wc:function(a,b){Fe(a,b,"createFramebuffer",Cd)},wa:function(a,b){for(var c=0;c<a;c++){var d=M.ke.createQueryEXT();
if(!d){for(R(1282);c<a;)y[b+4*c++>>2]=0;break}var e=Kd(Gd);d.name=e;Gd[e]=d;y[b+4*c>>2]=e}},Vc:function(a,b){Fe(a,b,"createRenderbuffer",Dd)},Uc:function(a,b){Fe(a,b,"createTexture",Ed)},ja:function(a,b){Fe(a,b,"createVertexArray",Fd)},Xc:function(a){M.generateMipmap(a)},Tc:function(a,b,c,d,e,f,g){Ge("getActiveAttrib",a,b,c,d,e,f,g)},Sc:function(a,b,c,d,e,f,g){Ge("getActiveUniform",a,b,c,d,e,f,g)},Rc:function(a,b,c,d){a=M.getAttachedShaders(P[a]);var e=a.length;e>b&&(e=b);y[c>>2]=e;for(b=0;b<e;++b)y[d+
4*b>>2]=Q.indexOf(a[b])},Qc:function(a,b){return M.getAttribLocation(P[a],l(b))},Pc:function(a,b){Ie(a,b,4)},Nc:function(a,b,c){c?y[c>>2]=M.getBufferParameter(a,b):R(1281)},Mc:function(){var a=M.getError()||Jd;Jd=0;return a},Lc:function(a,b){Ie(a,b,2)},Kc:function(a,b,c,d){a=M.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;y[d>>2]=a},Jc:function(a,b){Ie(a,b,0)},Hc:function(a,b,c,d){a=M.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");
b=0<b&&d?w(a,d,b):0;c&&(y[c>>2]=b)},Ic:function(a,b,c){if(c)if(a>=Ad)R(1281);else if(a=P[a],35716==b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.He)for(b=0;b<M.getProgramParameter(a,35718);++b)a.He=Math.max(a.He,M.getActiveUniform(a,b).name.length+1);y[c>>2]=a.He}else if(35722==b){if(!a.Fe)for(b=0;b<M.getProgramParameter(a,35721);++b)a.Fe=Math.max(a.Fe,M.getActiveAttrib(a,b).name.length+1);y[c>>2]=a.Fe}else if(35381==b){if(!a.Ge)for(b=0;b<M.getProgramParameter(a,
35382);++b)a.Ge=Math.max(a.Ge,M.getActiveUniformBlockName(a,b).length+1);y[c>>2]=a.Ge}else y[c>>2]=M.getProgramParameter(a,b);else R(1281)},na:function(a,b,c){if(c){a=M.ke.getQueryObjectEXT(Gd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;He(c,d)}else R(1281)},pa:function(a,b,c){if(c){a=M.ke.getQueryObjectEXT(Gd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;y[c>>2]=d}else R(1281)},ma:function(a,b,c){if(c){a=M.ke.getQueryObjectEXT(Gd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;He(c,d)}else R(1281)},oa:function(a,
b,c){if(c){a=M.ke.getQueryObjectEXT(Gd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;y[c>>2]=d}else R(1281)},qa:function(a,b,c){c?y[c>>2]=M.ke.getQueryEXT(a,b):R(1281)},Gc:function(a,b,c){c?y[c>>2]=M.getRenderbufferParameter(a,b):R(1281)},Ec:function(a,b,c,d){a=M.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?w(a,d,b):0;c&&(y[c>>2]=b)},Dc:function(a,b,c,d){a=M.getShaderPrecisionFormat(a,b);y[c>>2]=a.rangeMin;y[c+4>>2]=a.rangeMax;y[d>>2]=a.precision},Cc:function(a,b,c,d){if(a=M.getShaderSource(Q[a]))b=
0<b&&d?w(a,d,b):0,c&&(y[c>>2]=b)},Fc:function(a,b,c){c?35716==b?(a=M.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=M.getShaderSource(Q[a]),y[c>>2]=a?a.length+1:0):y[c>>2]=M.getShaderParameter(Q[a],b):R(1281)},Bc:function(a){var b=Hd[a];if(!b){switch(a){case 7939:b=M.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Je(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=M.getParameter(a))||R(1280);b=b&&Je(b);break;
case 7938:b=Je("OpenGL ES 2.0 ("+M.getParameter(7938)+")");break;case 35724:b=M.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Je(b);break;default:R(1280)}Hd[a]=b}return b},Ac:function(a,b,c){c?B[c>>2]=M.getTexParameter(a,b):R(1281)},zc:function(a,b,c){c?y[c>>2]=M.getTexParameter(a,b):R(1281)},wc:function(a,b){b=l(b);if(a=P[a]){Le(a);var c=a.Ce,d=0,e=b,f=Ke(b);0<f&&(d=parseInt(b.slice(f+
1))>>>0,e=b.slice(0,f));if((e=a.sf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else R(1281);return-1},yc:function(a,b,c){Me(a,b,c,2)},xc:function(a,b,c){Me(a,b,c,0)},tc:function(a,b,c){c?y[c>>2]=M.getVertexAttribOffset(a,b):R(1281)},vc:function(a,b,c){Ne(a,b,c,2)},uc:function(a,b,c){Ne(a,b,c,5)},sc:function(a,b){M.hint(a,b)},rc:function(a){return(a=Bd[a])?M.isBuffer(a):0},qc:function(a){return M.isEnabled(a)},pc:function(a){return(a=Cd[a])?M.isFramebuffer(a):0},oc:function(a){return(a=
P[a])?M.isProgram(a):0},ua:function(a){return(a=Gd[a])?M.ke.isQueryEXT(a):0},nc:function(a){return(a=Dd[a])?M.isRenderbuffer(a):0},mc:function(a){return(a=Q[a])?M.isShader(a):0},lc:function(a){return(a=Ed[a])?M.isTexture(a):0},ia:function(a){return(a=Fd[a])?M.isVertexArray(a):0},kc:function(a){M.lineWidth(a)},jc:function(a){a=P[a];M.linkProgram(a);a.Ce=0;a.sf={}},ic:function(a,b){3317==a&&(Id=b);M.pixelStorei(a,b)},hc:function(a,b){M.polygonOffset(a,b)},ra:function(a,b){M.ke.queryCounterEXT(Gd[a],
b)},gc:function(a,b,c,d,e,f,g){(g=Oe(f,e,c,d,g))?M.readPixels(a,b,c,d,e,f,g):R(1280)},fc:function(){},ec:function(a,b,c,d){M.renderbufferStorage(a,b,c,d)},dc:function(a,b){M.sampleCoverage(a,!!b)},cc:function(a,b,c,d){M.scissor(a,b,c,d)},bc:function(){R(1280)},ac:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?y[d+4*f>>2]:-1;e+=l(y[c+4*f>>2],0>g?void 0:g)}M.shaderSource(Q[a],e)},_b:function(a,b,c){M.stencilFunc(a,b,c)},Zb:function(a,b,c,d){M.stencilFuncSeparate(a,b,c,d)},Yb:function(a){M.stencilMask(a)},
Xb:function(a,b){M.stencilMaskSeparate(a,b)},Wb:function(a,b,c){M.stencilOp(a,b,c)},Vb:function(a,b,c,d){M.stencilOpSeparate(a,b,c,d)},Ub:function(a,b,c,d,e,f,g,m,n){M.texImage2D(a,b,c,d,e,f,g,m,n?Oe(m,g,d,e,n):null)},Tb:function(a,b,c){M.texParameterf(a,b,c)},Sb:function(a,b,c){M.texParameterf(a,b,B[c>>2])},Rb:function(a,b,c){M.texParameteri(a,b,c)},Pb:function(a,b,c){M.texParameteri(a,b,y[c>>2])},Ob:function(a,b,c,d,e,f,g,m,n){var p=null;n&&(p=Oe(m,g,e,f,n));M.texSubImage2D(a,b,c,d,e,f,g,m,p)},
Nb:function(a,b){M.uniform1f(W(a),b)},Mb:function(a,b,c){if(288>=b)for(var d=Pe[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);M.uniform1fv(W(a),d)},Lb:function(a,b){M.uniform1i(W(a),b)},Kb:function(a,b,c){if(288>=b)for(var d=Qe[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);M.uniform1iv(W(a),d)},Jb:function(a,b,c){M.uniform2f(W(a),b,c)},Ib:function(a,b,c){if(144>=b)for(var d=Pe[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>
2,c+8*b>>2);M.uniform2fv(W(a),d)},Hb:function(a,b,c){M.uniform2i(W(a),b,c)},Gb:function(a,b,c){if(144>=b)for(var d=Qe[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);M.uniform2iv(W(a),d)},Fb:function(a,b,c,d){M.uniform3f(W(a),b,c,d)},Eb:function(a,b,c){if(96>=b)for(var d=Pe[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);M.uniform3fv(W(a),d)},Db:function(a,b,c,d){M.uniform3i(W(a),
b,c,d)},Cb:function(a,b,c){if(96>=b)for(var d=Qe[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);M.uniform3iv(W(a),d)},Bb:function(a,b,c,d,e){M.uniform4f(W(a),b,c,d,e)},Ab:function(a,b,c){if(72>=b){var d=Pe[4*b-1],e=B;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=B.subarray(c>>2,c+16*b>>2);M.uniform4fv(W(a),d)},zb:function(a,b,c,d,e){M.uniform4i(W(a),b,c,d,e)},yb:function(a,
b,c){if(72>=b)for(var d=Qe[4*b-1],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=y.subarray(c>>2,c+16*b>>2);M.uniform4iv(W(a),d)},xb:function(a,b,c,d){if(72>=b)for(var e=Pe[4*b-1],f=0;f<4*b;f+=4)e[f]=B[d+4*f>>2],e[f+1]=B[d+(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2];else e=B.subarray(d>>2,d+16*b>>2);M.uniformMatrix2fv(W(a),!!c,e)},wb:function(a,b,c,d){if(32>=b)for(var e=Pe[9*b-1],f=0;f<9*b;f+=9)e[f]=B[d+4*f>>2],e[f+1]=B[d+
(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2],e[f+4]=B[d+(4*f+16)>>2],e[f+5]=B[d+(4*f+20)>>2],e[f+6]=B[d+(4*f+24)>>2],e[f+7]=B[d+(4*f+28)>>2],e[f+8]=B[d+(4*f+32)>>2];else e=B.subarray(d>>2,d+36*b>>2);M.uniformMatrix3fv(W(a),!!c,e)},vb:function(a,b,c,d){if(18>=b){var e=Pe[16*b-1],f=B;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+
11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=B.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(W(a),!!c,e)},ub:function(a){a=P[a];M.useProgram(a);M.yf=a},tb:function(a){M.validateProgram(P[a])},sb:function(a,b){M.vertexAttrib1f(a,b)},rb:function(a,b){M.vertexAttrib1f(a,B[b>>2])},qb:function(a,b,c){M.vertexAttrib2f(a,b,c)},pb:function(a,b){M.vertexAttrib2f(a,B[b>>2],B[b+4>>2])},ob:function(a,b,c,d){M.vertexAttrib3f(a,b,c,d)},nb:function(a,b){M.vertexAttrib3f(a,B[b>>2],B[b+
4>>2],B[b+8>>2])},mb:function(a,b,c,d,e){M.vertexAttrib4f(a,b,c,d,e)},lb:function(a,b){M.vertexAttrib4f(a,B[b>>2],B[b+4>>2],B[b+8>>2],B[b+12>>2])},ea:function(a,b){M.vertexAttribDivisor(a,b)},kb:function(a,b,c,d,e,f){M.vertexAttribPointer(a,b,c,!!d,e,f)},jb:function(a,b,c,d){M.viewport(a,b,c,d)},o:function(){return 0},ib:function(a,b,c){r.copyWithin(a,b,b+c)},ya:function(a,b,c){return Re(a,{Ue:y[c>>2],Me:y[c+4>>2],Ff:y[c+8>>2],Cf:b,De:y[c+12>>2],$e:y[c+16>>2]})},K:function(a,b){a=V(a);return a?a.requestPointerLock?
Sd&&$d.te?Be(a):b?(Xd(Be,2,[a]),1):-2:-1:-4},Ya:function(a){var b=r.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,f=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var g=va.buffer;try{va.grow(f.call(e,2147483648,d)-g.byteLength+65535>>>16);Da();var m=1;break a}catch(n){}m=void 0}if(m)return!0}return!1},S:function(){return(fe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():
null)?0:-1},q:function(a,b,c){if("undefined"==typeof onbeforeunload)return-1;if(1!==c)return-5;Se(a,b);return 0},C:function(a,b,c,d){Te(a,b,c,d,12,"blur");return 0},e:ve,l:function(a,b,c){a=V(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},D:function(a,b,c,d){Te(a,b,c,d,13,"focus");return 0},t:function(a,b,c,d){if(!de())return-1;a=V(a);if(!a)return-4;Ue(a,b,c,d,"fullscreenchange");Ue(a,b,c,d,"webkitfullscreenchange");return 0},Q:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;
Ve(a,b,c,26,"gamepadconnected");return 0},P:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Ve(a,b,c,27,"gamepaddisconnected");return 0},w:function(a,b,c,d){We(a,b,c,d,2,"keydown");return 0},u:function(a,b,c,d){We(a,b,c,d,1,"keypress");return 0},v:function(a,b,c,d){We(a,b,c,d,3,"keyup");return 0},Qb:function(a,b,c){a=I(a);Hc(a,b,c)},I:function(a,b,c,d){Ye(a,b,c,d,5,"mousedown");return 0},G:function(a,b,c,d){Ye(a,b,c,d,33,"mouseenter");return 0},F:function(a,b,c,d){Ye(a,
b,c,d,34,"mouseleave");return 0},J:function(a,b,c,d){Ye(a,b,c,d,8,"mousemove");return 0},H:function(a,b,c,d){Ye(a,b,c,d,6,"mouseup");return 0},x:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.de||document.body.Le||document.body.Ae))return-1;a=V(a);if(!a)return-4;Ze(a,b,c,d,"pointerlockchange");Ze(a,b,c,d,"mozpointerlockchange");Ze(a,b,c,d,"webkitpointerlockchange");Ze(a,b,c,d,"mspointerlockchange");return 0},s:function(a,b,c,d){$e(a,b,c,d);return 0},
y:function(a,b,c,d){af(a,b,c,d,25,"touchcancel");return 0},A:function(a,b,c,d){af(a,b,c,d,23,"touchend");return 0},z:function(a,b,c,d){af(a,b,c,d,24,"touchmove");return 0},B:function(a,b,c,d){af(a,b,c,d,22,"touchstart");return 0},r:function(a,b,c){if(!se[1])return-4;bf(a,b,c);return 0},E:function(a,b,c,d){a=V(a);return"undefined"!=typeof a.onwheel?(cf(a,b,c,d),0):-1},za:function(a){pa(l(a))},m:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},ab:function(a,b){var c=0;ef().forEach(function(d,e){var f=b+c;e=z[a+4*e>>2]=f;for(f=0;f<d.length;++f)x[e++>>0]=d.charCodeAt(f);x[e>>0]=0;c+=d.length+1});return 0},bb:function(a,b){var c=ef();z[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});z[b>>2]=d;return 0},p:gf,O:function(a){try{var b=uc(a);dc(b);return 0}catch(c){if("undefined"==typeof sc||"ErrnoError"!==c.name)throw c;return c.le}},db:function(a,b,c,d){try{a:{var e=uc(a);a=b;for(var f,g=b=0;g<c;g++){var m=z[a>>2],n=z[a+4>>2];
a+=8;var p=e,u=m,q=n,t=f,v=x;if(0>q||0>t)throw new J(28);if(null===p.fd)throw new J(8);if(1===(p.flags&2097155))throw new J(8);if(16384===(p.node.mode&61440))throw new J(31);if(!p.be.read)throw new J(28);var A="undefined"!=typeof t;if(!A)t=p.position;else if(!p.seekable)throw new J(70);var C=p.be.read(p,v,u,q,t);A||(p.position+=C);var D=C;if(0>D){var S=-1;break a}b+=D;if(D<n)break;"undefined"!==typeof f&&(f+=D)}S=b}z[d>>2]=S;return 0}catch(da){if("undefined"==typeof sc||"ErrnoError"!==da.name)throw da;
return da.le}},Ta:function(a,b,c,d,e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var f=uc(a);ec(f,b,d);G=[f.position>>>0,(F=f.position,1<=+Math.abs(F)?0<F?(Math.min(+Math.floor(F/4294967296),4294967295)|0)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)];y[e>>2]=G[0];y[e+4>>2]=G[1];f.Pe&&0===b&&0===d&&(f.Pe=null);return 0}catch(g){if("undefined"==typeof sc||"ErrnoError"!==g.name)throw g;return g.le}},M:function(a,b,c,d){try{a:{var e=uc(a);a=b;for(var f,g=b=0;g<
c;g++){var m=z[a>>2],n=z[a+4>>2];a+=8;var p=fc(e,x,m,n,f);if(0>p){var u=-1;break a}b+=p;"undefined"!==typeof f&&(f+=p)}u=b}z[d>>2]=u;return 0}catch(q){if("undefined"==typeof sc||"ErrnoError"!==q.name)throw q;return q.le}},k:nf,g:of,h:pf,j:qf,id:rf,Zc:sf,U:tf,Va:uf,Ua:vf,c:wf,i:xf,V:yf,a:va};
(function(){function a(c){c=c.exports;h.asm=c;Za();Ga=h.asm.Qd;Ia.unshift(h.asm.Nd);Ra("wasm-instantiate");return c}var b={a:zf};Qa("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return k("Module.instantiateWasm callback failed with error: "+c),!1}Xa(b,function(c){a(c.instance)});return{}})();function H(){return(H=h.asm.Od).apply(null,arguments)}var Af=h._main=function(){return(Af=h._main=h.asm.Pd).apply(null,arguments)};
function lf(){return(lf=h.asm.Rd).apply(null,arguments)}function mf(){return(mf=h.asm.Sd).apply(null,arguments)}function wb(){return(wb=h.asm.Td).apply(null,arguments)}function Z(){return(Z=h.asm.Ud).apply(null,arguments)}function T(){return(T=h.asm.Vd).apply(null,arguments)}function U(){return(U=h.asm.Wd).apply(null,arguments)}function ue(){return(ue=h.asm.Xd).apply(null,arguments)}h.dynCall_iiji=function(){return(h.dynCall_iiji=h.asm.Yd).apply(null,arguments)};
var Bf=h.dynCall_ji=function(){return(Bf=h.dynCall_ji=h.asm.Zd).apply(null,arguments)},Cf=h.dynCall_jiji=function(){return(Cf=h.dynCall_jiji=h.asm._d).apply(null,arguments)};function nf(a,b){var c=T();try{return I(a)(b)}catch(d){U(c);if(d!==d+0)throw d;Z(1,0)}}function qf(a,b,c,d,e){var f=T();try{return I(a)(b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;Z(1,0)}}function pf(a,b,c,d){var e=T();try{return I(a)(b,c,d)}catch(f){U(e);if(f!==f+0)throw f;Z(1,0)}}
function wf(a,b){var c=T();try{I(a)(b)}catch(d){U(c);if(d!==d+0)throw d;Z(1,0)}}function of(a,b,c){var d=T();try{return I(a)(b,c)}catch(e){U(d);if(e!==e+0)throw e;Z(1,0)}}function yf(a,b,c,d){var e=T();try{I(a)(b,c,d)}catch(f){U(e);if(f!==f+0)throw f;Z(1,0)}}function xf(a,b,c){var d=T();try{I(a)(b,c)}catch(e){U(d);if(e!==e+0)throw e;Z(1,0)}}function tf(a,b,c,d,e,f,g,m,n,p){var u=T();try{return I(a)(b,c,d,e,f,g,m,n,p)}catch(q){U(u);if(q!==q+0)throw q;Z(1,0)}}
function rf(a,b,c,d,e,f){var g=T();try{return I(a)(b,c,d,e,f)}catch(m){U(g);if(m!==m+0)throw m;Z(1,0)}}function sf(a,b,c,d,e,f,g,m,n){var p=T();try{return I(a)(b,c,d,e,f,g,m,n)}catch(u){U(p);if(u!==u+0)throw u;Z(1,0)}}function uf(a,b){var c=T();try{return Bf(a,b)}catch(d){U(c);if(d!==d+0)throw d;Z(1,0)}}function vf(a,b,c,d,e){var f=T();try{return Cf(a,b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;Z(1,0)}}h.addRunDependency=Qa;h.removeRunDependency=Ra;h.FS_createPath=jc;h.FS_createDataFile=lc;
h.FS_createPreloadedFile=rc;h.FS_createLazyFile=pc;h.FS_createDevice=nc;h.FS_unlink=$b;h.allocate=$a;var Df;Pa=function Ef(){Df||Ff();Df||(Pa=Ef)};function Gf(a=[]){var b=Af;a.unshift(ca);var c=a.length,d=ue(4*(c+1)),e=d>>2;a.forEach(g=>{var m=y,n=e++,p=Aa(g)+1,u=ue(p);za(g,x,u,p);m[n]=u});y[e]=0;try{var f=b(c,d);gf(f,!0)}catch(g){Pc(g)}}
function Ff(){var a=ba;function b(){if(!Df&&(Df=!0,h.calledRun=!0,!wa)){h.noFSInit||hc||(hc=!0,gc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?nc("/dev","stdin",h.stdin):Yb("/dev/tty","/dev/stdin"),h.stdout?nc("/dev","stdout",null,h.stdout):Yb("/dev/tty","/dev/stdout"),h.stderr?nc("/dev","stderr",null,h.stderr):Yb("/dev/tty1","/dev/stderr"),cc("/dev/stdin",0),cc("/dev/stdout",1),cc("/dev/stderr",1));Hb=!1;hb(Ia);hb(Ja);if(h.onRuntimeInitialized)h.onRuntimeInitialized();Hf&&Gf(a);
if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();La.unshift(c)}hb(La)}}if(!(0<Na)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ma();hb(Ha);0<Na||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Hf=!0;
h.noInitialRun&&(Hf=!1);Ff();
