
var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.Oe||(h.Oe=0);h.Oe++;
(function(a){function b(n,r,p){var t=new XMLHttpRequest;t.open("GET",n,!0);t.responseType="arraybuffer";t.onprogress=function(u){var v=r;u.total&&(v=u.total);if(u.loaded){t.ge?h.we[n].loaded=u.loaded:(t.ge=!0,h.we||(h.we={}),h.we[n]={loaded:u.loaded,total:v});var z=v=u=0,C;for(C in h.we){var H=h.we[C];u+=H.total;v+=H.loaded;z++}u=Math.ceil(u*h.Oe/z);h.setStatus&&h.setStatus("Downloading data... ("+v+"/"+u+")")}else!h.we&&h.setStatus&&h.setStatus("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+
n);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)p(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function c(n){console.error("package error:",n)}function d(){function n(u,v,z){this.start=u;this.Be=v;this.audio=z}function r(u){if(!u)throw"Loading data file failed."+Error().stack;if(!(u instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);n.prototype.cf=u;u=a.files;for(var v=0;v<
u.length;++v)n.prototype.ge[u[v].filename].onload();h.removeRunDependency("datafile_wasm/basque.data")}h.FS_createPath("/","assets",!0,!0);h.FS_createPath("/assets","audio",!0,!0);h.FS_createPath("/assets","fonts",!0,!0);h.FS_createPath("/assets","images",!0,!0);h.FS_createPath("/assets","data",!0,!0);h.FS_createPath("/assets","icons",!0,!0);h.FS_createPath("/assets/icons","basque_logo.iconset",!0,!0);n.prototype={ge:{},open:function(u,v){this.name=v;this.ge[v]=this;h.addRunDependency("fp "+this.name)},
send:function(){},onload:function(){this.bf(this.cf.subarray(this.start,this.Be))},bf:function(u){h.FS_createDataFile(this.name,null,u,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.ge[this.name]=null}};for(var p=a.files,t=0;t<p.length;++t)(new n(p[t].start,p[t].end,p[t].audio)).open("GET",p[t].filename);h.addRunDependency("datafile_wasm/basque.data");h.sf||(h.sf={});h.sf["wasm/basque.data"]={$f:!1};m?(r(m),m=null):g=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=h.locateFile?h.locateFile("basque.data",""):"basque.data",f=a.remote_package_size,g=null,m=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;m||b(e,f,function(n){g?(g(n),g=null):m=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))})({files:[{filename:"/assets/audio/Basque_sample_music.ogg",start:0,end:4240906,audio:1},{filename:"/assets/fonts/backpacker_license.pdf",start:4240906,end:4547109,audio:0},{filename:"/assets/fonts/BPtypewrite.ttf",start:4547109,end:4626281,audio:0},
{filename:"/assets/images/basque_logo.png",start:4626281,end:4627756,audio:0},{filename:"/assets/images/character.png",start:4627756,end:4631736,audio:0},{filename:"/assets/images/basque_logo_scaled.png",start:4631736,end:4655600,audio:0},{filename:"/assets/images/basque_logo_scaled_v3.png",start:4655600,end:4679724,audio:0},{filename:"/assets/images/tiles_packed.png",start:4679724,end:4686754,audio:0},{filename:"/assets/images/basque_logo_scaled_v2.png",start:4686754,end:4710529,audio:0},{filename:"/assets/images/README.md",
start:4710529,end:4710715,audio:0},{filename:"/assets/data/map_layout_5.txt",start:4710715,end:4756069,audio:0},{filename:"/assets/data/map_layout_9.txt",start:4756069,end:4801423,audio:0},{filename:"/assets/data/map_layout_8.txt",start:4801423,end:4846777,audio:0},{filename:"/assets/data/map_layout_3.txt",start:4846777,end:4892131,audio:0},{filename:"/assets/data/map_layout_6.txt",start:4892131,end:4937485,audio:0},{filename:"/assets/data/map_layout.txt",start:4937485,end:4982839,audio:0},{filename:"/assets/data/map_layout_4.txt",
start:4982839,end:5028193,audio:0},{filename:"/assets/data/map_layout_7.txt",start:5028193,end:5073547,audio:0},{filename:"/assets/data/map_library.txt",start:5073547,end:5073840,audio:0},{filename:"/assets/data/map_layout_2.txt",start:5073840,end:5119194,audio:0},{filename:"/assets/data/map_layout_1.txt",start:5119194,end:5164548,audio:0},{filename:"/assets/data/map_layout_0.txt",start:5164548,end:5209902,audio:0},{filename:"/assets/data/map_attributes.txt",start:5209902,end:5212406,audio:0},{filename:"/assets/icons/basque_logo.icns",
start:5212406,end:5470133,audio:0},{filename:"/assets/icons/basque_logo.png",start:5470133,end:5480776,audio:0},{filename:"/assets/icons/basque_logo.ico",start:5480776,end:5583606,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_256x256@2x.png",start:5583606,end:5703977,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_64x64@2x.png",start:5703977,end:5723947,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_128x128@2x.png",start:5723947,end:5776335,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_64x64.png",
start:5776335,end:5784515,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_128x128.png",start:5784515,end:5804485,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_32x32@2x.png",start:5804485,end:5812665,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_512x512.png",start:5812665,end:5933036,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_16x16@2x.png",start:5933036,end:5937238,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_8x8@2x.png",start:5937238,
end:5940145,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_16x16.png",start:5940145,end:5943052,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_512x512@2x.png",start:5943052,end:6170841,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_32x32.png",start:6170841,end:6175043,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_256x256.png",start:6175043,end:6227431,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_1024x1024.png",start:6227431,end:6455220,
audio:0}],remote_package_size:6455220,package_uuid:"5683d5d9-dca7-4e31-85d3-8797af2bb979"});var aa={},ba;for(ba in h)h.hasOwnProperty(ba)&&(aa[ba]=h[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var ka="";function la(a){return h.locateFile?h.locateFile(a,ka):ka+a}
var ma,na,oa,pa,qa,ra;
if(ia){if(ka=ha?require("path").dirname(ka)+"/":__dirname+"/",ma=function(a,b){qa||(qa=require("fs"));ra||(ra=require("path"));a=ra.normalize(a);return qa.readFileSync(a,b?null:"utf8")},oa=function(a){a=ma(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof ta))throw a;}),process.on("unhandledRejection",
l),ea=function(a){process.exit(a)},h.inspect=function(){return"[Emscripten Module object]"},"undefined"===typeof WebAssembly){var fs=require("fs");eval(fs.readFileSync(la("basque.wasm.js"))+"")}}else if(ja)"undefined"!=typeof read&&(ma=function(a){return read(a)}),oa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===
typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print),"undefined"===typeof WebAssembly&&eval(read(la("basque.wasm.js")));else if(fa||ha)ha?ka=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ka=document.currentScript.src),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.lastIndexOf("/")+1):"",ma=function(a){var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(oa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),na=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},pa=function(a){document.title=a};var ua=h.print||console.log.bind(console),k=h.printErr||console.warn.bind(console);
for(ba in aa)aa.hasOwnProperty(ba)&&(h[ba]=aa[ba]);aa=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);function va(a){wa||(wa={});wa[a]||(wa[a]=1,k(a))}var wa,xa=0,ya;h.wasmBinary&&(ya=h.wasmBinary);var noExitRuntime;h.noExitRuntime&&(noExitRuntime=h.noExitRuntime);
function za(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":q[a>>0]=b;break;case "i8":q[a>>0]=b;break;case "i16":Aa[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":x=[b>>>0,(y=b,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[a>>2]=x[0];w[a+4>>2]=x[1];break;case "float":A[a>>2]=b;break;case "double":Ca[a>>3]=b;break;default:l("invalid type for setValue: "+c)}}var Da,Ea=!1;
function assert(a,b){a||l("Assertion failed: "+b)}var Fa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ga(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Fa)return Fa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function B(a,b){return a?Ga(D,a,b):""}
function Ha(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function E(a,b,c){return Ha(a,D,b,c)}
function Ia(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ja(a){var b=Ia(a)+1,c=F(b);c&&Ha(a,q,c,b);return c}function Ka(a){var b=Ia(a)+1,c=La(b);Ha(a,q,c,b);return c}var Ma,q,D,Aa,Na,w,Oa,A,Ca;
function Pa(a){Ma=a;h.HEAP8=q=new Int8Array(a);h.HEAP16=Aa=new Int16Array(a);h.HEAP32=w=new Int32Array(a);h.HEAPU8=D=new Uint8Array(a);h.HEAPU16=Na=new Uint16Array(a);h.HEAPU32=Oa=new Uint32Array(a);h.HEAPF32=A=new Float32Array(a);h.HEAPF64=Ca=new Float64Array(a)}var Qa=h.INITIAL_MEMORY||1073741824;h.wasmMemory?Da=h.wasmMemory:Da=new WebAssembly.Memory({initial:Qa/65536,maximum:32768});Da&&(Ma=Da.buffer);Qa=Ma.byteLength;Pa(Ma);var G,Ra=[],Sa=[],Ta=[],Ua=[],Va=[];
function Wa(){var a=h.preRun.shift();Ra.unshift(a)}var Xa=0,Ya=null,Za=null;function $a(){Xa++;h.monitorRunDependencies&&h.monitorRunDependencies(Xa)}function ab(){Xa--;h.monitorRunDependencies&&h.monitorRunDependencies(Xa);if(0==Xa&&(null!==Ya&&(clearInterval(Ya),Ya=null),Za)){var a=Za;Za=null;a()}}h.preloadedImages={};h.preloadedAudios={};function l(a){if(h.onAbort)h.onAbort(a);k(a);Ea=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}var bb="basque.html.mem";
function cb(a,b){return String.prototype.startsWith?a.startsWith(b):0===a.indexOf(b)}function db(a){return cb(a,"data:application/octet-stream;base64,")}var eb="basque.wasm";db(eb)||(eb=la(eb));function fb(){try{if(ya)return new Uint8Array(ya);if(oa)return oa(eb);throw"both async and sync fetching of the wasm failed";}catch(a){l(a)}}
function gb(){return ya||!fa&&!ha||"function"!==typeof fetch||cb(eb,"file://")?Promise.resolve().then(fb):fetch(eb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+eb+"'";return a.arrayBuffer()}).catch(function(){return fb()})}
var y,x,jb={116154:function(a){a=B(a)+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");a=hb(a);var b=F(a.length);a.subarray||a.slice?D.set(a,b):D.set(new Uint8Array(a),b);return b},153740:function(a,b,c){h.SDL2||(h.SDL2={});var d=h.SDL2;d.xf!==h.canvas&&(d.pe=h.createContext(h.canvas,!1,!0),d.xf=h.canvas);if(d.w!==a||d.Ef!==b||d.Gf!==d.pe)d.image=d.pe.createImageData(a,b),d.w=a,d.Ef=b,d.Gf=d.pe;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&
a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=w[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Yf!==a&&(d.yf=new Int32Array(a.buffer),d.zf=new Uint8Array(a.buffer)),a=d.yf,c=a.length,a.set(w.subarray(b,b+c)),a=d.zf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.pe.putImageData(d.image,0,0);return 0},155219:function(a,
b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=w[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>16&255;b[m+3]=r>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(w.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=F(c.length+
1);E(c,d,c.length+1);return d},156208:function(a){h.canvas&&(h.canvas.style.cursor=B(a));return 0},156301:function(){h.canvas&&(h.canvas.style.cursor="none")},157526:function(){return screen.width},157553:function(){return screen.height},157581:function(){return window.innerWidth},157613:function(){return window.innerHeight},157691:function(a){"undefined"!==typeof pa&&pa(B(a));return 0},157825:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},157991:function(){return"undefined"!==
typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},158217:function(a){"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.fe||("undefined"!==typeof AudioContext?b.fe=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.fe=new webkitAudioContext),b.fe&&ib(b.fe));return void 0===b.fe?-1:0},158770:function(){return h.SDL2.fe.sampleRate},158840:function(a,b,c,d){function e(){}
function f(m){void 0!==g.capture.Ee&&(clearTimeout(g.capture.Ee),g.capture.Ee=void 0);g.capture.Ie=g.fe.createMediaStreamSource(m);g.capture.je=g.fe.createScriptProcessor(b,a,1);g.capture.je.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Ne=n.inputBuffer,n=[d],G.get(c).apply(null,n))};g.capture.Ie.connect(g.capture.je);g.capture.je.connect(g.fe.destination);g.capture.stream=m}var g=h.SDL2;g.capture.Le=g.fe.createBuffer(a,b,g.fe.sampleRate);
g.capture.Le.getChannelData(0).fill(0);g.capture.Ee=setTimeout(function(){g.capture.Ne=g.capture.Le;var m=[d];G.get(c).apply(null,m)},b/g.fe.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},160492:function(a,b,c,d){var e=h.SDL2;e.audio.je=e.fe.createScriptProcessor(b,0,a);e.audio.je.onaudioprocess=
function(f){void 0!==e&&void 0!==e.audio&&(e.audio.af=f.outputBuffer,f=[d],G.get(c).apply(null,f))};e.audio.je.connect(e.fe.destination)},160902:function(a,b){for(var c=h.SDL2,d=c.capture.Ne.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ne.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)za(a+4*g,f[g]);else for(g=0;g<b;++g)za(a+4*(g*d+e),f[g])}},161507:function(a,b){for(var c=
h.SDL2,d=c.audio.af.numberOfChannels,e=0;e<d;++e){var f=c.audio.af.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=A[a+(g*d+e<<2)>>2]}},161987:function(a){var b=h.SDL2;if(a){void 0!==b.capture.Ee&&clearTimeout(b.capture.Ee);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==
b.capture.je&&(b.capture.je.onaudioprocess=function(){},b.capture.je.disconnect(),b.capture.je=void 0);void 0!==b.capture.Ie&&(b.capture.Ie.disconnect(),b.capture.Ie=void 0);void 0!==b.capture.Le&&(b.capture.Le=void 0);b.capture=void 0}else void 0!=b.audio.je&&(b.audio.je.disconnect(),b.audio.je=void 0),b.audio=void 0;void 0!==b.fe&&void 0===b.audio&&void 0===b.capture&&(b.fe.close(),b.fe=void 0)}};function kb(a,b,c){a.addEventListener(b,c,{once:!0})}
function ib(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&kb(d,c,function(){"suspended"===a.state&&a.resume()})})})}function lb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.ff;"number"===typeof c?void 0===b.Fe?G.get(c)():G.get(c)(b.Fe):c(void 0===b.Fe?null:b.Fe)}}}function mb(){w[nb()>>2]=28}
function ob(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function pb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ob(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function qb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function rb(a){if("/"===a)return"/";a=pb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function sb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){l("randomDevice")}}
function tb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ob(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var ub=[];function vb(a,b){ub[a]={input:[],output:[],ze:b};wb(a,xb)}
var xb={open:function(a){var b=ub[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ze.flush(a.tty)},flush:function(a){a.tty.ze.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ze.gf)throw new I(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.ze.gf(a.tty)}catch(m){throw new I(29);}if(void 0===g&&0===e)throw new I(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.ze.Se)throw new I(60);
try{for(var e=0;e<d;e++)a.tty.ze.Se(a.tty,b[c+e])}catch(f){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},yb={gf:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.ge?Buffer.ge(256):new Buffer(256),d=0;try{d=qa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=hb(b,!0)}return a.input.shift()},Se:function(a,b){null===b||10===b?(ua(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ua(Ga(a.output,0)),a.output=[])}},zb={Se:function(a,b){null===b||10===b?(k(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(Ga(a.output,0)),a.output=[])}},J={re:null,se:function(){return J.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);J.re||(J.re={dir:{node:{qe:J.ce.qe,ke:J.ce.ke,lookup:J.ce.lookup,Je:J.ce.Je,rename:J.ce.rename,unlink:J.ce.unlink,rmdir:J.ce.rmdir,readdir:J.ce.readdir,symlink:J.ce.symlink},stream:{ve:J.de.ve}},file:{node:{qe:J.ce.qe,ke:J.ce.ke},stream:{ve:J.de.ve,read:J.de.read,write:J.de.write,We:J.de.We,mf:J.de.mf,pf:J.de.pf}},link:{node:{qe:J.ce.qe,ke:J.ce.ke,readlink:J.ce.readlink},stream:{}},$e:{node:{qe:J.ce.qe,
ke:J.ce.ke},stream:Ab}});c=Bb(a,b,c,d);K(c.mode)?(c.ce=J.re.dir.node,c.de=J.re.dir.stream,c.be={}):32768===(c.mode&61440)?(c.ce=J.re.file.node,c.de=J.re.file.stream,c.ee=0,c.be=null):40960===(c.mode&61440)?(c.ce=J.re.link.node,c.de=J.re.link.stream):8192===(c.mode&61440)&&(c.ce=J.re.$e.node,c.de=J.re.$e.stream);c.timestamp=Date.now();a&&(a.be[b]=c);return c},ag:function(a){if(a.be&&a.be.subarray){for(var b=[],c=0;c<a.ee;++c)b.push(a.be[c]);return b}return a.be},bg:function(a){return a.be?a.be.subarray?
a.be.subarray(0,a.ee):new Uint8Array(a.be):new Uint8Array(0)},df:function(a,b){var c=a.be?a.be.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.be,a.be=new Uint8Array(b),0<a.ee&&a.be.set(c.subarray(0,a.ee),0))},Pf:function(a,b){if(a.ee!=b)if(0==b)a.be=null,a.ee=0;else{if(!a.be||a.be.subarray){var c=a.be;a.be=new Uint8Array(b);c&&a.be.set(c.subarray(0,Math.min(b,a.ee)))}else if(a.be||(a.be=[]),a.be.length>b)a.be.length=b;else for(;a.be.length<b;)a.be.push(0);a.ee=
b}},ce:{qe:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.ee:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.wf=4096;b.blocks=Math.ceil(b.size/b.wf);return b},ke:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&J.Pf(a,
b.size)},lookup:function(){throw Cb[44];},Je:function(a,b,c,d){return J.createNode(a,b,c,d)},rename:function(a,b,c){if(K(a.mode)){try{var d=Db(b,c)}catch(f){}if(d)for(var e in d.be)throw new I(55);}delete a.parent.be[a.name];a.name=c;b.be[c]=a;a.parent=b},unlink:function(a,b){delete a.be[b]},rmdir:function(a,b){var c=Db(a,b),d;for(d in c.be)throw new I(55);delete a.be[b]},readdir:function(a){var b=[".",".."],c;for(c in a.be)a.be.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=J.createNode(a,
b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},de:{read:function(a,b,c,d,e){var f=a.node.be;if(e>=a.node.ee)return 0;a=Math.min(a.node.ee-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===q.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.be||a.be.subarray)){if(f)return a.be=b.subarray(c,c+d),a.ee=d;if(0===a.ee&&0===e)return a.be=
b.slice(c,c+d),a.ee=d;if(e+d<=a.ee)return a.be.set(b.subarray(c,c+d),e),d}J.df(a,e+d);if(a.be.subarray&&b.subarray)a.be.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.be[e+f]=b[c+f];a.ee=Math.max(a.ee,e+d);return d},ve:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ee);if(0>b)throw new I(28);return b},We:function(a,b,c){J.df(a.node,b+c);a.node.ee=Math.max(a.node.ee,b+c)},mf:function(a,b,c,d,e,f){assert(0===b);if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.be;
if(f&2||a.buffer!==Ma){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=F(f);c<f;)q[b+c++]=0;c=b;if(!c)throw new I(48);q.set(a,c)}else d=!1,c=a.byteOffset;return{ig:c,Vf:d}},pf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);if(e&2)return 0;J.de.write(a,b,0,d,c,!1);return 0}}},Eb=null,Fb={},Gb=[],Hb=1,Ib=null,Jb=!0,L={},I=null,Cb={};
function Kb(a,b){a=tb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ef:!0,Te:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Te)throw new I(32);a=ob(a.split("/").filter(function(g){return!!g}),!1);var e=Eb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Db(e,a[d]);c=pb(c+"/"+a[d]);e.xe&&(!f||f&&b.ef)&&(e=e.xe.root);if(!f||b.He)for(f=0;40960===(e.mode&61440);)if(e=Lb(c),c=tb(qb(c),e),e=Kb(c,{Te:b.Te}).node,40<f++)throw new I(32);}return{path:c,node:e}}
function Mb(a){for(var b;;){if(a===a.parent)return a=a.se.nf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Nb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ib.length}function Ob(a){var b=Nb(a.parent.id,a.name);if(Ib[b]===a)Ib[b]=a.ye;else for(b=Ib[b];b;){if(b.ye===a){b.ye=a.ye;break}b=b.ye}}
function Db(a,b){var c;if(c=(c=Pb(a,"x"))?c:a.ce.lookup?0:2)throw new I(c,a);for(c=Ib[Nb(a.id,b)];c;c=c.ye){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ce.lookup(a,b)}function Bb(a,b,c,d){a=new Qb(a,b,c,d);b=Nb(a.parent.id,a.name);a.ye=Ib[b];return Ib[b]=a}function K(a){return 16384===(a&61440)}var Rb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Sb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Pb(a,b){if(Jb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Tb(a,b){try{return Db(a,b),20}catch(c){}return Pb(a,"wx")}function Ub(a,b,c){try{var d=Db(a,b)}catch(e){return e.ie}if(a=Pb(a,"wx"))return a;if(c){if(!K(d.mode))return 54;if(d===d.parent||"/"===Mb(d))return 10}else if(K(d.mode))return 31;return 0}
function Vb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Gb[a])return a;throw new I(33);}function Wb(a,b){Xb||(Xb=function(){},Xb.prototype={});var c=new Xb,d;for(d in a)c[d]=a[d];a=c;b=Vb(b);a.fd=b;return Gb[b]=a}var Ab={open:function(a){a.de=Fb[a.node.rdev].de;a.de.open&&a.de.open(a)},ve:function(){throw new I(70);}};function wb(a,b){Fb[a]={de:b}}
function Yb(a,b){var c="/"===b,d=!b;if(c&&Eb)throw new I(10);if(!c&&!d){var e=Kb(b,{ef:!1});b=e.path;e=e.node;if(e.xe)throw new I(10);if(!K(e.mode))throw new I(54);}b={type:a,hg:{},nf:b,Mf:[]};a=a.se(b);a.se=b;b.root=a;c?Eb=a:e&&(e.xe=b,e.se&&e.se.Mf.push(b))}function Zb(a,b,c){var d=Kb(a,{parent:!0}).node;a=rb(a);if(!a||"."===a||".."===a)throw new I(28);var e=Tb(d,a);if(e)throw new I(e);if(!d.ce.Je)throw new I(63);return d.ce.Je(d,a,b,c)}function $b(a){Zb(a,16895,0)}
function ac(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Zb(a,b|8192,c)}function bc(a,b){if(!tb(a))throw new I(44);var c=Kb(b,{parent:!0}).node;if(!c)throw new I(44);b=rb(b);var d=Tb(c,b);if(d)throw new I(d);if(!c.ce.symlink)throw new I(63);c.ce.symlink(c,b,a)}
function cc(a){var b=Kb(a,{parent:!0}).node,c=rb(a),d=Db(b,c),e=Ub(b,c,!1);if(e)throw new I(e);if(!b.ce.unlink)throw new I(63);if(d.xe)throw new I(10);try{L.willDeletePath&&L.willDeletePath(a)}catch(f){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.ce.unlink(b,c);Ob(d);try{if(L.onDeletePath)L.onDeletePath(a)}catch(f){k("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}}
function Lb(a){a=Kb(a).node;if(!a)throw new I(44);if(!a.ce.readlink)throw new I(28);return tb(Mb(a.parent),a.ce.readlink(a))}function dc(a,b){var c;"string"===typeof a?c=Kb(a,{He:!0}).node:c=a;if(!c.ce.ke)throw new I(63);c.ce.ke(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function ec(a,b,c,d){if(""===a)throw new I(44);if("string"===typeof b){var e=Rb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=pb(a);try{f=Kb(a,{He:!(b&131072)}).node}catch(m){}}e=!1;if(b&64)if(f){if(b&128)throw new I(20);}else f=Zb(a,c,0),e=!0;if(!f)throw new I(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!K(f.mode))throw new I(54);if(!e&&(c=f?40960===(f.mode&61440)?32:K(f.mode)&&
("r"!==Sb(b)||b&512)?31:Pb(f,Sb(b)):44))throw new I(c);if(b&512){c=f;var g;"string"===typeof c?g=Kb(c,{He:!0}).node:g=c;if(!g.ce.ke)throw new I(63);if(K(g.mode))throw new I(31);if(32768!==(g.mode&61440))throw new I(28);if(c=Pb(g,"w"))throw new I(c);g.ce.ke(g,{size:0,timestamp:Date.now()})}b&=-131713;d=Wb({node:f,path:Mb(f),flags:b,seekable:!0,position:0,de:f.de,Sf:[],error:!1},d);d.de.open&&d.de.open(d);!h.logReadFiles||b&1||(fc||(fc={}),a in fc||(fc[a]=1,k("FS.trackingDelegate error on read file: "+
a)));try{L.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),L.onOpenFile(a,f))}catch(m){k("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function hc(a){if(null===a.fd)throw new I(8);a.Pe&&(a.Pe=null);try{a.de.close&&a.de.close(a)}catch(b){throw b;}finally{Gb[a.fd]=null}a.fd=null}
function ic(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.de.ve)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.de.ve(a,b,c);a.Sf=[]}
function jc(a,b,c,d,e,f){if(0>d||0>e)throw new I(28);if(null===a.fd)throw new I(8);if(0===(a.flags&2097155))throw new I(8);if(K(a.node.mode))throw new I(31);if(!a.de.write)throw new I(28);a.seekable&&a.flags&1024&&ic(a,0,2);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new I(70);b=a.de.write(a,b,c,d,e,f);g||(a.position+=b);try{if(a.path&&L.onWriteToFile)L.onWriteToFile(a.path)}catch(m){k("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function kc(){I||(I=function(a,b){this.node=b;this.Qf=function(c){this.ie=c};this.Qf(a);this.message="FS error"},I.prototype=Error(),I.prototype.constructor=I,[44].forEach(function(a){Cb[a]=new I(a);Cb[a].stack="<generic error, no stack>"}))}var lc;function mc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function nc(a,b){a="string"===typeof a?a:Mb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=pb(a+"/"+c);try{$b(d)}catch(e){}a=d}}return d}
function oc(a,b,c,d){a=pb(("string"===typeof a?a:Mb(a))+"/"+b);c=mc(c,d);return Zb(a,(void 0!==c?c:438)&4095|32768,0)}function pc(a,b,c,d,e,f){a=b?pb(("string"===typeof a?a:Mb(a))+"/"+b):a;d=mc(d,e);e=Zb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var g=c.length;b<g;++b)a[b]=c.charCodeAt(b);c=a}dc(e,d|146);a=ec(e,577);jc(a,c,0,c.length,0,f);hc(a);dc(e,d)}return e}
function qc(a,b,c,d){a=pb(("string"===typeof a?a:Mb(a))+"/"+b);b=mc(!!c,!!d);qc.kf||(qc.kf=64);var e=qc.kf++<<8|0;wb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,g,m,n){for(var r=0,p=0;p<n;p++){try{var t=c()}catch(u){throw new I(29);}if(void 0===t&&0===r)throw new I(6);if(null===t||void 0===t)break;r++;g[m+p]=t}r&&(f.node.timestamp=Date.now());return r},write:function(f,g,m,n){for(var r=0;r<n;r++)try{d(g[m+r])}catch(p){throw new I(29);}n&&
(f.node.timestamp=Date.now());return r}});return ac(a,b,e)}function rc(a){if(!(a.Kf||a.Lf||a.link||a.be)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ma)try{a.be=hb(ma(a.url),!0),a.ee=a.be.length}catch(b){throw new I(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function sc(a,b,c,d,e){function f(){this.Qe=!1;this.ge=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var t=p%this.chunkSize;return this.hf(p/this.chunkSize|0)[t]}};f.prototype.Be=function(p){this.hf=p};f.prototype.Ye=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var t=Number(p.getResponseHeader("Content-length")),u,v=(u=p.getResponseHeader("Accept-Ranges"))&&
"bytes"===u;p=(u=p.getResponseHeader("Content-Encoding"))&&"gzip"===u;var z=1048576;v||(z=t);var C=this;C.Be(function(H){var Ba=H*z,sa=(H+1)*z-1;sa=Math.min(sa,t-1);if("undefined"===typeof C.ge[H]){var vc=C.ge;if(Ba>sa)throw Error("invalid range ("+Ba+", "+sa+") or no bytes requested!");if(sa>t-1)throw Error("only "+t+" bytes available! programmer error!");var O=new XMLHttpRequest;O.open("GET",c,!1);t!==z&&O.setRequestHeader("Range","bytes="+Ba+"-"+sa);"undefined"!=typeof Uint8Array&&(O.responseType=
"arraybuffer");O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);if(!(200<=O.status&&300>O.status||304===O.status))throw Error("Couldn't load "+c+". Status: "+O.status);Ba=void 0!==O.response?new Uint8Array(O.response||[]):hb(O.responseText||"",!0);vc[H]=Ba}if("undefined"===typeof C.ge[H])throw Error("doXHR failed!");return C.ge[H]});if(p||!t)z=t=1,z=t=this.hf(0).length,ua("LazyFiles on gzip forces download of the whole file when length is accessed");this.vf=
t;this.uf=z;this.Qe=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;Object.defineProperties(g,{length:{get:function(){this.Qe||this.Ye();return this.vf}},chunkSize:{get:function(){this.Qe||this.Ye();return this.uf}}});var m=void 0}else m=c,g=void 0;var n=oc(a,b,d,e);g?n.be=g:m&&(n.be=null,n.url=m);Object.defineProperties(n,{ee:{get:function(){return this.be.length}}});
var r={};Object.keys(n.de).forEach(function(p){var t=n.de[p];r[p]=function(){rc(n);return t.apply(null,arguments)}});r.read=function(p,t,u,v,z){rc(n);p=p.node.be;if(z>=p.length)return 0;v=Math.min(p.length-z,v);if(p.slice)for(var C=0;C<v;C++)t[u+C]=p[z+C];else for(C=0;C<v;C++)t[u+C]=p.get(z+C);return v};n.de=r;return n}
function tc(a,b,c,d,e,f,g,m,n,r){function p(v){function z(H){r&&r();m||pc(a,b,H,d,e,n);f&&f();ab(u)}var C=!1;h.preloadPlugins.forEach(function(H){!C&&H.canHandle(t)&&(H.handle(v,t,z,function(){g&&g();ab(u)}),C=!0)});C||z(v)}uc();var t=b?tb(pb(a+"/"+b)):a,u="cp "+t;$a(u);"string"==typeof c?wc(c,function(v){p(v)},g):p(c)}var M={},Xb,fc,xc=void 0;function yc(){xc+=4;return w[xc-4>>2]}function zc(a){a=Gb[a];if(!a)throw new I(8);return a}var Ac;
ia?Ac=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Ac=dateNow:Ac=function(){return performance.now()};
function Bc(a,b){Cc=a;Dc=b;if(Ec)if(0==a)Fc=function(){var d=Math.max(0,Gc+b-Ac())|0;setTimeout(Hc,d)};else if(1==a)Fc=function(){Ic(Hc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Fc=function(){setImmediate(Hc)}}}
function Jc(a,b,c,d,e){noExitRuntime=!0;assert(!Ec,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ec=a;Kc=d;var f=Lc;Hc=function(){if(!Ea)if(0<Mc.length){var g=Date.now(),m=Mc.shift();m.ff(m.Fe);if(Nc){var n=Nc,r=0==n%1?n-1:Math.floor(n);Nc=m.Xf?r:(8*n+(r+.5))/9}console.log('main loop blocker "'+m.name+'" took '+(Date.now()-g)+" ms");h.setStatus&&(g=h.statusMessage||
"Please wait...",m=Nc,n=Oc.Zf,m?m<n?h.setStatus(g+" ("+(n-m)+"/"+n+")"):h.setStatus(g):h.setStatus(""));f<Lc||setTimeout(Hc,0)}else if(!(f<Lc))if(Pc=Pc+1|0,1==Cc&&1<Dc&&0!=Pc%Dc)Fc();else{0==Cc&&(Gc=Ac());a:if(!(Ea||h.preMainLoop&&!1===h.preMainLoop())){try{a()}catch(p){if(p instanceof ta||"unwind"==p)break a;p&&"object"===typeof p&&p.stack&&k("exception thrown: "+[p,p.stack]);throw p;}h.postMainLoop&&h.postMainLoop()}f<Lc||("object"===typeof SDL&&SDL.audio&&SDL.audio.Of&&SDL.audio.Of(),Fc())}};e||
(b&&0<b?Bc(0,1E3/b):Bc(1,1),Fc());if(c)throw"unwind";}var Fc=null,Lc=0,Ec=null,Kc=0,Cc=0,Dc=0,Pc=0,Mc=[],Oc={},Gc,Hc,Nc,Qc=!1,Rc=!1,Sc=[];
function uc(){function a(){Rc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!Tc){Tc=!0;try{Uc=!0}catch(c){Uc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Vc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Uc?null:console.log("warning: no BlobBuilder");
Wc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.qf||"undefined"!==typeof Wc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.qf=!0);h.preloadPlugins.push({canHandle:function(c){return!h.qf&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(Uc)try{g=new Blob([c],{type:Xc(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Xc(d)}))}catch(r){va("Blob constructor present but fails: "+
r+"; falling back to blob builder")}g||(g=new Vc,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var m=Wc.createObjectURL(g),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=n.width;r.height=n.height;r.getContext("2d").drawImage(n,0,0);h.preloadedImages[d]=r;Wc.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");f&&f()};n.src=m}});h.preloadPlugins.push({canHandle:function(c){return!h.gg&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function g(t){n||(n=!0,h.preloadedAudios[d]=t,e&&e(c))}function m(){n||(n=!0,h.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(Uc){try{var r=new Blob([c],{type:Xc(d)})}catch(t){return m()}r=Wc.createObjectURL(r);var p=new Audio;p.addEventListener("canplaythrough",function(){g(p)},!1);p.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var t="",u=0,v=0,
z=0;z<c.length;z++)for(u=u<<8|c[z],v+=8;6<=v;){var C=u>>v-6&63;v-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[C]}2==v?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],t+="=="):4==v&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],t+="=");p.src="data:audio/x-"+d.substr(-3)+";base64,"+t;g(p)}};p.src=r;Yc(function(){g(p)})}else return m()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&
b.addEventListener("click",function(c){!Rc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Zc(a,b,c,d){if(b&&h.pe&&a==h.canvas)return h.pe;var e;if(b){var f={antialias:!1,alpha:!1,lf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!==typeof $c&&(e=ad(a,f)))var m=bd[e].te}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof N,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.pe=m,b&&cd(e),h.Tf=b,Sc.forEach(function(n){n()}),uc());return m}var dd=!1,ed=void 0,fd=void 0;
function gd(a,b){function c(){Qc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=hd,ed&&d.requestPointerLock(),Qc=!0,fd?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=Oa[SDL.screen>>2]|8388608),id(h.canvas),jd()):id(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),fd?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=Oa[SDL.screen>>2]&
-8388609),id(h.canvas),jd()):id(d));if(h.onFullScreen)h.onFullScreen(Qc);if(h.onFullscreen)h.onFullscreen(Qc)}ed=a;fd=b;"undefined"===typeof ed&&(ed=!0);"undefined"===typeof fd&&(fd=!1);var d=h.canvas;dd||(dd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function hd(){if(!Qc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var kd=0;function Ic(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===kd)kd=b+1E3/60;else for(;b+2>=kd;)kd+=1E3/60;setTimeout(a,Math.max(kd-b,0))}}function Yc(a){noExitRuntime=!0;setTimeout(function(){Ea||a()},1E4)}
function Xc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function wc(a,b,c){var d="al "+a;na(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&ab(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&$a(d)}var ld=[];function jd(){var a=h.canvas;ld.forEach(function(b){b(a.width,a.height)})}
function id(a,b,c){b&&c?(a.Uf=b,a.Ff=c):(b=a.Uf,c=a.Ff);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}fd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Tc,Uc,Vc,Wc,P=12288,md=!1,nd=0,od=0,pd=0,Q={alpha:!1,depth:!1,stencil:!1,antialias:!1},qd={},rd;function sd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function td(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function ud(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var vd=1,wd=[],R=[],xd=[],yd=[],zd=[],S=[],T=[],Ad=[],bd=[],Bd=[],Cd={},Dd={},Ed=4;function U(a){Fd||(Fd=a)}function Gd(a){for(var b=vd++,c=a.length;c<b;c++)a[c]=null;return b}function ad(a,b){if(a=a.getContext("webgl",b)){var c=Gd(bd),d={cg:c,attributes:b,version:b.lf,te:a};a.canvas&&(a.canvas.Ae=d);bd[c]=d;("undefined"===typeof b.Bf||b.Bf)&&Hd(d);b=c}else b=0;return b}function cd(a){Id=bd[a];h.pe=N=Id&&Id.te}
function Hd(a){a||(a=Id);if(!a.Hf){a.Hf=!0;var b=a.te;sd(b);td(b);ud(b);b.ne=b.getExtension("EXT_disjoint_timer_query");b.fg=b.getExtension("WEBGL_multi_draw");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var $c={},Fd,Id,Jd=0;function Kd(){for(var a=Ld.length-1;0<=a;--a)Md(a);Ld=[];Nd=[]}var Nd=[];function Od(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in Nd){var f=Nd[e];if(f.Ve==a&&d(f.Xe,c))return}Nd.push({Ve:a,rf:b,Xe:c});Nd.sort(function(g,m){return g.rf<m.rf})}
function Pd(a){for(var b=0;b<Nd.length;++b)Nd[b].Ve==a&&(Nd.splice(b,1),--b)}function Qd(){if(Jd&&Rd.ue)for(var a=0;a<Nd.length;++a){var b=Nd[a];Nd.splice(a,1);--a;b.Ve.apply(null,b.Xe)}}var Ld=[];function Md(a){var b=Ld[a];b.target.removeEventListener(b.he,b.Cf,b.le);Ld.splice(a,1)}
function Sd(a){function b(d){++Jd;Rd=a;Qd();a.oe(d);Qd();--Jd}if(a.me)a.Cf=b,a.target.addEventListener(a.he,b,a.le),Ld.push(a),Td||(Ua.push(Kd),Td=!0);else for(var c=0;c<Ld.length;++c)Ld[c].target==a.target&&Ld[c].he==a.he&&Md(c--)}function Ud(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function Vd(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Wd={},Td,Rd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie={},je=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function V(a){a=2<a?B(a):a;return je[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function ke(a){var b=W(),c=La(8),d=c+4,e=La(a.id.length+1);E(a.id,e,a.id.length+1);if(a=V(e))w[c>>2]=a.width,w[d>>2]=a.height;c=[w[c>>2],w[d>>2]];X(b);return c}function le(a,b,c){a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function me(a,b,c){if(a.Wf){var d=W(),e=La(a.id.length+1);E(a.id,e,a.id.length+1);le(e,b,c);X(d)}else a.width=b,a.height=c}
function ne(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),me(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=p,a.style.paddingTop=t,a.style.paddingBottom=u,a.style.marginLeft=v,a.style.marginRight=
z,a.style.marginTop=C,a.style.marginBottom=H,document.body.style.margin=Ba,document.documentElement.style.overflow=sa,document.body.scroll=vc,a.style.jf=O,a.Ae&&a.Ae.te.viewport(0,0,d,e),ie.Ge&&G.get(ie.Ge)(37,0,ie.Ze))}var c=ke(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,p=a.style.paddingRight,t=a.style.paddingTop,u=a.style.paddingBottom,v=a.style.marginLeft,z=a.style.marginRight,C=a.style.marginTop,H=a.style.marginBottom,
Ba=document.body.style.margin,sa=document.documentElement.style.overflow,vc=document.body.scroll,O=a.style.jf;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function oe(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function pe(a){return 0>je.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function qe(a,b){if(0!=b.Ue||0!=b.Me){ne(a);var c=b.Rf?innerWidth:screen.width,d=b.Rf?innerHeight:screen.height,e=pe(a),f=e.width;e=e.height;var g=ke(a),m=g[0];g=g[1];3==b.Ue?(oe(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Ue&&(c*g<m*d?(f=g*c/m,oe(a,(d-f)/2,0),d=f):(f=m*d/g,oe(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Df&&(a.style.jf="pixelated");
f=2==b.Me?devicePixelRatio:1;0!=b.Me&&(c=c*f|0,d=d*f|0,me(a,c,d),a.Ae&&a.Ae.te.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Vd()?-3:-1;ie=b;b.Ge&&G.get(b.Ge)(37,0,b.Ze);return 0}function re(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.Ke)a.Ke();else return document.body.requestPointerLock||document.body.Ke?-3:-1;return 0}
function se(a,b){Ca[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)Ca[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)Ca[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)w[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];w[a+1296>>2]=b.connected;w[a+1300>>2]=b.index;w[a+8>>2]=b.axes.length;w[a+12>>2]=b.buttons.length;E(b.id,a+1304,64);E(b.mapping,a+1368,64)}
function te(a,b,c){(a|0)===a&&(a=B(a));a=tb(a);if(a=h.preloadedImages[a]){var d=a.getContext("2d").getImageData(0,0,a.width,a.height),e=F(a.width*a.height*4);D.set(d.data,e);w[b>>2]=a.width;w[c>>2]=a.height;return e}return 0}var ue=[];function ve(a,b,c,d){for(var e=0;e<a;e++){var f=N[c](),g=f&&Gd(d);f?(f.name=g,d[g]=f):U(1282);w[b+4*e>>2]=g}}function we(a,b,c,d,e,f,g,m){b=R[b];if(a=N[a](b,c))d=m&&E(a.name,m,d),e&&(w[e>>2]=d),f&&(w[f>>2]=a.size),g&&(w[g>>2]=a.type)}
function xe(a,b){Oa[a>>2]=b;Oa[a+4>>2]=(b-Oa[a>>2])/4294967296}
function ye(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&U(1280);return;case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:U(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:q[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){U(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:U(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:xe(b,
d);break;case 0:w[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:q[b>>0]=d?1:0}}else U(1281)}function ze(a){var b=Ia(a)+1,c=F(b);E(a,c,b);return c}function Ae(a,b,c,d){if(c)if(a=N.getUniform(R[a],S[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:A[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b]}else U(1281)}
function Be(a,b,c,d){if(c)if(a=N.getVertexAttrib(a,b),34975==b)w[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:w[c+4*b>>2]=Math.fround(a[b])}else U(1281)}
function Ce(a,b,c,d,e){a-=5120;a=1==a?D:4==a?w:6==a?A:5==a||28922==a?Oa:Na;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Ed;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var De=[],Ee=[];function Fe(a,b){if(!Vd())return-1;a=V(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Jd&&Rd.ue?qe(a,b):b.Af?(Od(qe,1,[a,b]),1):-2:-3:-4}
function Ge(a,b){var c={target:V(2),he:"beforeunload",me:b,oe:function(d){d=d||event;var e=G.get(b)(28,0,a);e&&(e=B(e));if(e)return d.preventDefault(),d.returnValue=e},le:!0};Sd(c)}function He(a,b,c,d,e,f){Yd||(Yd=F(256));a={target:V(a),he:f,me:d,oe:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Yd;E(Ud(g.target),n+0,128);E(m,n+128,128);G.get(d)(e,n,b)&&g.preventDefault()},le:c};Sd(a)}
function Ie(a,b,c,d,e){$d||($d=F(280));Sd({target:a,he:e,me:d,oe:function(f){f=f||event;var g=$d,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;w[g>>2]=n;w[g+4>>2]=Vd();var r=n?m:Zd,p=r&&r.id?r.id:"";E(Ud(r),g+8,128);E(p,g+136,128);w[g+264>>2]=r?r.clientWidth:0;w[g+268>>2]=r?r.clientHeight:0;w[g+272>>2]=screen.width;w[g+276>>2]=screen.height;n&&(Zd=m);G.get(d)(19,g,b)&&f.preventDefault()},le:c})}
function Je(a,b,c,d,e){ae||(ae=F(1432));b={target:V(2),ue:!0,he:e,me:c,oe:function(f){f=f||event;var g=ae;se(g,f.gamepad);G.get(c)(d,g,a)&&f.preventDefault()},le:b};Sd(b)}
function Ke(a,b,c,d,e,f){be||(be=F(164));a={target:V(a),ue:!0,he:f,me:d,oe:function(g){var m=be,n=m>>2;w[n]=g.location;w[n+1]=g.ctrlKey;w[n+2]=g.shiftKey;w[n+3]=g.altKey;w[n+4]=g.metaKey;w[n+5]=g.repeat;w[n+6]=g.charCode;w[n+7]=g.keyCode;w[n+8]=g.which;E(g.key||"",m+36,32);E(g.code||"",m+68,32);E(g.char||"",m+100,32);E(g.locale||"",m+132,32);G.get(d)(e,m,b)&&g.preventDefault()},le:c};Sd(a)}
function Le(a,b,c){a>>=2;w[a]=b.screenX;w[a+1]=b.screenY;w[a+2]=b.clientX;w[a+3]=b.clientY;w[a+4]=b.ctrlKey;w[a+5]=b.shiftKey;w[a+6]=b.altKey;w[a+7]=b.metaKey;Aa[2*a+16]=b.button;Aa[2*a+17]=b.buttons;w[a+9]=b.movementX;w[a+10]=b.movementY;c=pe(c);w[a+11]=b.clientX-c.left;w[a+12]=b.clientY-c.top}function Me(a,b,c,d,e,f){ce||(ce=F(64));a=V(a);Sd({target:a,ue:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,he:f,me:d,oe:function(g){g=g||event;Le(ce,g,a);G.get(d)(e,ce,b)&&g.preventDefault()},le:c})}
function Ne(a,b,c,d,e){de||(de=F(260));Sd({target:a,he:e,me:d,oe:function(f){f=f||event;var g=de,m=document.pointerLockElement||document.Be||document.cf||document.bf;w[g>>2]=!!m;var n=m&&m.id?m.id:"";E(Ud(m),g+4,128);E(n,g+132,128);G.get(d)(20,g,b)&&f.preventDefault()},le:c})}
function Oe(a,b,c,d){ee||(ee=F(36));a=V(a);Sd({target:a,he:"resize",me:d,oe:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=ee;w[g>>2]=e.detail;w[g+4>>2]=f.clientWidth;w[g+8>>2]=f.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset;w[g+32>>2]=pageYOffset;G.get(d)(10,g,b)&&e.preventDefault()}}},le:c})}
function Pe(a,b,c,d,e,f){fe||(fe=F(1684));a=V(a);Sd({target:a,ue:"touchstart"==f||"touchend"==f,he:f,me:d,oe:function(g){for(var m={},n=g.touches,r=0;r<n.length;++r){var p=n[r];m[p.identifier]=p}n=g.changedTouches;for(r=0;r<n.length;++r)p=n[r],p.Jf=1,m[p.identifier]=p;n=g.targetTouches;for(r=0;r<n.length;++r)m[n[r].identifier].Nf=1;n=fe;p=n>>2;w[p+1]=g.ctrlKey;w[p+2]=g.shiftKey;w[p+3]=g.altKey;w[p+4]=g.metaKey;p+=5;var t=pe(a),u=0;for(r in m){var v=m[r];w[p]=v.identifier;w[p+1]=v.screenX;w[p+2]=v.screenY;
w[p+3]=v.clientX;w[p+4]=v.clientY;w[p+5]=v.pageX;w[p+6]=v.pageY;w[p+7]=v.Jf;w[p+8]=v.Nf;w[p+9]=v.clientX-t.left;w[p+10]=v.clientY-t.top;p+=13;if(31<++u)break}w[n>>2]=u;G.get(d)(e,n,b)&&g.preventDefault()},le:c})}function Qe(a,b,c){var d=je[1];ge||(ge=F(8));Sd({target:d,he:"visibilitychange",me:c,oe:function(e){e=e||event;var f=ge,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);w[f>>2]=document.hidden;w[f+4>>2]=g;G.get(c)(21,f,a)&&e.preventDefault()},le:b})}
function Re(a,b,c,d){he||(he=F(96));Sd({target:a,ue:!0,he:"wheel",me:d,oe:function(e){e=e||event;var f=he;Le(f,e,a);Ca[f+64>>3]=e.deltaX;Ca[f+72>>3]=e.deltaY;Ca[f+80>>3]=e.deltaZ;w[f+88>>2]=e.deltaMode;G.get(d)(9,f,b)&&e.preventDefault()},le:c})}var Se={};
function Te(){if(!Ue){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Se)a[b]=Se[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ue=c}return Ue}var Ue,Ve=[];function Qb(a,b,c,d){a||(a=this);this.parent=a;this.se=a.se;this.xe=null;this.id=Hb++;this.name=b;this.mode=c;this.ce={};this.de={};this.rdev=d}
Object.defineProperties(Qb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Lf:{get:function(){return K(this.mode)}},Kf:{get:function(){return 8192===(this.mode&61440)}}});kc();Ib=Array(4096);Yb(J,"/");$b("/tmp");$b("/home");$b("/home/web_user");
(function(){$b("/dev");wb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});ac("/dev/null",259);vb(1280,yb);vb(1536,zb);ac("/dev/tty",1280);ac("/dev/tty1",1536);var a=sb();qc("/dev","random",a);qc("/dev","urandom",a);$b("/dev/shm");$b("/dev/shm/tmp")})();$b("/proc");$b("/proc/self");$b("/proc/self/fd");
Yb({se:function(){var a=Bb("/proc/self","fd",16895,73);a.ce={lookup:function(b,c){var d=Gb[+c];if(!d)throw new I(8);b={parent:null,se:{nf:"fake"},ce:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");h.FS_createPath=nc;h.FS_createDataFile=pc;h.FS_createPreloadedFile=tc;h.FS_createLazyFile=sc;h.FS_createDevice=qc;h.FS_unlink=cc;h.requestFullscreen=function(a,b){gd(a,b)};h.requestAnimationFrame=function(a){Ic(a)};
h.setCanvasSize=function(a,b,c){id(h.canvas,a,b);c||jd()};h.pauseMainLoop=function(){Fc=null;Lc++};h.resumeMainLoop=function(){Lc++;var a=Cc,b=Dc,c=Ec;Ec=null;Jc(c,0,!1,Kc,!0);Bc(a,b);Fc()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return Zc(a,b,c,d)};for(var N,Y=0;32>Y;++Y)ue.push(Array(Y));var We=new Float32Array(288);
for(Y=0;288>Y;++Y)De[Y]=We.subarray(0,Y+1);var Xe=new Int32Array(288);for(Y=0;288>Y;++Y)Ee[Y]=Xe.subarray(0,Y+1);function hb(a,b){var c=Array(Ia(a)+1);a=Ha(a,c,0,c.length);b&&(c.length=a);return c}Sa.push({ff:function(){Ye()}});
var nf={_:function(a,b,c,d){l("Assertion failed: "+B(a)+", at: "+[b?B(b):"unknown filename",c,d?B(d):"unknown function"])},x:function(a,b,c){xc=c;try{var d=zc(a);switch(b){case 0:var e=yc();return 0>e?-28:ec(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=yc(),d.flags|=e,0;case 12:return e=yc(),Aa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return mb(),-1;default:return-28}}catch(f){return"undefined"!==typeof M&&f instanceof I||l(f),-f.ie}},
ma:function(a,b,c){xc=c;try{var d=zc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=yc();return w[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=yc();if(!d.de.If)throw new I(59);return d.de.If(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:l("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof M&&f instanceof I||l(f),-f.ie}},na:function(a,
b,c){xc=c;try{var d=B(a),e=yc();return ec(d,b,e).fd}catch(f){return"undefined"!==typeof M&&f instanceof I||l(f),-f.ie}},oa:function(a){try{a=B(a);var b=Kb(a,{parent:!0}).node,c=rb(a),d=Db(b,c),e=Ub(b,c,!0);if(e)throw new I(e);if(!b.ce.rmdir)throw new I(63);if(d.xe)throw new I(10);try{L.willDeletePath&&L.willDeletePath(a)}catch(f){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.ce.rmdir(b,c);Ob(d);try{if(L.onDeletePath)L.onDeletePath(a)}catch(f){k("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+f.message)}return 0}catch(f){return"undefined"!==typeof M&&f instanceof I||l(f),-f.ie}},qa:function(a,b){try{a=B(a);a:{try{var c=Kb(a,{He:!0}).node;if(!c)throw new I(44);if(!c.ce.qe)throw new I(63);var d=c.ce.qe(c)}catch(f){if(f&&f.node&&pb(a)!==pb(Mb(f.node))){var e=-54;break a}throw f;}w[b>>2]=d.dev;w[b+4>>2]=0;w[b+8>>2]=d.ino;w[b+12>>2]=d.mode;w[b+16>>2]=d.nlink;w[b+20>>2]=d.uid;w[b+24>>2]=d.gid;w[b+28>>2]=d.rdev;w[b+32>>2]=0;x=[d.size>>>0,(y=d.size,1<=+Math.abs(y)?
0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[b+40>>2]=x[0];w[b+44>>2]=x[1];w[b+48>>2]=4096;w[b+52>>2]=d.blocks;w[b+56>>2]=d.atime.getTime()/1E3|0;w[b+60>>2]=0;w[b+64>>2]=d.mtime.getTime()/1E3|0;w[b+68>>2]=0;w[b+72>>2]=d.ctime.getTime()/1E3|0;w[b+76>>2]=0;x=[d.ino>>>0,(y=d.ino,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[b+80>>2]=x[0];w[b+84>>2]=x[1];e=0}return e}catch(f){return"undefined"!==
typeof M&&f instanceof I||l(f),-f.ie}},pa:function(a){try{return a=B(a),cc(a),0}catch(b){return"undefined"!==typeof M&&b instanceof I||l(b),-b.ie}},mc:function(){l()},o:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Ac();else return mb(),-1;w[b>>2]=a/1E3|0;w[b+4>>2]=a%1E3*1E6|0;return 0},ta:function(){l("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Ka:function(a){if(12448==a)return P=12288,1;P=12300;return 0},
mb:function(a,b,c,d,e){if(62E3!=a)P=12296,c=0;else{if(b)for(;;){a=w[b>>2];if(12321==a)Q.alpha=0<w[b+4>>2];else if(12325==a)Q.depth=0<w[b+4>>2];else if(12326==a)Q.stencil=0<w[b+4>>2];else if(12337==a)a=w[b+4>>2],Q.antialias=0<a;else if(12338==a)a=w[b+4>>2],Q.antialias=1==a;else if(12544==a)Q.dg=12547!=w[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(w[e>>2]=1),c&&0<d&&(w[c>>2]=62002),P=12288,c=1):(P=12300,c=0)}return c},Aa:function(a,b,c,d){if(62E3!=a)return P=12296,0;for(a=1;;){b=w[d>>2];if(12440==
b)a=w[d+4>>2];else if(12344==b)break;else return P=12292,0;d+=8}if(2!=a)return P=12293,0;Q.lf=a-1;Q.eg=0;rd=ad(h.canvas,Q);if(0!=rd)return P=12288,cd(rd),h.Tf=!0,Sc.forEach(function(e){e()}),cd(null),62004;P=12297;return 0},Ca:function(a,b){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;P=12288;return 62006},Ba:function(a,b){if(62E3!=a)return P=12296,0;if(62004!=b)return P=12294,0;a=rd;Id===bd[a]&&(Id=null);if("object"===typeof Wd)for(var c=bd[a].te.canvas,d=0;d<Ld.length;++d)Ld[d].target!=
c||Md(d--);bd[a]&&bd[a].te.canvas&&(bd[a].te.canvas.Ae=void 0);bd[a]=null;P=12288;nd==b&&(nd=0);return 1},Da:function(a,b){if(62E3!=a)return P=12296,0;if(62006!=b)return P=12301,1;od==b&&(od=0);pd==b&&(pd=0);P=12288;return 1},xb:function(a,b,c,d){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;if(!d)return P=12300,0;P=12288;switch(c){case 12320:return w[d>>2]=Q.alpha?32:24,1;case 12321:return w[d>>2]=Q.alpha?8:0,1;case 12322:return w[d>>2]=8,1;case 12323:return w[d>>2]=8,1;case 12324:return w[d>>
2]=8,1;case 12325:return w[d>>2]=Q.depth?24:0,1;case 12326:return w[d>>2]=Q.stencil?8:0,1;case 12327:return w[d>>2]=12344,1;case 12328:return w[d>>2]=62002,1;case 12329:return w[d>>2]=0,1;case 12330:return w[d>>2]=4096,1;case 12331:return w[d>>2]=16777216,1;case 12332:return w[d>>2]=4096,1;case 12333:return w[d>>2]=0,1;case 12334:return w[d>>2]=0,1;case 12335:return w[d>>2]=12344,1;case 12337:return w[d>>2]=Q.antialias?4:0,1;case 12338:return w[d>>2]=Q.antialias?1:0,1;case 12339:return w[d>>2]=4,
1;case 12340:return w[d>>2]=12344,1;case 12341:case 12342:case 12343:return w[d>>2]=-1,1;case 12345:case 12346:return w[d>>2]=0,1;case 12347:return w[d>>2]=0,1;case 12348:return w[d>>2]=1;case 12349:case 12350:return w[d>>2]=0,1;case 12351:return w[d>>2]=12430,1;case 12352:return w[d>>2]=4,1;case 12354:return w[d>>2]=0,1;default:return P=12292,0}},X:function(){P=12288;return 62E3},za:function(){return P},La:function(a){return Ze(a)},Sa:function(a,b,c){if(62E3==a)return b&&(w[b>>2]=1),c&&(w[c>>2]=
4),md=!0,P=12288,1;P=12296;return 0},Ea:function(a,b,c,d){if(62E3!=a)return P=12296,0;if(0!=d&&62004!=d)return P=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return P=12301,0;cd(d?rd:null);nd=d;pd=b;od=c;P=12288;return 1},ya:function(a,b){if(62E3!=a)return P=12296,0;P=12288;if(qd[b])return qd[b];switch(b){case 12371:a=Ja("Emscripten");break;case 12372:a=Ja("1.4 Emscripten EGL");break;case 12373:a=Ja("");break;case 12429:a=Ja("OpenGL_ES");break;default:return P=12300,0}return qd[b]=a},Fa:function(){if(md)if(h.pe)if(h.pe.isContextLost())P=
12302;else return P=12288,1;else P=12290;else P=12289;return 0},Ga:function(a,b){if(62E3!=a)return P=12296,0;0==b?Bc(0,0):Bc(1,b);P=12288;return 1},bb:function(a){if(62E3!=a)return P=12296,0;pd=od=nd=0;md=!1;P=12288;return 1},Ja:function(){P=12288;return 1},Ha:function(){P=12288;return 1},d:function(a,b,c){Ve.length=0;var d;for(c>>=2;d=D[b++];)(d=105>d)&&c&1&&c++,Ve.push(d?Ca[c++>>1]:w[c]),++c;return jb[a].apply(null,Ve)},ua:function(){if(!Vd())return-1;Pd(qe);var a=je[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},wa:function(){Pd(re);if(document.exitPointerLock)document.exitPointerLock();else if(document.ge)document.ge();else return-1;return 0},j:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},g:function(a,b,c){a=V(a);if(!a)return-4;a=pe(a);Ca[b>>3]=a.width;Ca[c>>3]=a.height;return 0},A:function(a,b){if(0>a||a>=Xd.length)return-5;if(!Xd[a])return-7;se(b,Xd[a]);
return 0},sa:function(){return Xd.length},Ia:te,xa:function(a,b,c){a=h._fileno(a);return(a=Gb[a])?te(a.path,b,c):0},Dd:function(a){N.activeTexture(a)},Cd:function(a,b){N.attachShader(R[a],T[b])},da:function(a,b){N.ne.beginQueryEXT(a,Bd[b])},Bd:function(a,b,c){N.bindAttribLocation(R[a],b,B(c))},Ad:function(a,b){N.bindBuffer(a,wd[b])},zd:function(a,b){N.bindFramebuffer(a,xd[b])},yd:function(a,b){N.bindRenderbuffer(a,yd[b])},xd:function(a,b){N.bindTexture(a,zd[b])},Ld:function(a){N.bindVertexArray(Ad[a])},
wd:function(a,b,c,d){N.blendColor(a,b,c,d)},vd:function(a){N.blendEquation(a)},ud:function(a,b){N.blendEquationSeparate(a,b)},td:function(a,b){N.blendFunc(a,b)},sd:function(a,b,c,d){N.blendFuncSeparate(a,b,c,d)},rd:function(a,b,c,d){N.bufferData(a,c?D.subarray(c,c+b):b,d)},qd:function(a,b,c,d){N.bufferSubData(a,b,D.subarray(d,d+c))},pd:function(a){return N.checkFramebufferStatus(a)},od:function(a){N.clear(a)},nd:function(a,b,c,d){N.clearColor(a,b,c,d)},md:function(a){N.clearDepth(a)},ld:function(a){N.clearStencil(a)},
kd:function(a,b,c,d){N.colorMask(!!a,!!b,!!c,!!d)},jd:function(a){N.compileShader(T[a])},id:function(a,b,c,d,e,f,g,m){N.compressedTexImage2D(a,b,c,d,e,f,m?D.subarray(m,m+g):null)},hd:function(a,b,c,d,e,f,g,m,n){N.compressedTexSubImage2D(a,b,c,d,e,f,g,n?D.subarray(n,n+m):null)},gd:function(a,b,c,d,e,f,g,m){N.copyTexImage2D(a,b,c,d,e,f,g,m)},fd:function(a,b,c,d,e,f,g,m){N.copyTexSubImage2D(a,b,c,d,e,f,g,m)},ed:function(){var a=Gd(R),b=N.createProgram();b.name=a;R[a]=b;return a},dd:function(a){var b=
Gd(T);T[b]=N.createShader(a);return b},cd:function(a){N.cullFace(a)},bd:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=wd[d];e&&(N.deleteBuffer(e),e.name=0,wd[d]=null)}},ad:function(a,b){for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=xd[d];e&&(N.deleteFramebuffer(e),e.name=0,xd[d]=null)}},$c:function(a){if(a){var b=R[a];b?(N.deleteProgram(b),b.name=0,R[a]=null,Cd[a]=null):U(1281)}},fa:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Bd[d];e&&(N.ne.deleteQueryEXT(e),Bd[d]=null)}},_c:function(a,
b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=yd[d];e&&(N.deleteRenderbuffer(e),e.name=0,yd[d]=null)}},Zc:function(a){if(a){var b=T[a];b?(N.deleteShader(b),T[a]=null):U(1281)}},Yc:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=zd[d];e&&(N.deleteTexture(e),e.name=0,zd[d]=null)}},Kd:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];N.deleteVertexArray(Ad[d]);Ad[d]=null}},Xc:function(a){N.depthFunc(a)},Wc:function(a){N.depthMask(!!a)},Vc:function(a,b){N.depthRange(a,b)},Uc:function(a,b){N.detachShader(R[a],
T[b])},Tc:function(a){N.disable(a)},Sc:function(a){N.disableVertexAttribArray(a)},Rc:function(a,b,c){N.drawArrays(a,b,c)},Gd:function(a,b,c,d){N.drawArraysInstanced(a,b,c,d)},Hd:function(a,b){for(var c=ue[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];N.drawBuffers(c)},Qc:function(a,b,c,d){N.drawElements(a,b,c,d)},Fd:function(a,b,c,d,e){N.drawElementsInstanced(a,b,c,d,e)},Pc:function(a){N.enable(a)},Oc:function(a){N.enableVertexAttribArray(a)},ca:function(a){N.ne.endQueryEXT(a)},Nc:function(){N.finish()},Mc:function(){N.flush()},
Lc:function(a,b,c,d){N.framebufferRenderbuffer(a,b,c,yd[d])},Kc:function(a,b,c,d,e){N.framebufferTexture2D(a,b,c,zd[d],e)},Jc:function(a){N.frontFace(a)},Hc:function(a,b){ve(a,b,"createBuffer",wd)},Fc:function(a,b){ve(a,b,"createFramebuffer",xd)},ga:function(a,b){for(var c=0;c<a;c++){var d=N.ne.createQueryEXT();if(!d){for(U(1282);c<a;)w[b+4*c++>>2]=0;break}var e=Gd(Bd);d.name=e;Bd[e]=d;w[b+4*c>>2]=e}},Ec:function(a,b){ve(a,b,"createRenderbuffer",yd)},Dc:function(a,b){ve(a,b,"createTexture",zd)},Jd:function(a,
b){ve(a,b,"createVertexArray",Ad)},Gc:function(a){N.generateMipmap(a)},Cc:function(a,b,c,d,e,f,g){we("getActiveAttrib",a,b,c,d,e,f,g)},Bc:function(a,b,c,d,e,f,g){we("getActiveUniform",a,b,c,d,e,f,g)},Ac:function(a,b,c,d){a=N.getAttachedShaders(R[a]);var e=a.length;e>b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+4*b>>2]=T.indexOf(a[b])},zc:function(a,b){return N.getAttribLocation(R[a],B(b))},yc:function(a,b){ye(a,b,4)},wc:function(a,b,c){c?w[c>>2]=N.getBufferParameter(a,b):U(1281)},vc:function(){var a=N.getError()||
Fd;Fd=0;return a},uc:function(a,b){ye(a,b,2)},tc:function(a,b,c,d){a=N.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},sc:function(a,b){ye(a,b,0)},qc:function(a,b,c,d){a=N.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(w[c>>2]=b)},rc:function(a,b,c){if(c)if(a>=vd)U(1281);else{var d=Cd[a];if(d)if(35716==b)a=N.getProgramInfoLog(R[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==
b)w[c>>2]=d.Re;else if(35722==b){if(-1==d.Ce){a=R[a];var e=N.getProgramParameter(a,35721);for(b=d.Ce=0;b<e;++b)d.Ce=Math.max(d.Ce,N.getActiveAttrib(a,b).name.length+1)}w[c>>2]=d.Ce}else if(35381==b){if(-1==d.De)for(a=R[a],e=N.getProgramParameter(a,35382),b=d.De=0;b<e;++b)d.De=Math.max(d.De,N.getActiveUniformBlockName(a,b).length+1);w[c>>2]=d.De}else w[c>>2]=N.getProgramParameter(R[a],b);else U(1282)}else U(1281)},Nd:function(a,b,c){if(c){a=N.ne.getQueryObjectEXT(Bd[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;xe(c,d)}else U(1281)},$:function(a,b,c){if(c){a=N.ne.getQueryObjectEXT(Bd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else U(1281)},Md:function(a,b,c){if(c){a=N.ne.getQueryObjectEXT(Bd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;xe(c,d)}else U(1281)},Od:function(a,b,c){if(c){a=N.ne.getQueryObjectEXT(Bd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else U(1281)},aa:function(a,b,c){c?w[c>>2]=N.ne.getQueryEXT(a,b):U(1281)},pc:function(a,b,c){c?w[c>>2]=N.getRenderbufferParameter(a,
b):U(1281)},nc:function(a,b,c,d){a=N.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(w[c>>2]=b)},lc:function(a,b,c,d){a=N.getShaderPrecisionFormat(a,b);w[c>>2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},kc:function(a,b,c,d){if(a=N.getShaderSource(T[a]))b=0<b&&d?E(a,d,b):0,c&&(w[c>>2]=b)},oc:function(a,b,c){c?35716==b?(a=N.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(T[a]),w[c>>2]=a?a.length+1:
0):w[c>>2]=N.getShaderParameter(T[a],b):U(1281)},jc:function(a){if(Dd[a])return Dd[a];switch(a){case 7939:var b=N.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ze(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=N.getParameter(a))||U(1280);b=ze(b);break;case 7938:b=ze("OpenGL ES 2.0 ("+N.getParameter(7938)+")");break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),
b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ze(b);break;default:return U(1280),0}return Dd[a]=b},ic:function(a,b,c){c?A[c>>2]=N.getTexParameter(a,b):U(1281)},hc:function(a,b,c){c?w[c>>2]=N.getTexParameter(a,b):U(1281)},ec:function(a,b){b=B(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Cd[a]&&Cd[a].tf[b])&&0<=c&&c<a[0]?a[1]+c:-1},gc:function(a,b,c){Ae(a,b,c,2)},fc:function(a,b,c){Ae(a,b,c,0)},bc:function(a,b,c){c?w[c>>2]=N.getVertexAttribOffset(a,
b):U(1281)},dc:function(a,b,c){Be(a,b,c,2)},cc:function(a,b,c){Be(a,b,c,5)},ac:function(a,b){N.hint(a,b)},$b:function(a){return(a=wd[a])?N.isBuffer(a):0},_b:function(a){return N.isEnabled(a)},Zb:function(a){return(a=xd[a])?N.isFramebuffer(a):0},Yb:function(a){return(a=R[a])?N.isProgram(a):0},ea:function(a){return(a=Bd[a])?N.ne.isQueryEXT(a):0},Xb:function(a){return(a=yd[a])?N.isRenderbuffer(a):0},Wb:function(a){return(a=T[a])?N.isShader(a):0},Vb:function(a){return(a=zd[a])?N.isTexture(a):0},Id:function(a){return(a=
Ad[a])?N.isVertexArray(a):0},Ub:function(a){N.lineWidth(a)},Sb:function(a){N.linkProgram(R[a]);var b=R[a];a=Cd[a]={tf:{},Re:0,Ce:-1,De:-1};for(var c=a.tf,d=N.getProgramParameter(b,35718),e=0;e<d;++e){var f=N.getActiveUniform(b,e),g=f.name;a.Re=Math.max(a.Re,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var m=N.getUniformLocation(b,g);if(m){var n=Gd(S);c[g]=[f.size,n];S[n]=m;for(var r=1;r<f.size;++r)m=N.getUniformLocation(b,g+"["+r+"]"),n=Gd(S),S[n]=m}}},Rb:function(a,b){3317==a&&
(Ed=b);N.pixelStorei(a,b)},Qb:function(a,b){N.polygonOffset(a,b)},ba:function(a,b){N.ne.queryCounterEXT(Bd[a],b)},Pb:function(a,b,c,d,e,f,g){(g=Ce(f,e,c,d,g))?N.readPixels(a,b,c,d,e,f,g):U(1280)},Ob:function(){},Nb:function(a,b,c,d){N.renderbufferStorage(a,b,c,d)},Mb:function(a,b){N.sampleCoverage(a,!!b)},Lb:function(a,b,c,d){N.scissor(a,b,c,d)},Kb:function(){U(1280)},Jb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?w[d+4*f>>2]:-1;e+=B(w[c+4*f>>2],0>g?void 0:g)}N.shaderSource(T[a],e)},Hb:function(a,
b,c){N.stencilFunc(a,b,c)},Gb:function(a,b,c,d){N.stencilFuncSeparate(a,b,c,d)},Fb:function(a){N.stencilMask(a)},Eb:function(a,b){N.stencilMaskSeparate(a,b)},Db:function(a,b,c){N.stencilOp(a,b,c)},Cb:function(a,b,c,d){N.stencilOpSeparate(a,b,c,d)},Bb:function(a,b,c,d,e,f,g,m,n){N.texImage2D(a,b,c,d,e,f,g,m,n?Ce(m,g,d,e,n):null)},Ab:function(a,b,c){N.texParameterf(a,b,c)},zb:function(a,b,c){N.texParameterf(a,b,A[c>>2])},yb:function(a,b,c){N.texParameteri(a,b,c)},wb:function(a,b,c){N.texParameteri(a,
b,w[c>>2])},vb:function(a,b,c,d,e,f,g,m,n){var r=null;n&&(r=Ce(m,g,e,f,n));N.texSubImage2D(a,b,c,d,e,f,g,m,r)},ub:function(a,b){N.uniform1f(S[a],b)},tb:function(a,b,c){if(288>=b)for(var d=De[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);N.uniform1fv(S[a],d)},sb:function(a,b){N.uniform1i(S[a],b)},rb:function(a,b,c){if(288>=b)for(var d=Ee[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);N.uniform1iv(S[a],d)},qb:function(a,b,c){N.uniform2f(S[a],b,c)},pb:function(a,
b,c){if(144>=b)for(var d=De[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);N.uniform2fv(S[a],d)},ob:function(a,b,c){N.uniform2i(S[a],b,c)},nb:function(a,b,c){if(144>=b)for(var d=Ee[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);N.uniform2iv(S[a],d)},lb:function(a,b,c,d){N.uniform3f(S[a],b,c,d)},kb:function(a,b,c){if(96>=b)for(var d=De[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=
A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);N.uniform3fv(S[a],d)},jb:function(a,b,c,d){N.uniform3i(S[a],b,c,d)},ib:function(a,b,c){if(96>=b)for(var d=Ee[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);N.uniform3iv(S[a],d)},hb:function(a,b,c,d,e){N.uniform4f(S[a],b,c,d,e)},gb:function(a,b,c){if(72>=b){var d=De[4*b-1],e=A;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=A.subarray(c>>
2,c+16*b>>2);N.uniform4fv(S[a],d)},fb:function(a,b,c,d,e){N.uniform4i(S[a],b,c,d,e)},eb:function(a,b,c){if(72>=b)for(var d=Ee[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);N.uniform4iv(S[a],d)},db:function(a,b,c,d){if(72>=b)for(var e=De[4*b-1],f=0;f<4*b;f+=4)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);N.uniformMatrix2fv(S[a],
!!c,e)},cb:function(a,b,c,d){if(32>=b)for(var e=De[9*b-1],f=0;f<9*b;f+=9)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2],e[f+4]=A[d+(4*f+16)>>2],e[f+5]=A[d+(4*f+20)>>2],e[f+6]=A[d+(4*f+24)>>2],e[f+7]=A[d+(4*f+28)>>2],e[f+8]=A[d+(4*f+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);N.uniformMatrix3fv(S[a],!!c,e)},ab:function(a,b,c,d){if(18>=b){var e=De[16*b-1],f=A;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+
4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(S[a],!!c,e)},$a:function(a){N.useProgram(R[a])},_a:function(a){N.validateProgram(R[a])},Za:function(a,b){N.vertexAttrib1f(a,b)},Ya:function(a,b){N.vertexAttrib1f(a,A[b>>2])},Xa:function(a,b,c){N.vertexAttrib2f(a,b,c)},Wa:function(a,b){N.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},Va:function(a,
b,c,d){N.vertexAttrib3f(a,b,c,d)},Ua:function(a,b){N.vertexAttrib3f(a,A[b>>2],A[b+4>>2],A[b+8>>2])},Ta:function(a,b,c,d,e){N.vertexAttrib4f(a,b,c,d,e)},Ra:function(a,b){N.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+8>>2],A[b+12>>2])},Ed:function(a,b){N.vertexAttribDivisor(a,b)},Qa:function(a,b,c,d,e,f){N.vertexAttribPointer(a,b,c,!!d,e,f)},Pa:function(a,b,c,d){N.viewport(a,b,c,d)},r:function(){return 0},e:function(a,b){Z(a,b||1);throw"longjmp";},ha:function(a,b,c){D.copyWithin(a,b,b+c)},va:function(a,
b,c){return Fe(a,{Ue:w[c>>2],Me:w[c+4>>2],Df:w[c+8>>2],Af:b,Ge:w[c+12>>2],Ze:w[c+16>>2]})},W:function(a,b){a=V(a);return a?a.requestPointerLock||a.Ke?Jd&&Rd.ue?re(a):b?(Od(re,2,[a]),1):-2:-1:-4},ia:function(a){a>>>=0;var b=D.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{Da.grow(Math.min(2147483648,d)-Ma.byteLength+65535>>>16);Pa(Da.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
B:function(){return(Xd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},C:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;Ge(a,b);return 0},O:function(a,b,c,d){He(a,b,c,d,12,"blur");return 0},i:le,p:function(a,b,c){a=V(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},P:function(a,b,c,d){He(a,b,c,d,13,"focus");return 0},F:function(a,b,c,d){if(!Vd())return-1;a=V(a);if(!a)return-4;
Ie(a,b,c,d,"fullscreenchange");Ie(a,b,c,d,"webkitfullscreenchange");return 0},z:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Je(a,b,c,26,"gamepadconnected");return 0},y:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Je(a,b,c,27,"gamepaddisconnected");return 0},I:function(a,b,c,d){Ke(a,b,c,d,2,"keydown");return 0},G:function(a,b,c,d){Ke(a,b,c,d,1,"keypress");return 0},H:function(a,b,c,d){Ke(a,b,c,d,3,"keyup");return 0},Tb:function(a,
b,c,d,e){Jc(function(){G.get(a)()},b,c,d,e)},U:function(a,b,c,d){Me(a,b,c,d,5,"mousedown");return 0},S:function(a,b,c,d){Me(a,b,c,d,33,"mouseenter");return 0},R:function(a,b,c,d){Me(a,b,c,d,34,"mouseleave");return 0},V:function(a,b,c,d){Me(a,b,c,d,8,"mousemove");return 0},T:function(a,b,c,d){Me(a,b,c,d,6,"mouseup");return 0},J:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ge||document.body.Be||document.body.Ke))return-1;a=V(a);if(!a)return-4;Ne(a,
b,c,d,"pointerlockchange");Ne(a,b,c,d,"mozpointerlockchange");Ne(a,b,c,d,"webkitpointerlockchange");Ne(a,b,c,d,"mspointerlockchange");return 0},E:function(a,b,c,d){Oe(a,b,c,d);return 0},K:function(a,b,c,d){Pe(a,b,c,d,25,"touchcancel");return 0},M:function(a,b,c,d){Pe(a,b,c,d,23,"touchend");return 0},L:function(a,b,c,d){Pe(a,b,c,d,24,"touchmove");return 0},N:function(a,b,c,d){Pe(a,b,c,d,22,"touchstart");return 0},D:function(a,b,c){if(!je[1])return-4;Qe(a,b,c);return 0},Q:function(a,b,c,d){a=V(a);return"undefined"!==
typeof a.onwheel?(Re(a,b,c,d),0):-1},q:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},ja:function(a,b){try{var c=0;Te().forEach(function(d,e){var f=b+c;e=w[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++>>0]=d.charCodeAt(f);q[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof M&&d instanceof I||l(d),d.ie}},ka:function(a,b){try{var c=Te();w[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});w[b>>
2]=d;return 0}catch(e){return"undefined"!==typeof M&&e instanceof I||l(e),e.ie}},t:function(a){$e(a)},w:function(a){try{var b=zc(a);hc(b);return 0}catch(c){return"undefined"!==typeof M&&c instanceof I||l(c),c.ie}},la:function(a,b,c,d){try{a:{for(var e=zc(a),f=a=0;f<c;f++){var g=w[b+(8*f+4)>>2],m=e,n=w[b+8*f>>2],r=g,p=void 0,t=q;if(0>r||0>p)throw new I(28);if(null===m.fd)throw new I(8);if(1===(m.flags&2097155))throw new I(8);if(K(m.node.mode))throw new I(31);if(!m.de.read)throw new I(28);var u="undefined"!==
typeof p;if(!u)p=m.position;else if(!m.seekable)throw new I(70);var v=m.de.read(m,t,n,r,p);u||(m.position+=v);var z=v;if(0>z){var C=-1;break a}a+=z;if(z<g)break}C=a}w[d>>2]=C;return 0}catch(H){return"undefined"!==typeof M&&H instanceof I||l(H),H.ie}},Ma:function(a,b,c,d,e){try{var f=zc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;ic(f,a,d);x=[f.position>>>0,(y=f.position,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-
+(~~y>>>0))/4294967296)>>>0:0)];w[e>>2]=x[0];w[e+4>>2]=x[1];f.Pe&&0===a&&0===d&&(f.Pe=null);return 0}catch(g){return"undefined"!==typeof M&&g instanceof I||l(g),g.ie}},v:function(a,b,c,d){try{a:{for(var e=zc(a),f=a=0;f<c;f++){var g=jc(e,q,w[b+8*f>>2],w[b+(8*f+4)>>2],void 0);if(0>g){var m=-1;break a}a+=g}m=a}w[d>>2]=m;return 0}catch(n){return"undefined"!==typeof M&&n instanceof I||l(n),n.ie}},b:function(){return xa},n:function(a){var b=Date.now();w[a>>2]=b/1E3|0;w[a+4>>2]=b%1E3*1E3|0;return 0},xc:af,
m:bf,k:cf,s:df,u:ef,Ic:ff,Y:gf,Oa:hf,Na:jf,h:kf,l:lf,Z:mf,a:Da,ra:function(a,b){if(0===a)return mb(),-1;var c=w[a>>2];a=w[a+4>>2];if(0>a||999999999<a||0>c)return mb(),-1;0!==b&&(w[b>>2]=0,w[b+4>>2]=0);b=1E6*c+a/1E3;for(c=Ac();Ac()-c<b/1E3;);},c:function(a){xa=a},f:function(){return 0},Ib:function(){return 0}};
(function(){function a(e){h.asm=e.exports;G=h.asm.Pd;ab("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return gb().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){k("failed to asynchronously prepare wasm: "+f);if("undefined"!==typeof location){var g=location.search;0>g.indexOf("_rwasm=0")&&(location.href+=(g?g+"&":"?")+"_rwasm=0")}l(f)})}var d={a:nf};$a("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return ya||"function"!==typeof WebAssembly.instantiateStreaming||db(eb)||cb(eb,"file://")||"function"!==typeof fetch?c(b):fetch(eb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Ye=h.___wasm_call_ctors=function(){return(Ye=h.___wasm_call_ctors=h.asm.Qd).apply(null,arguments)},F=h._malloc=function(){return(F=h._malloc=h.asm.Rd).apply(null,arguments)};h._main=function(){return(h._main=h.asm.Sd).apply(null,arguments)};var nb=h.___errno_location=function(){return(nb=h.___errno_location=h.asm.Td).apply(null,arguments)},Ze=h._emscripten_GetProcAddress=function(){return(Ze=h._emscripten_GetProcAddress=h.asm.Ud).apply(null,arguments)};
h._fileno=function(){return(h._fileno=h.asm.Vd).apply(null,arguments)};
var W=h.stackSave=function(){return(W=h.stackSave=h.asm.Wd).apply(null,arguments)},X=h.stackRestore=function(){return(X=h.stackRestore=h.asm.Xd).apply(null,arguments)},La=h.stackAlloc=function(){return(La=h.stackAlloc=h.asm.Yd).apply(null,arguments)},Z=h._setThrew=function(){return(Z=h._setThrew=h.asm.Zd).apply(null,arguments)},of=h.dynCall_ji=function(){return(of=h.dynCall_ji=h.asm._d).apply(null,arguments)},pf=h.dynCall_jiji=function(){return(pf=h.dynCall_jiji=h.asm.$d).apply(null,arguments)};
h.dynCall_iiji=function(){return(h.dynCall_iiji=h.asm.ae).apply(null,arguments)};function bf(a,b){var c=W();try{return G.get(a)(b)}catch(d){X(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function ef(a,b,c,d,e){var f=W();try{return G.get(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function df(a,b,c,d){var e=W();try{return G.get(a)(b,c,d)}catch(f){X(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}
function kf(a,b){var c=W();try{G.get(a)(b)}catch(d){X(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function mf(a,b,c,d){var e=W();try{G.get(a)(b,c,d)}catch(f){X(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function lf(a,b,c){var d=W();try{G.get(a)(b,c)}catch(e){X(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}function cf(a,b,c){var d=W();try{return G.get(a)(b,c)}catch(e){X(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}
function gf(a,b,c,d,e,f,g,m,n,r){var p=W();try{return G.get(a)(b,c,d,e,f,g,m,n,r)}catch(t){X(p);if(t!==t+0&&"longjmp"!==t)throw t;Z(1,0)}}function ff(a,b,c,d,e,f,g,m,n){var r=W();try{return G.get(a)(b,c,d,e,f,g,m,n)}catch(p){X(r);if(p!==p+0&&"longjmp"!==p)throw p;Z(1,0)}}function af(a){var b=W();try{return G.get(a)()}catch(c){X(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}function hf(a,b){var c=W();try{return of(a,b)}catch(d){X(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}
function jf(a,b,c,d,e){var f=W();try{return pf(a,b,c,d,e)}catch(g){X(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}h.addRunDependency=$a;h.removeRunDependency=ab;h.FS_createPath=nc;h.FS_createDataFile=pc;h.FS_createPreloadedFile=tc;h.FS_createLazyFile=sc;h.FS_createDevice=qc;h.FS_unlink=cc;
if(bb)if(db(bb)||(bb=la(bb)),ia||ja){var qf=oa(bb);D.set(qf,1024)}else{$a("memory initializer");var rf=function(a){a.byteLength&&(a=new Uint8Array(a));D.set(a,1024);h.memoryInitializerRequest&&delete h.memoryInitializerRequest.response;ab("memory initializer")},sf=function(){na(bb,rf,function(){throw Error("could not load memory initializer "+bb);})};if(h.memoryInitializerRequest){var tf=function(){var a=h.memoryInitializerRequest,b=a.response;200!==a.status&&0!==a.status?(console.warn("a problem seems to have happened with Module.memoryInitializerRequest, status: "+
a.status+", retrying "+bb),sf()):rf(b)};h.memoryInitializerRequest.response?setTimeout(tf,0):h.memoryInitializerRequest.addEventListener("load",tf)}else sf()}var uf;function ta(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Za=function vf(){uf||wf();uf||(Za=vf)};
function wf(a){function b(){if(!uf&&(uf=!0,h.calledRun=!0,!Ea)){h.noFSInit||lc||(lc=!0,kc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?qc("/dev","stdin",h.stdin):bc("/dev/tty","/dev/stdin"),h.stdout?qc("/dev","stdout",null,h.stdout):bc("/dev/tty","/dev/stdout"),h.stderr?qc("/dev","stderr",null,h.stderr):bc("/dev/tty1","/dev/stderr"),ec("/dev/stdin",0),ec("/dev/stdout",1),ec("/dev/stderr",1));lb(Sa);Jb=!1;lb(Ta);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(xf){var c=a,d=h._main;
c=c||[];var e=c.length+1,f=La(4*(e+1));w[f>>2]=Ka(da);for(var g=1;g<e;g++)w[(f>>2)+g]=Ka(c[g-1]);w[(f>>2)+e]=0;try{var m=d(e,f);$e(m,!0)}catch(n){n instanceof ta||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),k("exception thrown: "+c),ea(1,n)))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Va.unshift(c);lb(Va)}}a=a||ca;if(!(0<Xa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Wa();
lb(Ra);0<Xa||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=wf;function $e(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(h.onExit)h.onExit(a);Ea=!0}ea(a,new ta(a))}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var xf=!0;h.noInitialRun&&(xf=!1);noExitRuntime=!0;wf();
