
var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.Me||(h.Me=0);h.Me++;
(function(a){function b(n,r,p){var t=new XMLHttpRequest;t.open("GET",n,!0);t.responseType="arraybuffer";t.onprogress=function(u){var v=r;u.total&&(v=u.total);if(u.loaded){t.ee?h.ue[n].loaded=u.loaded:(t.ee=!0,h.ue||(h.ue={}),h.ue[n]={loaded:u.loaded,total:v});var z=v=u=0,C;for(C in h.ue){var H=h.ue[C];u+=H.total;v+=H.loaded;z++}u=Math.ceil(u*h.Me/z);h.setStatus&&h.setStatus("Downloading data... ("+v+"/"+u+")")}else!h.ue&&h.setStatus&&h.setStatus("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+
n);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)p(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function c(n){console.error("package error:",n)}function d(){function n(u,v,z){this.start=u;this.ze=v;this.audio=z}function r(u){if(!u)throw"Loading data file failed."+Error().stack;if(!(u instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);n.prototype.Ze=u;u=a.files;for(var v=0;v<
u.length;++v)n.prototype.ee[u[v].filename].onload();h.removeRunDependency("datafile_wasm/basque.data")}h.FS_createPath("/","assets",!0,!0);h.FS_createPath("/assets","data",!0,!0);h.FS_createPath("/assets","icons",!0,!0);h.FS_createPath("/assets/icons","basque_logo.iconset",!0,!0);h.FS_createPath("/assets","images",!0,!0);h.FS_createPath("/assets","fonts",!0,!0);h.FS_createPath("/assets","audio",!0,!0);n.prototype={ee:{},open:function(u,v){this.name=v;this.ee[v]=this;h.addRunDependency("fp "+this.name)},
send:function(){},onload:function(){this.We(this.Ze.subarray(this.start,this.ze))},We:function(u){h.FS_createDataFile(this.name,null,u,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.ee[this.name]=null}};for(var p=a.files,t=0;t<p.length;++t)(new n(p[t].start,p[t].end,p[t].audio)).open("GET",p[t].filename);h.addRunDependency("datafile_wasm/basque.data");h.qf||(h.qf={});h.qf["wasm/basque.data"]={Zf:!1};m?(r(m),m=null):g=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=h.locateFile?h.locateFile("basque.data",""):"basque.data",f=a.remote_package_size,g=null,m=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;m||b(e,f,function(n){g?(g(n),g=null):m=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))})({files:[{filename:"/assets/data/map_layout_8.txt",start:0,end:27127,audio:0},{filename:"/assets/data/map_layout_5.txt",start:27127,end:54170,audio:0},{filename:"/assets/data/map_library.txt",start:54170,end:54463,audio:0},{filename:"/assets/data/map_layout_3.txt",
start:54463,end:81506,audio:0},{filename:"/assets/data/map_layout_0.txt",start:81506,end:108537,audio:0},{filename:"/assets/data/map_layout_1.txt",start:108537,end:135572,audio:0},{filename:"/assets/data/map_layout_7.txt",start:135572,end:162655,audio:0},{filename:"/assets/data/map_attributes.txt",start:162655,end:165159,audio:0},{filename:"/assets/data/map_layout_4.txt",start:165159,end:192202,audio:0},{filename:"/assets/data/map_layout_2.txt",start:192202,end:219241,audio:0},{filename:"/assets/data/map_layout_6.txt",
start:219241,end:246284,audio:0},{filename:"/assets/data/map_layout_9.txt",start:246284,end:273407,audio:0},{filename:"/assets/data/map_layout.txt",start:273407,end:300938,audio:0},{filename:"/assets/icons/basque_logo.png",start:300938,end:311581,audio:0},{filename:"/assets/icons/basque_logo.ico",start:311581,end:414411,audio:0},{filename:"/assets/icons/basque_logo.icns",start:414411,end:672138,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_64x64@2x.png",start:672138,end:692108,audio:0},
{filename:"/assets/icons/basque_logo.iconset/icon_8x8@2x.png",start:692108,end:695015,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_512x512@2x.png",start:695015,end:922804,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_512x512.png",start:922804,end:1043175,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_16x16@2x.png",start:1043175,end:1047377,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_64x64.png",start:1047377,end:1055557,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_32x32@2x.png",
start:1055557,end:1063737,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_16x16.png",start:1063737,end:1066644,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_32x32.png",start:1066644,end:1070846,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_128x128@2x.png",start:1070846,end:1123234,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_256x256.png",start:1123234,end:1175622,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_128x128.png",start:1175622,
end:1195592,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_256x256@2x.png",start:1195592,end:1315963,audio:0},{filename:"/assets/icons/basque_logo.iconset/icon_1024x1024.png",start:1315963,end:1543752,audio:0},{filename:"/assets/images/basque_logo.png",start:1543752,end:1545227,audio:0},{filename:"/assets/images/character.png",start:1545227,end:1549207,audio:0},{filename:"/assets/images/basque_logo_scaled.png",start:1549207,end:1573071,audio:0},{filename:"/assets/images/README.md",start:1573071,
end:1573257,audio:0},{filename:"/assets/images/basque_logo_scaled_v3.png",start:1573257,end:1597381,audio:0},{filename:"/assets/images/basque_logo_scaled_v2.png",start:1597381,end:1621156,audio:0},{filename:"/assets/images/tiles_packed.png",start:1621156,end:1628186,audio:0},{filename:"/assets/fonts/backpacker_license.pdf",start:1628186,end:1934389,audio:0},{filename:"/assets/fonts/BPtypewrite.ttf",start:1934389,end:2013561,audio:0},{filename:"/assets/audio/Basque_sample_music.ogg",start:2013561,
end:6254467,audio:1}],remote_package_size:6254467,package_uuid:"fc41ff37-7dd1-4edb-b5ef-e73b8f0b2fdf"});var aa={},ba;for(ba in h)h.hasOwnProperty(ba)&&(aa[ba]=h[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var ka="";
function la(a){return h.locateFile?h.locateFile(a,ka):ka+a}var ma,na,oa,pa,qa,ra;
if(ia){if(ka=ha?require("path").dirname(ka)+"/":__dirname+"/",ma=function(a,b){qa||(qa=require("fs"));ra||(ra=require("path"));a=ra.normalize(a);return qa.readFileSync(a,b?null:"utf8")},oa=function(a){a=ma(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof ta))throw a;}),process.on("unhandledRejection",
l),ea=function(a){process.exit(a)},h.inspect=function(){return"[Emscripten Module object]"},"undefined"===typeof WebAssembly){var fs=require("fs");eval(fs.readFileSync(la("basque.wasm.js"))+"")}}else if(ja)"undefined"!=typeof read&&(ma=function(a){return read(a)}),oa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===
typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print),"undefined"===typeof WebAssembly&&eval(read(la("basque.wasm.js")));else if(fa||ha)ha?ka=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ka=document.currentScript.src),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.lastIndexOf("/")+1):"",ma=function(a){var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(oa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),na=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},pa=function(a){document.title=a};var ua=h.print||console.log.bind(console),k=h.printErr||console.warn.bind(console);
for(ba in aa)aa.hasOwnProperty(ba)&&(h[ba]=aa[ba]);aa=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);function va(a){wa||(wa={});wa[a]||(wa[a]=1,k(a))}var wa,xa=0,ya;h.wasmBinary&&(ya=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;
function za(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":q[a>>0]=b;break;case "i8":q[a>>0]=b;break;case "i16":Aa[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":x=[b>>>0,(y=b,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[a>>2]=x[0];w[a+4>>2]=x[1];break;case "float":A[a>>2]=b;break;case "double":Ca[a>>3]=b;break;default:l("invalid type for setValue: "+c)}}var Da,Ea=!1,Fa;
function assert(a,b){a||l("Assertion failed: "+b)}var Ga="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ha(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ga)return Ga.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function B(a,b){return a?Ha(D,a,b):""}
function Ia(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function E(a,b,c){return Ia(a,D,b,c)}
function Ja(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ka(a){var b=Ja(a)+1,c=F(b);c&&Ia(a,q,c,b);return c}function La(a){var b=Ja(a)+1,c=Ma(b);Ia(a,q,c,b);return c}var Na,q,D,Aa,Oa,w,Pa,A,Ca;
function Qa(a){Na=a;h.HEAP8=q=new Int8Array(a);h.HEAP16=Aa=new Int16Array(a);h.HEAP32=w=new Int32Array(a);h.HEAPU8=D=new Uint8Array(a);h.HEAPU16=Oa=new Uint16Array(a);h.HEAPU32=Pa=new Uint32Array(a);h.HEAPF32=A=new Float32Array(a);h.HEAPF64=Ca=new Float64Array(a)}var Ra=h.INITIAL_MEMORY||536870912;h.wasmMemory?Da=h.wasmMemory:Da=new WebAssembly.Memory({initial:Ra/65536,maximum:32768});Da&&(Na=Da.buffer);Ra=Na.byteLength;Qa(Na);var G,Sa=[],Ta=[],Ua=[],Va=[],Wa=[];
function Xa(){var a=h.preRun.shift();Sa.unshift(a)}var Ya=0,Za=null,$a=null;function ab(){Ya++;h.monitorRunDependencies&&h.monitorRunDependencies(Ya)}function bb(){Ya--;h.monitorRunDependencies&&h.monitorRunDependencies(Ya);if(0==Ya&&(null!==Za&&(clearInterval(Za),Za=null),$a)){var a=$a;$a=null;a()}}h.preloadedImages={};h.preloadedAudios={};function l(a){if(h.onAbort)h.onAbort(a);k(a);Ea=!0;Fa=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
var cb="basque.html.mem";function db(a,b){return String.prototype.startsWith?a.startsWith(b):0===a.indexOf(b)}function eb(a){return db(a,"data:application/octet-stream;base64,")}var I="basque.wasm";eb(I)||(I=la(I));function fb(){var a=I;try{if(a==I&&ya)return new Uint8Array(ya);if(oa)return oa(a);throw"both async and sync fetching of the wasm failed";}catch(b){l(b)}}
function gb(){if(!ya&&(fa||ha)){if("function"===typeof fetch&&!db(I,"file://"))return fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return fb()});if(na)return new Promise(function(a,b){na(I,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return fb()})}
var y,x,jb={379624:function(a){a=B(a)+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");a=hb(a);var b=F(a.length);a.subarray||a.slice?D.set(a,b):D.set(new Uint8Array(a),b);return b},379849:function(a,b,c){h.SDL2||(h.SDL2={});var d=h.SDL2;d.vf!==h.canvas&&(d.ne=h.createContext(h.canvas,!1,!0),d.vf=h.canvas);if(d.w!==a||d.Df!==b||d.Ff!==d.ne)d.image=d.ne.createImageData(a,b),d.w=a,d.Df=b,d.Ff=d.ne;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&
a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=w[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Xf!==a&&(d.wf=new Int32Array(a.buffer),d.xf=new Uint8Array(a.buffer)),a=d.wf,c=a.length,a.set(w.subarray(b,b+c)),a=d.xf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.ne.putImageData(d.image,0,0);return 0},381304:function(a,
b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=w[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>16&255;b[m+3]=r>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(w.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=F(c.length+
1);E(c,d,c.length+1);return d},382293:function(a){h.canvas&&(h.canvas.style.cursor=B(a));return 0},382386:function(){h.canvas&&(h.canvas.style.cursor="none")},382455:function(){return screen.width},382480:function(){return screen.height},382506:function(){return window.innerWidth},382536:function(){return window.innerHeight},382567:function(a){"undefined"!==typeof pa&&pa(B(a));return 0},382662:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},382799:function(){return"undefined"!==
typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},383023:function(a){"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.de||("undefined"!==typeof AudioContext?b.de=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.de=new webkitAudioContext),b.de&&ib(b.de));return void 0===b.de?-1:0},383516:function(){return h.SDL2.de.sampleRate},383584:function(a,b,c,d){function e(){}
function f(m){void 0!==g.capture.Ce&&(clearTimeout(g.capture.Ce),g.capture.Ce=void 0);g.capture.Ge=g.de.createMediaStreamSource(m);g.capture.he=g.de.createScriptProcessor(b,a,1);g.capture.he.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Le=n.inputBuffer,n=[d],G.get(c).apply(null,n))};g.capture.Ge.connect(g.capture.he);g.capture.he.connect(g.de.destination);g.capture.stream=m}var g=h.SDL2;g.capture.Je=g.de.createBuffer(a,b,g.de.sampleRate);
g.capture.Je.getChannelData(0).fill(0);g.capture.Ce=setTimeout(function(){g.capture.Le=g.capture.Je;var m=[d];G.get(c).apply(null,m)},b/g.de.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},385236:function(a,b,c,d){var e=h.SDL2;e.audio.he=e.de.createScriptProcessor(b,0,a);e.audio.he.onaudioprocess=
function(f){void 0!==e&&void 0!==e.audio&&(e.audio.af=f.outputBuffer,f=[d],G.get(c).apply(null,f))};e.audio.he.connect(e.de.destination)},385646:function(a,b){for(var c=h.SDL2,d=c.capture.Le.numberOfChannels,e=0;e<d;++e){var f=c.capture.Le.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)za(a+4*g,f[g]);else for(g=0;g<b;++g)za(a+4*(g*d+e),f[g])}},386251:function(a,b){for(var c=
h.SDL2,d=c.audio.af.numberOfChannels,e=0;e<d;++e){var f=c.audio.af.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=A[a+(g*d+e<<2)>>2]}},386731:function(a){var b=h.SDL2;if(a){void 0!==b.capture.Ce&&clearTimeout(b.capture.Ce);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==
b.capture.he&&(b.capture.he.onaudioprocess=function(){},b.capture.he.disconnect(),b.capture.he=void 0);void 0!==b.capture.Ge&&(b.capture.Ge.disconnect(),b.capture.Ge=void 0);void 0!==b.capture.Je&&(b.capture.Je=void 0);b.capture=void 0}else void 0!=b.audio.he&&(b.audio.he.disconnect(),b.audio.he=void 0),b.audio=void 0;void 0!==b.de&&void 0===b.audio&&void 0===b.capture&&(b.de.close(),b.de=void 0)}};function kb(a,b,c){a.addEventListener(b,c,{once:!0})}
function ib(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&kb(d,c,function(){"suspended"===a.state&&a.resume()})})})}function lb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.Cf;"number"===typeof c?void 0===b.De?G.get(c)():G.get(c)(b.De):c(void 0===b.De?null:b.De)}}}
function mb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function nb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=mb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ob(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function pb(a){if("/"===a)return"/";a=nb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function qb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){l("randomDevice")}}
function rb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=mb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var sb=[];function tb(a,b){sb[a]={input:[],output:[],xe:b};ub(a,vb)}
var vb={open:function(a){var b=sb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.xe.flush(a.tty)},flush:function(a){a.tty.xe.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.xe.ef)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.xe.ef(a.tty)}catch(m){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.xe.Qe)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.xe.Qe(a.tty,b[c+e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},wb={ef:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.ee?Buffer.ee(256):new Buffer(256),d=0;try{d=qa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=hb(b,!0)}return a.input.shift()},Qe:function(a,b){null===b||10===b?(ua(Ha(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ua(Ha(a.output,0)),a.output=[])}},xb={Qe:function(a,b){null===b||10===b?(k(Ha(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(Ha(a.output,0)),a.output=[])}},K={pe:null,qe:function(){return K.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.pe||(K.pe={dir:{node:{oe:K.$d.oe,ie:K.$d.ie,lookup:K.$d.lookup,He:K.$d.He,rename:K.$d.rename,unlink:K.$d.unlink,rmdir:K.$d.rmdir,readdir:K.$d.readdir,symlink:K.$d.symlink},stream:{te:K.be.te}},file:{node:{oe:K.$d.oe,ie:K.$d.ie},stream:{te:K.be.te,read:K.be.read,write:K.be.write,Ue:K.be.Ue,kf:K.be.kf,mf:K.be.mf}},link:{node:{oe:K.$d.oe,ie:K.$d.ie,readlink:K.$d.readlink},stream:{}},$e:{node:{oe:K.$d.oe,
ie:K.$d.ie},stream:yb}});c=zb(a,b,c,d);L(c.mode)?(c.$d=K.pe.dir.node,c.be=K.pe.dir.stream,c.ae={}):32768===(c.mode&61440)?(c.$d=K.pe.file.node,c.be=K.pe.file.stream,c.ce=0,c.ae=null):40960===(c.mode&61440)?(c.$d=K.pe.link.node,c.be=K.pe.link.stream):8192===(c.mode&61440)&&(c.$d=K.pe.$e.node,c.be=K.pe.$e.stream);c.timestamp=Date.now();a&&(a.ae[b]=c,a.timestamp=c.timestamp);return c},$f:function(a){return a.ae?a.ae.subarray?a.ae.subarray(0,a.ce):new Uint8Array(a.ae):new Uint8Array(0)},bf:function(a,
b){var c=a.ae?a.ae.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ae,a.ae=new Uint8Array(b),0<a.ce&&a.ae.set(c.subarray(0,a.ce),0))},Of:function(a,b){if(a.ce!=b)if(0==b)a.ae=null,a.ce=0;else{var c=a.ae;a.ae=new Uint8Array(b);c&&a.ae.set(c.subarray(0,Math.min(b,a.ce)));a.ce=b}},$d:{oe:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.ce:
40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.uf=4096;b.blocks=Math.ceil(b.size/b.uf);return b},ie:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.Of(a,b.size)},lookup:function(){throw Ab[44];},He:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(L(a.mode)){try{var d=Bb(b,c)}catch(f){}if(d)for(var e in d.ae)throw new J(55);
}delete a.parent.ae[a.name];a.parent.timestamp=Date.now();a.name=c;b.ae[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.ae[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Bb(a,b),d;for(d in c.ae)throw new J(55);delete a.ae[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.ae)a.ae.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);
return a.link}},be:{read:function(a,b,c,d,e){var f=a.node.ae;if(e>=a.node.ce)return 0;a=Math.min(a.node.ce-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===q.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ae||a.ae.subarray)){if(f)return a.ae=b.subarray(c,c+d),a.ce=d;if(0===a.ce&&0===e)return a.ae=b.slice(c,c+d),a.ce=d;if(e+d<=a.ce)return a.ae.set(b.subarray(c,c+d),e),d}K.bf(a,e+
d);if(a.ae.subarray&&b.subarray)a.ae.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ae[e+f]=b[c+f];a.ce=Math.max(a.ce,e+d);return d},te:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ce);if(0>b)throw new J(28);return b},Ue:function(a,b,c){K.bf(a.node,b+c);a.node.ce=Math.max(a.node.ce,b+c)},kf:function(a,b,c,d,e,f){if(0!==b)throw new J(28);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.ae;if(f&2||a.buffer!==Na){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,
d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=F(f);c<f;)q[b+c++]=0;c=b;if(!c)throw new J(48);q.set(a,c)}else d=!1,c=a.byteOffset;return{gg:c,Uf:d}},mf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.be.write(a,b,0,d,c,!1);return 0}}},Cb=null,Db={},Eb=[],Fb=1,Gb=null,Hb=!0,M={},J=null,Ab={};
function Ib(a,b){a=rb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={cf:!0,Re:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Re)throw new J(32);a=mb(a.split("/").filter(function(g){return!!g}),!1);var e=Cb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Bb(e,a[d]);c=nb(c+"/"+a[d]);e.ve&&(!f||f&&b.cf)&&(e=e.ve.root);if(!f||b.Fe)for(f=0;40960===(e.mode&61440);)if(e=Jb(c),c=rb(ob(c),e),e=Ib(c,{Re:b.Re}).node,40<f++)throw new J(32);}return{path:c,node:e}}
function Kb(a){for(var b;;){if(a===a.parent)return a=a.qe.lf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Lb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Gb.length}function Mb(a){var b=Lb(a.parent.id,a.name);if(Gb[b]===a)Gb[b]=a.we;else for(b=Gb[b];b;){if(b.we===a){b.we=a.we;break}b=b.we}}
function Bb(a,b){var c;if(c=(c=Nb(a,"x"))?c:a.$d.lookup?0:2)throw new J(c,a);for(c=Gb[Lb(a.id,b)];c;c=c.we){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.$d.lookup(a,b)}function zb(a,b,c,d){a=new Ob(a,b,c,d);b=Lb(a.parent.id,a.name);a.we=Gb[b];return Gb[b]=a}function L(a){return 16384===(a&61440)}var Pb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Qb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Nb(a,b){if(Hb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Rb(a,b){try{return Bb(a,b),20}catch(c){}return Nb(a,"wx")}function Sb(a,b,c){try{var d=Bb(a,b)}catch(e){return e.ge}if(a=Nb(a,"wx"))return a;if(c){if(!L(d.mode))return 54;if(d===d.parent||"/"===Kb(d))return 10}else if(L(d.mode))return 31;return 0}
function Tb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Eb[a])return a;throw new J(33);}function Ub(a,b){Vb||(Vb=function(){},Vb.prototype={});var c=new Vb,d;for(d in a)c[d]=a[d];a=c;b=Tb(b);a.fd=b;return Eb[b]=a}var yb={open:function(a){a.be=Db[a.node.rdev].be;a.be.open&&a.be.open(a)},te:function(){throw new J(70);}};function ub(a,b){Db[a]={be:b}}
function Wb(a,b){var c="/"===b,d=!b;if(c&&Cb)throw new J(10);if(!c&&!d){var e=Ib(b,{cf:!1});b=e.path;e=e.node;if(e.ve)throw new J(10);if(!L(e.mode))throw new J(54);}b={type:a,fg:{},lf:b,Lf:[]};a=a.qe(b);a.qe=b;b.root=a;c?Cb=a:e&&(e.ve=b,e.qe&&e.qe.Lf.push(b))}function Xb(a,b,c){var d=Ib(a,{parent:!0}).node;a=pb(a);if(!a||"."===a||".."===a)throw new J(28);var e=Rb(d,a);if(e)throw new J(e);if(!d.$d.He)throw new J(63);return d.$d.He(d,a,b,c)}function Yb(a){return Xb(a,16895,0)}
function Zb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Xb(a,b|8192,c)}function $b(a,b){if(!rb(a))throw new J(44);var c=Ib(b,{parent:!0}).node;if(!c)throw new J(44);b=pb(b);var d=Rb(c,b);if(d)throw new J(d);if(!c.$d.symlink)throw new J(63);c.$d.symlink(c,b,a)}
function ac(a){var b=Ib(a,{parent:!0}).node,c=pb(a),d=Bb(b,c),e=Sb(b,c,!1);if(e)throw new J(e);if(!b.$d.unlink)throw new J(63);if(d.ve)throw new J(10);try{M.willDeletePath&&M.willDeletePath(a)}catch(f){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.$d.unlink(b,c);Mb(d);try{if(M.onDeletePath)M.onDeletePath(a)}catch(f){k("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}}
function Jb(a){a=Ib(a).node;if(!a)throw new J(44);if(!a.$d.readlink)throw new J(28);return rb(Kb(a.parent),a.$d.readlink(a))}function bc(a,b){a="string"===typeof a?Ib(a,{Fe:!0}).node:a;if(!a.$d.ie)throw new J(63);a.$d.ie(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function cc(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=Pb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=nb(a);try{f=Ib(a,{Fe:!(b&131072)}).node}catch(g){}}e=!1;if(b&64)if(f){if(b&128)throw new J(20);}else f=Xb(a,c,0),e=!0;if(!f)throw new J(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!L(f.mode))throw new J(54);if(!e&&(c=f?40960===(f.mode&61440)?32:L(f.mode)&&
("r"!==Qb(b)||b&512)?31:Nb(f,Qb(b)):44))throw new J(c);if(b&512){c=f;c="string"===typeof c?Ib(c,{Fe:!0}).node:c;if(!c.$d.ie)throw new J(63);if(L(c.mode))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(e=Nb(c,"w"))throw new J(e);c.$d.ie(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Ub({node:f,path:Kb(f),flags:b,seekable:!0,position:0,be:f.be,Rf:[],error:!1},d);d.be.open&&d.be.open(d);!h.logReadFiles||b&1||(dc||(dc={}),a in dc||(dc[a]=1,k("FS.trackingDelegate error on read file: "+a)));
try{M.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),M.onOpenFile(a,f))}catch(g){k("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+g.message)}return d}function ec(a){if(null===a.fd)throw new J(8);a.Ne&&(a.Ne=null);try{a.be.close&&a.be.close(a)}catch(b){throw b;}finally{Eb[a.fd]=null}a.fd=null}function fc(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.be.te)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.be.te(a,b,c);a.Rf=[]}
function hc(a,b,c,d,e,f){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(L(a.node.mode))throw new J(31);if(!a.be.write)throw new J(28);a.seekable&&a.flags&1024&&fc(a,0,2);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new J(70);b=a.be.write(a,b,c,d,e,f);g||(a.position+=b);try{if(a.path&&M.onWriteToFile)M.onWriteToFile(a.path)}catch(m){k("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function ic(){J||(J=function(a,b){this.node=b;this.Pf=function(c){this.ge=c};this.Pf(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){Ab[a]=new J(a);Ab[a].stack="<generic error, no stack>"}))}var jc;function kc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function lc(a,b){a="string"===typeof a?a:Kb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=nb(a+"/"+c);try{Yb(d)}catch(e){}a=d}}return d}
function mc(a,b,c,d){a=nb(("string"===typeof a?a:Kb(a))+"/"+b);c=kc(c,d);return Xb(a,(void 0!==c?c:438)&4095|32768,0)}function nc(a,b,c,d,e,f){a=b?nb(("string"===typeof a?a:Kb(a))+"/"+b):a;d=kc(d,e);e=Xb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var g=c.length;b<g;++b)a[b]=c.charCodeAt(b);c=a}bc(e,d|146);a=cc(e,577);hc(a,c,0,c.length,0,f);ec(a);bc(e,d)}return e}
function oc(a,b,c,d){a=nb(("string"===typeof a?a:Kb(a))+"/"+b);b=kc(!!c,!!d);oc.hf||(oc.hf=64);var e=oc.hf++<<8|0;ub(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,g,m,n){for(var r=0,p=0;p<n;p++){try{var t=c()}catch(u){throw new J(29);}if(void 0===t&&0===r)throw new J(6);if(null===t||void 0===t)break;r++;g[m+p]=t}r&&(f.node.timestamp=Date.now());return r},write:function(f,g,m,n){for(var r=0;r<n;r++)try{d(g[m+r])}catch(p){throw new J(29);}n&&
(f.node.timestamp=Date.now());return r}});return Zb(a,b,e)}function pc(a){if(!(a.Jf||a.Kf||a.link||a.ae)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ma)try{a.ae=hb(ma(a.url),!0),a.ce=a.ae.length}catch(b){throw new J(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function qc(a,b,c,d,e){function f(){this.Oe=!1;this.ee=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var t=p%this.chunkSize;return this.ff(p/this.chunkSize|0)[t]}};f.prototype.ze=function(p){this.ff=p};f.prototype.Xe=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var t=Number(p.getResponseHeader("Content-length")),u,v=(u=p.getResponseHeader("Accept-Ranges"))&&
"bytes"===u;p=(u=p.getResponseHeader("Content-Encoding"))&&"gzip"===u;var z=1048576;v||(z=t);var C=this;C.ze(function(H){var Ba=H*z,sa=(H+1)*z-1;sa=Math.min(sa,t-1);if("undefined"===typeof C.ee[H]){var vc=C.ee;if(Ba>sa)throw Error("invalid range ("+Ba+", "+sa+") or no bytes requested!");if(sa>t-1)throw Error("only "+t+" bytes available! programmer error!");var O=new XMLHttpRequest;O.open("GET",c,!1);t!==z&&O.setRequestHeader("Range","bytes="+Ba+"-"+sa);"undefined"!=typeof Uint8Array&&(O.responseType=
"arraybuffer");O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);if(!(200<=O.status&&300>O.status||304===O.status))throw Error("Couldn't load "+c+". Status: "+O.status);Ba=void 0!==O.response?new Uint8Array(O.response||[]):hb(O.responseText||"",!0);vc[H]=Ba}if("undefined"===typeof C.ee[H])throw Error("doXHR failed!");return C.ee[H]});if(p||!t)z=t=1,z=t=this.ff(0).length,ua("LazyFiles on gzip forces download of the whole file when length is accessed");this.tf=
t;this.sf=z;this.Oe=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;Object.defineProperties(g,{length:{get:function(){this.Oe||this.Xe();return this.tf}},chunkSize:{get:function(){this.Oe||this.Xe();return this.sf}}});var m=void 0}else m=c,g=void 0;var n=mc(a,b,d,e);g?n.ae=g:m&&(n.ae=null,n.url=m);Object.defineProperties(n,{ce:{get:function(){return this.ae.length}}});
var r={};Object.keys(n.be).forEach(function(p){var t=n.be[p];r[p]=function(){pc(n);return t.apply(null,arguments)}});r.read=function(p,t,u,v,z){pc(n);p=p.node.ae;if(z>=p.length)return 0;v=Math.min(p.length-z,v);if(p.slice)for(var C=0;C<v;C++)t[u+C]=p[z+C];else for(C=0;C<v;C++)t[u+C]=p.get(z+C);return v};n.be=r;return n}
function rc(a,b,c,d,e,f,g,m,n,r){function p(v){function z(H){r&&r();m||nc(a,b,H,d,e,n);f&&f();bb(u)}var C=!1;h.preloadPlugins.forEach(function(H){!C&&H.canHandle(t)&&(H.handle(v,t,z,function(){g&&g();bb(u)}),C=!0)});C||z(v)}sc();var t=b?rb(nb(a+"/"+b)):a,u="cp "+t;ab(u);"string"==typeof c?tc(c,function(v){p(v)},g):p(c)}var uc={},Vb,dc,wc=void 0;function xc(){wc+=4;return w[wc-4>>2]}function yc(a){a=Eb[a];if(!a)throw new J(8);return a}var zc;
ia?zc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?zc=dateNow:zc=function(){return performance.now()};
function Ac(a,b){Bc=a;Cc=b;if(Dc)if(Ec||(Ec=!0),0==a)Fc=function(){var d=Math.max(0,Gc+b-zc())|0;setTimeout(Hc,d)};else if(1==a)Fc=function(){Ic(Hc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Fc=function(){setImmediate(Hc)}}}
function Jc(a,b,c,d,e){function f(){if(g<Kc){if(!noExitRuntime)try{Lc(Fa)}catch(m){if(!(m instanceof ta))throw m;}return!1}return!0}assert(!Dc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Dc=a;Mc=d;var g=Kc;Ec=!1;Hc=function(){if(!Ea)if(0<Nc.length){var m=Date.now(),n=Nc.shift();n.Cf(n.De);if(Oc){var r=Oc,p=0==r%1?r-1:Math.floor(r);Oc=n.Wf?p:(8*r+(p+.5))/
9}console.log('main loop blocker "'+n.name+'" took '+(Date.now()-m)+" ms");h.setStatus&&(m=h.statusMessage||"Please wait...",n=Oc,r=Pc.Yf,n?n<r?h.setStatus(m+" ("+(r-n)+"/"+r+")"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(Hc,0)}else f()&&(Qc=Qc+1|0,1==Bc&&1<Cc&&0!=Qc%Cc?Fc():(0==Bc&&(Gc=zc()),Ea||h.preMainLoop&&!1===h.preMainLoop()||(Rc(a),h.postMainLoop&&h.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.Nf&&SDL.audio.Nf(),Fc())))};e||(b&&0<b?Ac(0,1E3/b):Ac(1,1),Fc());if(c)throw"unwind";
}function Rc(a){try{a()}catch(b){if(!(b instanceof ta)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&k("exception thrown: "+[b,b.stack]),b;}}var Ec=!1,Fc=null,Kc=0,Dc=null,Mc=0,Bc=0,Cc=0,Qc=0,Nc=[],Pc={},Gc,Hc,Oc,Sc=!1,Tc=!1,Uc=[];
function sc(){function a(){Tc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!Vc){Vc=!0;try{Wc=!0}catch(c){Wc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Xc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Wc?null:console.log("warning: no BlobBuilder");
Yc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.nf||"undefined"!==typeof Yc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.nf=!0);h.preloadPlugins.push({canHandle:function(c){return!h.nf&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(Wc)try{g=new Blob([c],{type:Zc(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Zc(d)}))}catch(r){va("Blob constructor present but fails: "+
r+"; falling back to blob builder")}g||(g=new Xc,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var m=Yc.createObjectURL(g),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=n.width;r.height=n.height;r.getContext("2d").drawImage(n,0,0);h.preloadedImages[d]=r;Yc.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");f&&f()};n.src=m}});h.preloadPlugins.push({canHandle:function(c){return!h.eg&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function g(t){n||(n=!0,h.preloadedAudios[d]=t,e&&e(c))}function m(){n||(n=!0,h.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(Wc){try{var r=new Blob([c],{type:Zc(d)})}catch(t){return m()}r=Yc.createObjectURL(r);var p=new Audio;p.addEventListener("canplaythrough",function(){g(p)},!1);p.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var t="",u=0,v=0,
z=0;z<c.length;z++)for(u=u<<8|c[z],v+=8;6<=v;){var C=u>>v-6&63;v-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[C]}2==v?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],t+="=="):4==v&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],t+="=");p.src="data:audio/x-"+d.substr(-3)+";base64,"+t;g(p)}};p.src=r;$c(function(){g(p)})}else return m()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&
b.addEventListener("click",function(c){!Tc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function ad(a,b,c,d){if(b&&h.ne&&a==h.canvas)return h.ne;var e;if(b){var f={antialias:!1,alpha:!1,jf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!==typeof bd&&(e=cd(a,f)))var m=dd[e].re}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof N,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.ne=m,b&&ed(e),h.Sf=b,Uc.forEach(function(n){n()}),sc());return m}var fd=!1,gd=void 0,hd=void 0;
function id(a,b){function c(){Sc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=jd,gd&&d.requestPointerLock(),Sc=!0,hd?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=Pa[SDL.screen>>2]|8388608),kd(h.canvas),ld()):kd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),hd?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=Pa[SDL.screen>>2]&
-8388609),kd(h.canvas),ld()):kd(d));if(h.onFullScreen)h.onFullScreen(Sc);if(h.onFullscreen)h.onFullscreen(Sc)}gd=a;hd=b;"undefined"===typeof gd&&(gd=!0);"undefined"===typeof hd&&(hd=!1);var d=h.canvas;fd||(fd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function jd(){if(!Sc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var md=0;function Ic(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===md)md=b+1E3/60;else for(;b+2>=md;)md+=1E3/60;setTimeout(a,Math.max(md-b,0))}}function $c(a){setTimeout(function(){Rc(a)},1E4)}
function Zc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function tc(a,b,c){var d="al "+a;na(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&bb(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&ab(d)}var nd=[];function ld(){var a=h.canvas;nd.forEach(function(b){b(a.width,a.height)})}
function kd(a,b,c){b&&c?(a.Tf=b,a.Ef=c):(b=a.Tf,c=a.Ef);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}hd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Vc,Wc,Xc,Yc,P=12288,od=!1,pd=0,qd=0,rd=0,Q={alpha:!1,depth:!1,stencil:!1,antialias:!1},sd={},td;function ud(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function vd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function wd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var xd=1,yd=[],R=[],zd=[],Ad=[],Bd=[],S=[],T=[],Cd=[],dd=[],Dd=[],Ed={},Fd={},Gd=4;function U(a){Hd||(Hd=a)}function Id(a){for(var b=xd++,c=a.length;c<b;c++)a[c]=null;return b}function cd(a,b){a.df||(a.df=a.getContext,a.getContext=function(d,e){e=a.df(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Jd(c,b):0}
function Jd(a,b){var c=Id(dd),d={ag:c,attributes:b,version:b.jf,re:a};a.canvas&&(a.canvas.ye=d);dd[c]=d;("undefined"===typeof b.zf||b.zf)&&Kd(d);return c}function ed(a){Ld=dd[a];h.ne=N=Ld&&Ld.re}function Kd(a){a||(a=Ld);if(!a.Gf){a.Gf=!0;var b=a.re;ud(b);vd(b);wd(b);b.le=b.getExtension("EXT_disjoint_timer_query");b.dg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var bd={},Hd,Ld,Md=0;
function Nd(){for(var a=Od.length-1;0<=a;--a)Pd(a);Od=[];Qd=[]}var Qd=[];function Rd(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in Qd){var f=Qd[e];if(f.Te==a&&d(f.Ve,c))return}Qd.push({Te:a,pf:b,Ve:c});Qd.sort(function(g,m){return g.pf<m.pf})}function Sd(a){for(var b=0;b<Qd.length;++b)Qd[b].Te==a&&(Qd.splice(b,1),--b)}function Td(){if(Md&&Ud.se)for(var a=0;a<Qd.length;++a){var b=Qd[a];Qd.splice(a,1);--a;b.Te.apply(null,b.Ve)}}
var Od=[];function Pd(a){var b=Od[a];b.target.removeEventListener(b.fe,b.Af,b.je);Od.splice(a,1)}function Vd(a){function b(d){++Md;Ud=a;Td();a.me(d);Td();--Md}if(a.ke)a.Af=b,a.target.addEventListener(a.fe,b,a.je),Od.push(a),Wd||(Va.push(Nd),Wd=!0);else for(var c=0;c<Od.length;++c)Od[c].target==a.target&&Od[c].fe==a.fe&&Pd(c--)}function Xd(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
function Yd(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var Zd={},Wd,Ud,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le={},me=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function V(a){a=2<a?B(a):a;return me[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function ne(a){var b=W(),c=Ma(8),d=c+4,e=Ma(a.id.length+1);E(a.id,e,a.id.length+1);if(a=V(e))w[c>>2]=a.width,w[d>>2]=a.height;c=[w[c>>2],w[d>>2]];X(b);return c}
function oe(a,b,c){a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0}function pe(a,b,c){if(a.Vf){var d=W(),e=Ma(a.id.length+1);E(a.id,e,a.id.length+1);oe(e,b,c);X(d)}else a.width=b,a.height=c}
function qe(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),pe(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=p,a.style.paddingTop=t,a.style.paddingBottom=u,a.style.marginLeft=v,a.style.marginRight=
z,a.style.marginTop=C,a.style.marginBottom=H,document.body.style.margin=Ba,document.documentElement.style.overflow=sa,document.body.scroll=vc,a.style.gf=O,a.ye&&a.ye.re.viewport(0,0,d,e),le.Ee&&G.get(le.Ee)(37,0,le.Ye))}var c=ne(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,p=a.style.paddingRight,t=a.style.paddingTop,u=a.style.paddingBottom,v=a.style.marginLeft,z=a.style.marginRight,C=a.style.marginTop,H=a.style.marginBottom,
Ba=document.body.style.margin,sa=document.documentElement.style.overflow,vc=document.body.scroll,O=a.style.gf;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function re(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function se(a){return 0>me.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function te(a,b){if(0!=b.Se||0!=b.Ke){qe(a);var c=b.Qf?innerWidth:screen.width,d=b.Qf?innerHeight:screen.height,e=se(a),f=e.width;e=e.height;var g=ne(a),m=g[0];g=g[1];3==b.Se?(re(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Se&&(c*g<m*d?(f=g*c/m,re(a,(d-f)/2,0),d=f):(f=m*d/g,re(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Bf&&(a.style.gf="pixelated");
f=2==b.Ke?devicePixelRatio:1;0!=b.Ke&&(c=c*f|0,d=d*f|0,pe(a,c,d),a.ye&&a.ye.re.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Yd()?-3:-1;le=b;b.Ee&&G.get(b.Ee)(37,0,b.Ye);return 0}function ue(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.Ie)a.Ie();else return document.body.requestPointerLock||document.body.Ie?-3:-1;return 0}
function ve(a,b){Ca[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)Ca[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)Ca[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)w[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];w[a+1296>>2]=b.connected;w[a+1300>>2]=b.index;w[a+8>>2]=b.axes.length;w[a+12>>2]=b.buttons.length;E(b.id,a+1304,64);E(b.mapping,a+1368,64)}
function we(a,b,c){(a|0)===a&&(a=B(a));a=rb(a);if(a=h.preloadedImages[a]){var d=a.getContext("2d").getImageData(0,0,a.width,a.height),e=F(a.width*a.height*4);D.set(d.data,e);w[b>>2]=a.width;w[c>>2]=a.height;return e}return 0}var xe=[];function ye(a,b,c,d){for(var e=0;e<a;e++){var f=N[c](),g=f&&Id(d);f?(f.name=g,d[g]=f):U(1282);w[b+4*e>>2]=g}}function ze(a,b,c,d,e,f,g,m){b=R[b];if(a=N[a](b,c))d=m&&E(a.name,m,d),e&&(w[e>>2]=d),f&&(w[f>>2]=a.size),g&&(w[g>>2]=a.type)}
function Ae(a,b){Pa[a>>2]=b;Pa[a+4>>2]=(b-Pa[a>>2])/4294967296}
function Be(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&U(1280);return;case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:U(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:q[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){U(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:U(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Ae(b,
d);break;case 0:w[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:q[b>>0]=d?1:0}}else U(1281)}function Ce(a){var b=Ja(a)+1,c=F(b);E(a,c,b);return c}function De(a,b,c,d){if(c)if(a=N.getUniform(R[a],S[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:A[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b]}else U(1281)}
function Ee(a,b,c,d){if(c)if(a=N.getVertexAttrib(a,b),34975==b)w[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:w[c+4*b>>2]=Math.fround(a[b])}else U(1281)}
function Fe(a,b,c,d,e){a-=5120;a=1==a?D:4==a?w:6==a?A:5==a||28922==a?Pa:Oa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Gd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var Ge=[],He=[];function Ie(a,b){if(!Yd())return-1;a=V(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Md&&Ud.se?te(a,b):b.yf?(Rd(te,1,[a,b]),1):-2:-3:-4}
function Je(a,b){var c={target:V(2),fe:"beforeunload",ke:b,me:function(d){d=d||event;var e=G.get(b)(28,0,a);e&&(e=B(e));if(e)return d.preventDefault(),d.returnValue=e},je:!0};Vd(c)}function Ke(a,b,c,d,e,f){ae||(ae=F(256));a={target:V(a),fe:f,ke:d,me:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=ae;E(Xd(g.target),n+0,128);E(m,n+128,128);G.get(d)(e,n,b)&&g.preventDefault()},je:c};Vd(a)}
function Le(a,b,c,d,e){ce||(ce=F(280));Vd({target:a,fe:e,ke:d,me:function(f){f=f||event;var g=ce,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;w[g>>2]=n;w[g+4>>2]=Yd();var r=n?m:be,p=r&&r.id?r.id:"";E(Xd(r),g+8,128);E(p,g+136,128);w[g+264>>2]=r?r.clientWidth:0;w[g+268>>2]=r?r.clientHeight:0;w[g+272>>2]=screen.width;w[g+276>>2]=screen.height;n&&(be=m);G.get(d)(19,g,b)&&f.preventDefault()},je:c})}
function Me(a,b,c,d,e){de||(de=F(1432));b={target:V(2),se:!0,fe:e,ke:c,me:function(f){f=f||event;var g=de;ve(g,f.gamepad);G.get(c)(d,g,a)&&f.preventDefault()},je:b};Vd(b)}
function Ne(a,b,c,d,e,f){ee||(ee=F(164));a={target:V(a),se:!0,fe:f,ke:d,me:function(g){var m=ee,n=m>>2;w[n]=g.location;w[n+1]=g.ctrlKey;w[n+2]=g.shiftKey;w[n+3]=g.altKey;w[n+4]=g.metaKey;w[n+5]=g.repeat;w[n+6]=g.charCode;w[n+7]=g.keyCode;w[n+8]=g.which;E(g.key||"",m+36,32);E(g.code||"",m+68,32);E(g.char||"",m+100,32);E(g.locale||"",m+132,32);G.get(d)(e,m,b)&&g.preventDefault()},je:c};Vd(a)}
function Oe(a,b,c){a>>=2;w[a]=b.screenX;w[a+1]=b.screenY;w[a+2]=b.clientX;w[a+3]=b.clientY;w[a+4]=b.ctrlKey;w[a+5]=b.shiftKey;w[a+6]=b.altKey;w[a+7]=b.metaKey;Aa[2*a+16]=b.button;Aa[2*a+17]=b.buttons;w[a+9]=b.movementX;w[a+10]=b.movementY;c=se(c);w[a+11]=b.clientX-c.left;w[a+12]=b.clientY-c.top}function Pe(a,b,c,d,e,f){fe||(fe=F(64));a=V(a);Vd({target:a,se:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,fe:f,ke:d,me:function(g){g=g||event;Oe(fe,g,a);G.get(d)(e,fe,b)&&g.preventDefault()},je:c})}
function Qe(a,b,c,d,e){ge||(ge=F(260));Vd({target:a,fe:e,ke:d,me:function(f){f=f||event;var g=ge,m=document.pointerLockElement||document.ze||document.Ze||document.We;w[g>>2]=!!m;var n=m&&m.id?m.id:"";E(Xd(m),g+4,128);E(n,g+132,128);G.get(d)(20,g,b)&&f.preventDefault()},je:c})}
function Re(a,b,c,d){he||(he=F(36));a=V(a);Vd({target:a,fe:"resize",ke:d,me:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=he;w[g>>2]=e.detail;w[g+4>>2]=f.clientWidth;w[g+8>>2]=f.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset;w[g+32>>2]=pageYOffset;G.get(d)(10,g,b)&&e.preventDefault()}}},je:c})}
function Se(a,b,c,d,e,f){ie||(ie=F(1684));a=V(a);Vd({target:a,se:"touchstart"==f||"touchend"==f,fe:f,ke:d,me:function(g){for(var m={},n=g.touches,r=0;r<n.length;++r){var p=n[r];m[p.identifier]=p}n=g.changedTouches;for(r=0;r<n.length;++r)p=n[r],p.If=1,m[p.identifier]=p;n=g.targetTouches;for(r=0;r<n.length;++r)m[n[r].identifier].Mf=1;n=ie;p=n>>2;w[p+1]=g.ctrlKey;w[p+2]=g.shiftKey;w[p+3]=g.altKey;w[p+4]=g.metaKey;p+=5;var t=se(a),u=0;for(r in m){var v=m[r];w[p]=v.identifier;w[p+1]=v.screenX;w[p+2]=v.screenY;
w[p+3]=v.clientX;w[p+4]=v.clientY;w[p+5]=v.pageX;w[p+6]=v.pageY;w[p+7]=v.If;w[p+8]=v.Mf;w[p+9]=v.clientX-t.left;w[p+10]=v.clientY-t.top;p+=13;if(31<++u)break}w[n>>2]=u;G.get(d)(e,n,b)&&g.preventDefault()},je:c})}function Te(a,b,c){var d=me[1];je||(je=F(8));Vd({target:d,fe:"visibilitychange",ke:c,me:function(e){e=e||event;var f=je,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);w[f>>2]=document.hidden;w[f+4>>2]=g;G.get(c)(21,f,a)&&e.preventDefault()},je:b})}
function Ue(a,b,c,d){ke||(ke=F(96));Vd({target:a,se:!0,fe:"wheel",ke:d,me:function(e){e=e||event;var f=ke;Oe(f,e,a);Ca[f+64>>3]=e.deltaX;Ca[f+72>>3]=e.deltaY;Ca[f+80>>3]=e.deltaZ;w[f+88>>2]=e.deltaMode;G.get(d)(9,f,b)&&e.preventDefault()},je:c})}var Ve={};
function We(){if(!Xe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Ve)a[b]=Ve[b];var c=[];for(b in a)c.push(b+"="+a[b]);Xe=c}return Xe}var Xe,Ye=[];function Ob(a,b,c,d){a||(a=this);this.parent=a;this.qe=a.qe;this.ve=null;this.id=Fb++;this.name=b;this.mode=c;this.$d={};this.be={};this.rdev=d}
Object.defineProperties(Ob.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Kf:{get:function(){return L(this.mode)}},Jf:{get:function(){return 8192===(this.mode&61440)}}});ic();Gb=Array(4096);Wb(K,"/");Yb("/tmp");Yb("/home");Yb("/home/web_user");
(function(){Yb("/dev");ub(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Zb("/dev/null",259);tb(1280,wb);tb(1536,xb);Zb("/dev/tty",1280);Zb("/dev/tty1",1536);var a=qb();oc("/dev","random",a);oc("/dev","urandom",a);Yb("/dev/shm");Yb("/dev/shm/tmp")})();
(function(){Yb("/proc");var a=Yb("/proc/self");Yb("/proc/self/fd");Wb({qe:function(){var b=zb(a,"fd",16895,73);b.$d={lookup:function(c,d){var e=Eb[+d];if(!e)throw new J(8);c={parent:null,qe:{lf:"fake"},$d:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=lc;h.FS_createDataFile=nc;h.FS_createPreloadedFile=rc;h.FS_createLazyFile=qc;h.FS_createDevice=oc;h.FS_unlink=ac;h.requestFullscreen=function(a,b){id(a,b)};h.requestAnimationFrame=function(a){Ic(a)};
h.setCanvasSize=function(a,b,c){kd(h.canvas,a,b);c||ld()};h.pauseMainLoop=function(){Fc=null;Kc++};h.resumeMainLoop=function(){Kc++;var a=Bc,b=Cc,c=Dc;Dc=null;Jc(c,0,!1,Mc,!0);Ac(a,b);Fc()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return ad(a,b,c,d)};for(var N,Y=0;32>Y;++Y)xe.push(Array(Y));var Ze=new Float32Array(288);
for(Y=0;288>Y;++Y)Ge[Y]=Ze.subarray(0,Y+1);var $e=new Int32Array(288);for(Y=0;288>Y;++Y)He[Y]=$e.subarray(0,Y+1);function hb(a,b){var c=Array(Ja(a)+1);a=Ia(a,c,0,c.length);b&&(c.length=a);return c}
var of={_:function(a,b,c,d){l("Assertion failed: "+B(a)+", at: "+[b?B(b):"unknown filename",c,d?B(d):"unknown function"])},X:function(a,b,c){wc=c;try{var d=yc(a);switch(b){case 0:var e=xc();return 0>e?-28:cc(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=xc(),d.flags|=e,0;case 12:return e=xc(),Aa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return w[af()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof uc&&f instanceof J||
l(f),-f.ge}},Za:function(a,b,c){wc=c;try{var d=yc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=xc();return w[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=xc();if(!d.be.Hf)throw new J(59);return d.be.Hf(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:l("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof uc&&f instanceof J||
l(f),-f.ge}},_a:function(a,b,c){wc=c;try{var d=B(a),e=c?xc():0;return cc(d,b,e).fd}catch(f){return"undefined"!==typeof uc&&f instanceof J||l(f),-f.ge}},$a:function(a){try{a=B(a);var b=Ib(a,{parent:!0}).node,c=pb(a),d=Bb(b,c),e=Sb(b,c,!0);if(e)throw new J(e);if(!b.$d.rmdir)throw new J(63);if(d.ve)throw new J(10);try{M.willDeletePath&&M.willDeletePath(a)}catch(f){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.$d.rmdir(b,c);Mb(d);try{if(M.onDeletePath)M.onDeletePath(a)}catch(f){k("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+f.message)}return 0}catch(f){return"undefined"!==typeof uc&&f instanceof J||l(f),-f.ge}},cb:function(a,b){try{a=B(a);a:{try{var c=Ib(a,{Fe:!0}).node;if(!c)throw new J(44);if(!c.$d.oe)throw new J(63);var d=c.$d.oe(c)}catch(f){if(f&&f.node&&nb(a)!==nb(Kb(f.node))){var e=-54;break a}throw f;}w[b>>2]=d.dev;w[b+4>>2]=0;w[b+8>>2]=d.ino;w[b+12>>2]=d.mode;w[b+16>>2]=d.nlink;w[b+20>>2]=d.uid;w[b+24>>2]=d.gid;w[b+28>>2]=d.rdev;w[b+32>>2]=0;x=[d.size>>>0,(y=d.size,1<=+Math.abs(y)?
0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[b+40>>2]=x[0];w[b+44>>2]=x[1];w[b+48>>2]=4096;w[b+52>>2]=d.blocks;w[b+56>>2]=d.atime.getTime()/1E3|0;w[b+60>>2]=0;w[b+64>>2]=d.mtime.getTime()/1E3|0;w[b+68>>2]=0;w[b+72>>2]=d.ctime.getTime()/1E3|0;w[b+76>>2]=0;x=[d.ino>>>0,(y=d.ino,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[b+80>>2]=x[0];w[b+84>>2]=x[1];e=0}return e}catch(f){return"undefined"!==
typeof uc&&f instanceof J||l(f),-f.ge}},bb:function(a){try{return a=B(a),ac(a),0}catch(b){return"undefined"!==typeof uc&&b instanceof J||l(b),-b.ge}},wa:function(){l()},o:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=zc();else return w[af()>>2]=28,-1;w[b>>2]=a/1E3|0;w[b+4>>2]=a%1E3*1E6|0;return 0},ya:function(){l("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Pa:function(a){if(12448==a)return P=12288,1;P=
12300;return 0},wb:function(a,b,c,d,e){if(62E3!=a)P=12296,c=0;else{if(b)for(;;){a=w[b>>2];if(12321==a)Q.alpha=0<w[b+4>>2];else if(12325==a)Q.depth=0<w[b+4>>2];else if(12326==a)Q.stencil=0<w[b+4>>2];else if(12337==a)a=w[b+4>>2],Q.antialias=0<a;else if(12338==a)a=w[b+4>>2],Q.antialias=1==a;else if(12544==a)Q.bg=12547!=w[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(w[e>>2]=1),c&&0<d&&(w[c>>2]=62002),P=12288,c=1):(P=12300,c=0)}return c},Fa:function(a,b,c,d){if(62E3!=a)return P=12296,0;for(a=1;;){b=
w[d>>2];if(12440==b)a=w[d+4>>2];else if(12344==b)break;else return P=12292,0;d+=8}if(2!=a)return P=12293,0;Q.jf=a-1;Q.cg=0;td=cd(h.canvas,Q);if(0!=td)return P=12288,ed(td),h.Sf=!0,Uc.forEach(function(e){e()}),ed(null),62004;P=12297;return 0},Ha:function(a,b){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;P=12288;return 62006},Ga:function(a,b){if(62E3!=a)return P=12296,0;if(62004!=b)return P=12294,0;a=td;Ld===dd[a]&&(Ld=null);if("object"===typeof Zd)for(var c=dd[a].re.canvas,d=0;d<Od.length;++d)Od[d].target!=
c||Pd(d--);dd[a]&&dd[a].re.canvas&&(dd[a].re.canvas.ye=void 0);dd[a]=null;P=12288;pd==b&&(pd=0);return 1},Ia:function(a,b){if(62E3!=a)return P=12296,0;if(62006!=b)return P=12301,1;qd==b&&(qd=0);rd==b&&(rd=0);P=12288;return 1},Hb:function(a,b,c,d){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;if(!d)return P=12300,0;P=12288;switch(c){case 12320:return w[d>>2]=Q.alpha?32:24,1;case 12321:return w[d>>2]=Q.alpha?8:0,1;case 12322:return w[d>>2]=8,1;case 12323:return w[d>>2]=8,1;case 12324:return w[d>>
2]=8,1;case 12325:return w[d>>2]=Q.depth?24:0,1;case 12326:return w[d>>2]=Q.stencil?8:0,1;case 12327:return w[d>>2]=12344,1;case 12328:return w[d>>2]=62002,1;case 12329:return w[d>>2]=0,1;case 12330:return w[d>>2]=4096,1;case 12331:return w[d>>2]=16777216,1;case 12332:return w[d>>2]=4096,1;case 12333:return w[d>>2]=0,1;case 12334:return w[d>>2]=0,1;case 12335:return w[d>>2]=12344,1;case 12337:return w[d>>2]=Q.antialias?4:0,1;case 12338:return w[d>>2]=Q.antialias?1:0,1;case 12339:return w[d>>2]=4,
1;case 12340:return w[d>>2]=12344,1;case 12341:case 12342:case 12343:return w[d>>2]=-1,1;case 12345:case 12346:return w[d>>2]=0,1;case 12347:return w[d>>2]=0,1;case 12348:return w[d>>2]=1;case 12349:case 12350:return w[d>>2]=0,1;case 12351:return w[d>>2]=12430,1;case 12352:return w[d>>2]=4,1;case 12354:return w[d>>2]=0,1;default:return P=12292,0}},U:function(){P=12288;return 62E3},Ea:function(){return P},ab:function(a,b,c){if(62E3==a)return b&&(w[b>>2]=1),c&&(w[c>>2]=4),od=!0,P=12288,1;P=12296;return 0},
Ja:function(a,b,c,d){if(62E3!=a)return P=12296,0;if(0!=d&&62004!=d)return P=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return P=12301,0;ed(d?td:null);pd=d;rd=b;qd=c;P=12288;return 1},Da:function(a,b){if(62E3!=a)return P=12296,0;P=12288;if(sd[b])return sd[b];switch(b){case 12371:a=Ka("Emscripten");break;case 12372:a=Ka("1.4 Emscripten EGL");break;case 12373:a=Ka("");break;case 12429:a=Ka("OpenGL_ES");break;default:return P=12300,0}return sd[b]=a},Ka:function(){if(od)if(h.ne)if(h.ne.isContextLost())P=
12302;else return P=12288,1;else P=12290;else P=12289;return 0},Ma:function(a,b){if(62E3!=a)return P=12296,0;0==b?Ac(0,0):Ac(1,b);P=12288;return 1},lb:function(a){if(62E3!=a)return P=12296,0;rd=qd=pd=0;od=!1;P=12288;return 1},Oa:function(){P=12288;return 1},Na:function(){P=12288;return 1},d:function(a,b,c){Ye.length=0;var d;for(c>>=2;d=D[b++];)(d=105>d)&&c&1&&c++,Ye.push(d?Ca[c++>>1]:w[c]),++c;return jb[a].apply(null,Ye)},za:function(){if(!Yd())return-1;Sd(te);var a=me[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ba:function(){Sd(ue);if(document.exitPointerLock)document.exitPointerLock();else if(document.ee)document.ee();else return-1;return 0},j:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},g:function(a,b,c){a=V(a);if(!a)return-4;a=se(a);Ca[b>>3]=a.width;Ca[c>>3]=a.height;return 0},x:function(a,b){if(0>a||a>=$d.length)return-5;if(!$d[a])return-7;ve(b,$d[a]);
return 0},xa:function(){return $d.length},La:we,Ca:function(a,b,c){a=h._fileno(a);return(a=Eb[a])?we(a.path,b,c):0},ca:function(a){N.activeTexture(a)},ba:function(a,b){N.attachShader(R[a],T[b])},sa:function(a,b){N.le.beginQueryEXT(a,Dd[b])},aa:function(a,b,c){N.bindAttribLocation(R[a],b,B(c))},$:function(a,b){N.bindBuffer(a,yd[b])},Nd:function(a,b){N.bindFramebuffer(a,zd[b])},Md:function(a,b){N.bindRenderbuffer(a,Ad[b])},Ld:function(a,b){N.bindTexture(a,Bd[b])},ka:function(a){N.bindVertexArray(Cd[a])},
Kd:function(a,b,c,d){N.blendColor(a,b,c,d)},Jd:function(a){N.blendEquation(a)},Id:function(a,b){N.blendEquationSeparate(a,b)},Hd:function(a,b){N.blendFunc(a,b)},Gd:function(a,b,c,d){N.blendFuncSeparate(a,b,c,d)},Fd:function(a,b,c,d){N.bufferData(a,c?D.subarray(c,c+b):b,d)},Ed:function(a,b,c,d){N.bufferSubData(a,b,D.subarray(d,d+c))},Dd:function(a){return N.checkFramebufferStatus(a)},Cd:function(a){N.clear(a)},Bd:function(a,b,c,d){N.clearColor(a,b,c,d)},Ad:function(a){N.clearDepth(a)},zd:function(a){N.clearStencil(a)},
yd:function(a,b,c,d){N.colorMask(!!a,!!b,!!c,!!d)},xd:function(a){N.compileShader(T[a])},wd:function(a,b,c,d,e,f,g,m){N.compressedTexImage2D(a,b,c,d,e,f,m?D.subarray(m,m+g):null)},vd:function(a,b,c,d,e,f,g,m,n){N.compressedTexSubImage2D(a,b,c,d,e,f,g,n?D.subarray(n,n+m):null)},ud:function(a,b,c,d,e,f,g,m){N.copyTexImage2D(a,b,c,d,e,f,g,m)},td:function(a,b,c,d,e,f,g,m){N.copyTexSubImage2D(a,b,c,d,e,f,g,m)},sd:function(){var a=Id(R),b=N.createProgram();b.name=a;R[a]=b;return a},rd:function(a){var b=
Id(T);T[b]=N.createShader(a);return b},qd:function(a){N.cullFace(a)},pd:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=yd[d];e&&(N.deleteBuffer(e),e.name=0,yd[d]=null)}},od:function(a,b){for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=zd[d];e&&(N.deleteFramebuffer(e),e.name=0,zd[d]=null)}},nd:function(a){if(a){var b=R[a];b?(N.deleteProgram(b),b.name=0,R[a]=null,Ed[a]=null):U(1281)}},ua:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Dd[d];e&&(N.le.deleteQueryEXT(e),Dd[d]=null)}},md:function(a,
b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Ad[d];e&&(N.deleteRenderbuffer(e),e.name=0,Ad[d]=null)}},ld:function(a){if(a){var b=T[a];b?(N.deleteShader(b),T[a]=null):U(1281)}},kd:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Bd[d];e&&(N.deleteTexture(e),e.name=0,Bd[d]=null)}},ja:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];N.deleteVertexArray(Cd[d]);Cd[d]=null}},jd:function(a){N.depthFunc(a)},id:function(a){N.depthMask(!!a)},hd:function(a,b){N.depthRange(a,b)},gd:function(a,b){N.detachShader(R[a],
T[b])},fd:function(a){N.disable(a)},ed:function(a){N.disableVertexAttribArray(a)},dd:function(a,b,c){N.drawArrays(a,b,c)},fa:function(a,b,c,d){N.drawArraysInstanced(a,b,c,d)},ga:function(a,b){for(var c=xe[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];N.drawBuffers(c)},cd:function(a,b,c,d){N.drawElements(a,b,c,d)},ea:function(a,b,c,d,e){N.drawElementsInstanced(a,b,c,d,e)},bd:function(a){N.enable(a)},ad:function(a){N.enableVertexAttribArray(a)},ra:function(a){N.le.endQueryEXT(a)},$c:function(){N.finish()},_c:function(){N.flush()},
Zc:function(a,b,c,d){N.framebufferRenderbuffer(a,b,c,Ad[d])},Yc:function(a,b,c,d,e){N.framebufferTexture2D(a,b,c,Bd[d],e)},Xc:function(a){N.frontFace(a)},Wc:function(a,b){ye(a,b,"createBuffer",yd)},Uc:function(a,b){ye(a,b,"createFramebuffer",zd)},va:function(a,b){for(var c=0;c<a;c++){var d=N.le.createQueryEXT();if(!d){for(U(1282);c<a;)w[b+4*c++>>2]=0;break}var e=Id(Dd);d.name=e;Dd[e]=d;w[b+4*c>>2]=e}},Tc:function(a,b){ye(a,b,"createRenderbuffer",Ad)},Sc:function(a,b){ye(a,b,"createTexture",Bd)},ia:function(a,
b){ye(a,b,"createVertexArray",Cd)},Vc:function(a){N.generateMipmap(a)},Rc:function(a,b,c,d,e,f,g){ze("getActiveAttrib",a,b,c,d,e,f,g)},Qc:function(a,b,c,d,e,f,g){ze("getActiveUniform",a,b,c,d,e,f,g)},Pc:function(a,b,c,d){a=N.getAttachedShaders(R[a]);var e=a.length;e>b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+4*b>>2]=T.indexOf(a[b])},Oc:function(a,b){return N.getAttribLocation(R[a],B(b))},Nc:function(a,b){Be(a,b,4)},Mc:function(a,b,c){c?w[c>>2]=N.getBufferParameter(a,b):U(1281)},Lc:function(){var a=N.getError()||
Hd;Hd=0;return a},Kc:function(a,b){Be(a,b,2)},Jc:function(a,b,c,d){a=N.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},Ic:function(a,b){Be(a,b,0)},Fc:function(a,b,c,d){a=N.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(w[c>>2]=b)},Gc:function(a,b,c){if(c)if(a>=xd)U(1281);else{var d=Ed[a];if(d)if(35716==b)a=N.getProgramInfoLog(R[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==
b)w[c>>2]=d.Pe;else if(35722==b){if(-1==d.Ae){a=R[a];var e=N.getProgramParameter(a,35721);for(b=d.Ae=0;b<e;++b)d.Ae=Math.max(d.Ae,N.getActiveAttrib(a,b).name.length+1)}w[c>>2]=d.Ae}else if(35381==b){if(-1==d.Be)for(a=R[a],e=N.getProgramParameter(a,35382),b=d.Be=0;b<e;++b)d.Be=Math.max(d.Be,N.getActiveUniformBlockName(a,b).length+1);w[c>>2]=d.Be}else w[c>>2]=N.getProgramParameter(R[a],b);else U(1282)}else U(1281)},ma:function(a,b,c){if(c){a=N.le.getQueryObjectEXT(Dd[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;Ae(c,d)}else U(1281)},oa:function(a,b,c){if(c){a=N.le.getQueryObjectEXT(Dd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else U(1281)},la:function(a,b,c){if(c){a=N.le.getQueryObjectEXT(Dd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Ae(c,d)}else U(1281)},na:function(a,b,c){if(c){a=N.le.getQueryObjectEXT(Dd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else U(1281)},pa:function(a,b,c){c?w[c>>2]=N.le.getQueryEXT(a,b):U(1281)},Ec:function(a,b,c){c?w[c>>2]=N.getRenderbufferParameter(a,
b):U(1281)},Cc:function(a,b,c,d){a=N.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(w[c>>2]=b)},Bc:function(a,b,c,d){a=N.getShaderPrecisionFormat(a,b);w[c>>2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},Ac:function(a,b,c,d){if(a=N.getShaderSource(T[a]))b=0<b&&d?E(a,d,b):0,c&&(w[c>>2]=b)},Dc:function(a,b,c){c?35716==b?(a=N.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(T[a]),w[c>>2]=a?a.length+1:
0):w[c>>2]=N.getShaderParameter(T[a],b):U(1281)},zc:function(a){if(Fd[a])return Fd[a];switch(a){case 7939:var b=N.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Ce(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=N.getParameter(a))||U(1280);b=Ce(b);break;case 7938:b=Ce("OpenGL ES 2.0 ("+N.getParameter(7938)+")");break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),
b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ce(b);break;default:return U(1280),0}return Fd[a]=b},yc:function(a,b,c){c?A[c>>2]=N.getTexParameter(a,b):U(1281)},xc:function(a,b,c){c?w[c>>2]=N.getTexParameter(a,b):U(1281)},tc:function(a,b){b=B(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Ed[a]&&Ed[a].rf[b])&&0<=c&&c<a[0]?a[1]+c:-1},vc:function(a,b,c){De(a,b,c,2)},uc:function(a,b,c){De(a,b,c,0)},qc:function(a,b,c){c?w[c>>2]=N.getVertexAttribOffset(a,
b):U(1281)},sc:function(a,b,c){Ee(a,b,c,2)},rc:function(a,b,c){Ee(a,b,c,5)},pc:function(a,b){N.hint(a,b)},oc:function(a){return(a=yd[a])?N.isBuffer(a):0},nc:function(a){return N.isEnabled(a)},mc:function(a){return(a=zd[a])?N.isFramebuffer(a):0},lc:function(a){return(a=R[a])?N.isProgram(a):0},ta:function(a){return(a=Dd[a])?N.le.isQueryEXT(a):0},kc:function(a){return(a=Ad[a])?N.isRenderbuffer(a):0},jc:function(a){return(a=T[a])?N.isShader(a):0},ic:function(a){return(a=Bd[a])?N.isTexture(a):0},ha:function(a){return(a=
Cd[a])?N.isVertexArray(a):0},hc:function(a){N.lineWidth(a)},gc:function(a){N.linkProgram(R[a]);var b=R[a];a=Ed[a]={rf:{},Pe:0,Ae:-1,Be:-1};for(var c=a.rf,d=N.getProgramParameter(b,35718),e=0;e<d;++e){var f=N.getActiveUniform(b,e),g=f.name;a.Pe=Math.max(a.Pe,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var m=N.getUniformLocation(b,g);if(m){var n=Id(S);c[g]=[f.size,n];S[n]=m;for(var r=1;r<f.size;++r)m=N.getUniformLocation(b,g+"["+r+"]"),n=Id(S),S[n]=m}}},fc:function(a,b){3317==a&&
(Gd=b);N.pixelStorei(a,b)},ec:function(a,b){N.polygonOffset(a,b)},qa:function(a,b){N.le.queryCounterEXT(Dd[a],b)},dc:function(a,b,c,d,e,f,g){(g=Fe(f,e,c,d,g))?N.readPixels(a,b,c,d,e,f,g):U(1280)},cc:function(){},bc:function(a,b,c,d){N.renderbufferStorage(a,b,c,d)},ac:function(a,b){N.sampleCoverage(a,!!b)},$b:function(a,b,c,d){N.scissor(a,b,c,d)},_b:function(){U(1280)},Zb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?w[d+4*f>>2]:-1;e+=B(w[c+4*f>>2],0>g?void 0:g)}N.shaderSource(T[a],e)},Yb:function(a,
b,c){N.stencilFunc(a,b,c)},Xb:function(a,b,c,d){N.stencilFuncSeparate(a,b,c,d)},Wb:function(a){N.stencilMask(a)},Vb:function(a,b){N.stencilMaskSeparate(a,b)},Ub:function(a,b,c){N.stencilOp(a,b,c)},Rb:function(a,b,c,d){N.stencilOpSeparate(a,b,c,d)},Qb:function(a,b,c,d,e,f,g,m,n){N.texImage2D(a,b,c,d,e,f,g,m,n?Fe(m,g,d,e,n):null)},Pb:function(a,b,c){N.texParameterf(a,b,c)},Ob:function(a,b,c){N.texParameterf(a,b,A[c>>2])},Nb:function(a,b,c){N.texParameteri(a,b,c)},Mb:function(a,b,c){N.texParameteri(a,
b,w[c>>2])},Lb:function(a,b,c,d,e,f,g,m,n){var r=null;n&&(r=Fe(m,g,e,f,n));N.texSubImage2D(a,b,c,d,e,f,g,m,r)},Kb:function(a,b){N.uniform1f(S[a],b)},Jb:function(a,b,c){if(288>=b)for(var d=Ge[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);N.uniform1fv(S[a],d)},Ib:function(a,b){N.uniform1i(S[a],b)},Gb:function(a,b,c){if(288>=b)for(var d=He[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);N.uniform1iv(S[a],d)},Fb:function(a,b,c){N.uniform2f(S[a],b,c)},Eb:function(a,
b,c){if(144>=b)for(var d=Ge[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);N.uniform2fv(S[a],d)},Db:function(a,b,c){N.uniform2i(S[a],b,c)},Cb:function(a,b,c){if(144>=b)for(var d=He[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);N.uniform2iv(S[a],d)},Bb:function(a,b,c,d){N.uniform3f(S[a],b,c,d)},Ab:function(a,b,c){if(96>=b)for(var d=Ge[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=
A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);N.uniform3fv(S[a],d)},zb:function(a,b,c,d){N.uniform3i(S[a],b,c,d)},yb:function(a,b,c){if(96>=b)for(var d=He[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);N.uniform3iv(S[a],d)},xb:function(a,b,c,d,e){N.uniform4f(S[a],b,c,d,e)},vb:function(a,b,c){if(72>=b){var d=Ge[4*b-1],e=A;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=A.subarray(c>>
2,c+16*b>>2);N.uniform4fv(S[a],d)},ub:function(a,b,c,d,e){N.uniform4i(S[a],b,c,d,e)},tb:function(a,b,c){if(72>=b)for(var d=He[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);N.uniform4iv(S[a],d)},sb:function(a,b,c,d){if(72>=b)for(var e=Ge[4*b-1],f=0;f<4*b;f+=4)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);N.uniformMatrix2fv(S[a],
!!c,e)},rb:function(a,b,c,d){if(32>=b)for(var e=Ge[9*b-1],f=0;f<9*b;f+=9)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2],e[f+4]=A[d+(4*f+16)>>2],e[f+5]=A[d+(4*f+20)>>2],e[f+6]=A[d+(4*f+24)>>2],e[f+7]=A[d+(4*f+28)>>2],e[f+8]=A[d+(4*f+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);N.uniformMatrix3fv(S[a],!!c,e)},qb:function(a,b,c,d){if(18>=b){var e=Ge[16*b-1],f=A;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+
4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(S[a],!!c,e)},pb:function(a){N.useProgram(R[a])},ob:function(a){N.validateProgram(R[a])},nb:function(a,b){N.vertexAttrib1f(a,b)},mb:function(a,b){N.vertexAttrib1f(a,A[b>>2])},kb:function(a,b,c){N.vertexAttrib2f(a,b,c)},jb:function(a,b){N.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},ib:function(a,
b,c,d){N.vertexAttrib3f(a,b,c,d)},hb:function(a,b){N.vertexAttrib3f(a,A[b>>2],A[b+4>>2],A[b+8>>2])},gb:function(a,b,c,d,e){N.vertexAttrib4f(a,b,c,d,e)},fb:function(a,b){N.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+8>>2],A[b+12>>2])},da:function(a,b){N.vertexAttribDivisor(a,b)},eb:function(a,b,c,d,e,f){N.vertexAttribPointer(a,b,c,!!d,e,f)},db:function(a,b,c,d){N.viewport(a,b,c,d)},r:function(){return 0},e:function(a,b){Z(a,b||1);throw"longjmp";},Ta:function(a,b,c){D.copyWithin(a,b,b+c)},Aa:function(a,
b,c){return Ie(a,{Se:w[c>>2],Ke:w[c+4>>2],Bf:w[c+8>>2],yf:b,Ee:w[c+12>>2],Ye:w[c+16>>2]})},T:function(a,b){a=V(a);return a?a.requestPointerLock||a.Ie?Md&&Ud.se?ue(a):b?(Rd(ue,2,[a]),1):-2:-1:-4},Ua:function(a){var b=D.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{Da.grow(Math.min(2147483648,d)-Na.byteLength+65535>>>16);Qa(Da.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},y:function(){return($d=
navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},z:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;Je(a,b);return 0},L:function(a,b,c,d){Ke(a,b,c,d,12,"blur");return 0},i:oe,p:function(a,b,c){a=V(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},M:function(a,b,c,d){Ke(a,b,c,d,13,"focus");return 0},C:function(a,b,c,d){if(!Yd())return-1;a=V(a);if(!a)return-4;Le(a,b,c,d,"fullscreenchange");
Le(a,b,c,d,"webkitfullscreenchange");return 0},w:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Me(a,b,c,26,"gamepadconnected");return 0},v:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Me(a,b,c,27,"gamepaddisconnected");return 0},F:function(a,b,c,d){Ne(a,b,c,d,2,"keydown");return 0},D:function(a,b,c,d){Ne(a,b,c,d,1,"keypress");return 0},E:function(a,b,c,d){Ne(a,b,c,d,3,"keyup");return 0},Tb:function(a,b,c){a=G.get(a);Jc(a,b,c)},
R:function(a,b,c,d){Pe(a,b,c,d,5,"mousedown");return 0},P:function(a,b,c,d){Pe(a,b,c,d,33,"mouseenter");return 0},O:function(a,b,c,d){Pe(a,b,c,d,34,"mouseleave");return 0},S:function(a,b,c,d){Pe(a,b,c,d,8,"mousemove");return 0},Q:function(a,b,c,d){Pe(a,b,c,d,6,"mouseup");return 0},G:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ee||document.body.ze||document.body.Ie))return-1;a=V(a);if(!a)return-4;Qe(a,b,c,d,"pointerlockchange");Qe(a,b,c,d,"mozpointerlockchange");
Qe(a,b,c,d,"webkitpointerlockchange");Qe(a,b,c,d,"mspointerlockchange");return 0},B:function(a,b,c,d){Re(a,b,c,d);return 0},H:function(a,b,c,d){Se(a,b,c,d,25,"touchcancel");return 0},J:function(a,b,c,d){Se(a,b,c,d,23,"touchend");return 0},I:function(a,b,c,d){Se(a,b,c,d,24,"touchmove");return 0},K:function(a,b,c,d){Se(a,b,c,d,22,"touchstart");return 0},A:function(a,b,c){if(!me[1])return-4;Te(a,b,c);return 0},N:function(a,b,c,d){a=V(a);return"undefined"!==typeof a.onwheel?(Ue(a,b,c,d),0):-1},q:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},Xa:function(a){for(var b=zc();zc()-b<a;);},Va:function(a,b){try{var c=0;We().forEach(function(d,e){var f=b+c;e=w[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++>>0]=d.charCodeAt(f);q[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof uc&&d instanceof J||l(d),d.ge}},Wa:function(a,b){try{var c=We();w[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});w[b>>2]=d;return 0}catch(e){return"undefined"!==typeof uc&&e instanceof J||l(e),e.ge}},t:function(a){Lc(a)},W:function(a){try{var b=
yc(a);ec(b);return 0}catch(c){return"undefined"!==typeof uc&&c instanceof J||l(c),c.ge}},Ya:function(a,b,c,d){try{a:{for(var e=yc(a),f=a=0;f<c;f++){var g=w[b+(8*f+4)>>2],m=e,n=w[b+8*f>>2],r=g,p=void 0,t=q;if(0>r||0>p)throw new J(28);if(null===m.fd)throw new J(8);if(1===(m.flags&2097155))throw new J(8);if(L(m.node.mode))throw new J(31);if(!m.be.read)throw new J(28);var u="undefined"!==typeof p;if(!u)p=m.position;else if(!m.seekable)throw new J(70);var v=m.be.read(m,t,n,r,p);u||(m.position+=v);var z=
v;if(0>z){var C=-1;break a}a+=z;if(z<g)break}C=a}w[d>>2]=C;return 0}catch(H){return"undefined"!==typeof uc&&H instanceof J||l(H),H.ge}},Qa:function(a,b,c,d,e){try{var f=yc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;fc(f,a,d);x=[f.position>>>0,(y=f.position,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[e>>2]=x[0];w[e+4>>2]=x[1];f.Ne&&0===a&&0===d&&(f.Ne=null);return 0}catch(g){return"undefined"!==
typeof uc&&g instanceof J||l(g),g.ge}},V:function(a,b,c,d){try{a:{for(var e=yc(a),f=a=0;f<c;f++){var g=hc(e,q,w[b+8*f>>2],w[b+(8*f+4)>>2],void 0);if(0>g){var m=-1;break a}a+=g}m=a}w[d>>2]=m;return 0}catch(n){return"undefined"!==typeof uc&&n instanceof J||l(n),n.ge}},b:function(){return xa},n:function(a){var b=Date.now();w[a>>2]=b/1E3|0;w[a+4>>2]=b%1E3*1E3|0;return 0},wc:bf,m:cf,k:df,s:ef,u:ff,Hc:gf,Y:hf,Sa:jf,Ra:kf,h:lf,l:mf,Z:nf,a:Da,c:function(a){xa=a},f:function(){return 0},Sb:function(){return 0}};
(function(){function a(e){h.asm=e.exports;pf();G=h.asm.Rd;Ta.unshift(h.asm.Od);bb("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return gb().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){k("failed to asynchronously prepare wasm: "+f);if("undefined"!==typeof location){var g=location.search;if(0>g.indexOf("_rwasm=0")){location.href+=(g?g+"&":"?")+"_rwasm=0";return}}l(f)})}var d={a:of};ab("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(d,
a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ya||"function"!==typeof WebAssembly.instantiateStreaming||eb(I)||db(I,"file://")||"function"!==typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.Od).apply(null,arguments)};var F=h._malloc=function(){return(F=h._malloc=h.asm.Pd).apply(null,arguments)};h._main=function(){return(h._main=h.asm.Qd).apply(null,arguments)};var af=h.___errno_location=function(){return(af=h.___errno_location=h.asm.Sd).apply(null,arguments)};h._fileno=function(){return(h._fileno=h.asm.Td).apply(null,arguments)};
var W=h.stackSave=function(){return(W=h.stackSave=h.asm.Ud).apply(null,arguments)},X=h.stackRestore=function(){return(X=h.stackRestore=h.asm.Vd).apply(null,arguments)},Ma=h.stackAlloc=function(){return(Ma=h.stackAlloc=h.asm.Wd).apply(null,arguments)},Z=h._setThrew=function(){return(Z=h._setThrew=h.asm.Xd).apply(null,arguments)};h.dynCall_iiji=function(){return(h.dynCall_iiji=h.asm.Yd).apply(null,arguments)};
var qf=h.dynCall_ji=function(){return(qf=h.dynCall_ji=h.asm.Zd).apply(null,arguments)},rf=h.dynCall_jiji=function(){return(rf=h.dynCall_jiji=h.asm._d).apply(null,arguments)};function cf(a,b){var c=W();try{return G.get(a)(b)}catch(d){X(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function ff(a,b,c,d,e){var f=W();try{return G.get(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}
function ef(a,b,c,d){var e=W();try{return G.get(a)(b,c,d)}catch(f){X(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function lf(a,b){var c=W();try{G.get(a)(b)}catch(d){X(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function nf(a,b,c,d){var e=W();try{G.get(a)(b,c,d)}catch(f){X(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function mf(a,b,c){var d=W();try{G.get(a)(b,c)}catch(e){X(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}
function df(a,b,c){var d=W();try{return G.get(a)(b,c)}catch(e){X(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}function hf(a,b,c,d,e,f,g,m,n,r){var p=W();try{return G.get(a)(b,c,d,e,f,g,m,n,r)}catch(t){X(p);if(t!==t+0&&"longjmp"!==t)throw t;Z(1,0)}}function gf(a,b,c,d,e,f,g,m,n){var r=W();try{return G.get(a)(b,c,d,e,f,g,m,n)}catch(p){X(r);if(p!==p+0&&"longjmp"!==p)throw p;Z(1,0)}}function bf(a){var b=W();try{return G.get(a)()}catch(c){X(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}
function jf(a,b){var c=W();try{return qf(a,b)}catch(d){X(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function kf(a,b,c,d,e){var f=W();try{return rf(a,b,c,d,e)}catch(g){X(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}h.addRunDependency=ab;h.removeRunDependency=bb;h.FS_createPath=lc;h.FS_createDataFile=nc;h.FS_createPreloadedFile=rc;h.FS_createLazyFile=qc;h.FS_createDevice=oc;h.FS_unlink=ac;
function pf(){if(cb)if(eb(cb)||(cb=la(cb)),ia||ja){var a=oa(cb);D.set(a,1024)}else{ab("memory initializer");var b=function(d){d.byteLength&&(d=new Uint8Array(d));D.set(d,1024);h.memoryInitializerRequest&&delete h.memoryInitializerRequest.response;bb("memory initializer")},c=function(){na(cb,b,function(){throw Error("could not load memory initializer "+cb);})};h.memoryInitializerRequest?(a=function(){var d=h.memoryInitializerRequest,e=d.response;200!==d.status&&0!==d.status?(console.warn("a problem seems to have happened with Module.memoryInitializerRequest, status: "+
d.status+", retrying "+cb),c()):b(e)},h.memoryInitializerRequest.response?setTimeout(a,0):h.memoryInitializerRequest.addEventListener("load",a)):c()}}var sf;function ta(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}$a=function tf(){sf||uf();sf||($a=tf)};
function uf(a){function b(){if(!sf&&(sf=!0,h.calledRun=!0,!Ea)){h.noFSInit||jc||(jc=!0,ic(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?oc("/dev","stdin",h.stdin):$b("/dev/tty","/dev/stdin"),h.stdout?oc("/dev","stdout",null,h.stdout):$b("/dev/tty","/dev/stdout"),h.stderr?oc("/dev","stderr",null,h.stderr):$b("/dev/tty1","/dev/stderr"),cc("/dev/stdin",0),cc("/dev/stdout",1),cc("/dev/stderr",1));lb(Ta);Hb=!1;lb(Ua);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(vf){var c=a,d=h._main;
c=c||[];var e=c.length+1,f=Ma(4*(e+1));w[f>>2]=La(da);for(var g=1;g<e;g++)w[(f>>2)+g]=La(c[g-1]);w[(f>>2)+e]=0;try{var m=d(e,f);Lc(m,!0)}catch(n){n instanceof ta||"unwind"==n||((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),k("exception thrown: "+c),ea(1,n))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Wa.unshift(c);lb(Wa)}}a=a||ca;if(!(0<Ya)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Xa();
lb(Sa);0<Ya||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=uf;function Lc(a,b){Fa=a;if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(h.onExit)h.onExit(a);Ea=!0}ea(a,new ta(a))}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var vf=!0;h.noInitialRun&&(vf=!1);uf();
