#define GAME_TITLE "Basque"
#define DEBUG_MODE 1

// int SCREEN_HEIGHT = 630;
// int SCREEN_WIDTH = 1120;
// int SCREEN_HEIGHT = 600;
// int SCREEN_WIDTH = 800;

int SCREEN_HEIGHT = 864;
int SCREEN_WIDTH = 704;

int DETECT_RESOLUTION = 1;
int FULLSCREEN_MODE = 0;

#define PLAYER_SPRITE_HEIGHT 28
#define PLAYER_SPRITE_WIDTH 16
#define PLAYER_SPRITE_ROW_HEIGHT 32
#define PLAYER_SPRITE_COLUMN_WIDTH 16

#define ATTRIBUTE_LENGTH 8
#define ATTRIBUTE_CHAR_LIMIT 256

#define TILE_SPRITE_HEIGHT 16
#define TILE_SPRITE_WIDTH 16
#define TILE_CHAR_LIMIT 4

// This is a float, but we enforce integers
// with SDL_RenderSetIntegerScale().
#define INITIAL_SCALING 2.0
float SCALING = INITIAL_SCALING;

#define TXT_EXTENSION ".txt"
#define ASSETS_DIR "assets/"
#define DATA_DIR ASSETS_DIR "data/"
#define IMAGE_DIR ASSETS_DIR "images/"
#define AUDIO_DIR ASSETS_DIR "audio/"
#define FONT_DIR ASSETS_DIR "fonts/"

#define MAP_LAYOUT_FILE_BASE DATA_DIR "map_layout"
#define MAP_LAYOUT_FILE MAP_LAYOUT_FILE_BASE TXT_EXTENSION
#define MAP_LAYOUT_FILE_LIMIT 99
#define MAP_LOCK_FILE DATA_DIR "__MAP__._LOCK_"
#define MAP_LIBRARY_FILE DATA_DIR "map_library" TXT_EXTENSION
#define MAP_ATTRIBUTES_FILE DATA_DIR "map_attributes" TXT_EXTENSION
#define PLAYER_IMAGE IMAGE_DIR "character.png"
#define BACKGROUND_IMAGE IMAGE_DIR "tiles_packed.png"

#define MUSIC_INTRO_FILE AUDIO_DIR "Basque_sample_music.ogg"
#define MUSIC_VOLUME (MIX_MAX_VOLUME / 4)
// #define MUSIC_VOLUME 0

#define EDITOR_FONT FONT_DIR "BPtypewrite.ttf"
#define EDITOR_FONT_SIZE 10
#define EDITOR_FONT_OUTLINE 2
#define EDITOR_FONT_DEST_SIZE_H 9
#define EDITOR_FONT_DEST_SIZE_W 10

#define TILE_ATTRIBUTES_LIMIT 500

#define EMPTY_COLUMN -1
#define END_OF_ROW -2

#define PLAYER_INCREMENT 1
#define GLOBAL_INCREMENT (PLAYER_INCREMENT * ((int)INITIAL_SCALING + 1))

#define MIN_FRAMETIME_MSECS 22
